/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const getUsersProfile200RoleEnum = {
  MEMBER: 'MEMBER',
  ADMIN: 'ADMIN',
} as const

export type GetUsersProfile200RoleEnumType = (typeof getUsersProfile200RoleEnum)[keyof typeof getUsersProfile200RoleEnum]

/**
 * @description Informações do perfil do usuário obtidas com sucesso.
 */
export type GetUsersProfile200Type = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  name: string
  /**
   * @type string, email
   */
  email: string
  /**
   * @type string
   */
  role: GetUsersProfile200RoleEnumType
}

/**
 * @description Usuário não autenticado.
 */
export type GetUsersProfile401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Usuário não encontrado.
 */
export type GetUsersProfile404Type = {
  /**
   * @type string
   */
  message: string
}

export type GetUsersProfileQueryResponseType = GetUsersProfile200Type

export type GetUsersProfileTypeQuery = {
  Response: GetUsersProfile200Type
  Errors: GetUsersProfile401Type | GetUsersProfile404Type
}