/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteSuppliersIdPathParamsType = {
  /**
   * @type string
   */
  id: string
}

export const deleteSuppliersId200Enum = {
  null: 'null',
} as const

export type DeleteSuppliersId200EnumType = (typeof deleteSuppliersId200Enum)[keyof typeof deleteSuppliersId200Enum]

/**
 * @description Fornecedor deletado com sucesso.
 */
export type DeleteSuppliersId200Type = DeleteSuppliersId200EnumType | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteSuppliersId401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Fornecedor não encontrado.
 */
export type DeleteSuppliersId404Type = {
  /**
   * @type string
   */
  message: string
}

export type DeleteSuppliersIdMutationResponseType = DeleteSuppliersId200Type

export type DeleteSuppliersIdTypeMutation = {
  Response: DeleteSuppliersId200Type
  PathParams: DeleteSuppliersIdPathParamsType
  Errors: DeleteSuppliersId401Type | DeleteSuppliersId404Type
}