/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteCustomersIdPathParamsType = {
  /**
   * @type string
   */
  id: string
}

export const deleteCustomersId200Enum = {
  null: 'null',
} as const

export type DeleteCustomersId200EnumType =
  (typeof deleteCustomersId200Enum)[keyof typeof deleteCustomersId200Enum]

/**
 * @description Cliente deletado com sucesso.
 */
export type DeleteCustomersId200Type = DeleteCustomersId200EnumType | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteCustomersId401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Cliente não encontrado.
 */
export type DeleteCustomersId404Type = {
  /**
   * @type string
   */
  message: string
}

export type DeleteCustomersIdMutationResponseType = DeleteCustomersId200Type

export type DeleteCustomersIdTypeMutation = {
  Response: DeleteCustomersId200Type
  PathParams: DeleteCustomersIdPathParamsType
  Errors: DeleteCustomersId401Type | DeleteCustomersId404Type
}
