/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const postCustomers201Enum = {
  null: 'null',
} as const

export type PostCustomers201EnumType = (typeof postCustomers201Enum)[keyof typeof postCustomers201Enum]

/**
 * @description Cliente cadastrado com sucesso.
 */
export type PostCustomers201Type = PostCustomers201EnumType | null

/**
 * @description Usuário não autenticado.
 */
export type PostCustomers401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Cliente já cadastrado.
 */
export type PostCustomers409Type = {
  /**
   * @type string
   */
  message: string
}

export const postCustomersMutationRequestDocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type PostCustomersMutationRequestDocumentTypeEnumType =
  (typeof postCustomersMutationRequestDocumentTypeEnum)[keyof typeof postCustomersMutationRequestDocumentTypeEnum]

export const postCustomersMutationRequestGenderEnum = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const

export type PostCustomersMutationRequestGenderEnumType = (typeof postCustomersMutationRequestGenderEnum)[keyof typeof postCustomersMutationRequestGenderEnum]

export type PostCustomersMutationRequestType = {
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @minLength 1
   * @type string
   */
  phone: string
  /**
   * @type string | undefined
   */
  phone_2?: string
  /**
   * @type string
   */
  document_type: PostCustomersMutationRequestDocumentTypeEnumType
  /**
   * @minLength 1
   * @type string
   */
  document: string
  /**
   * @type string | undefined
   */
  document_2?: string
  /**
   * @minLength 1
   * @type string, email
   */
  email: string
  /**
   * @type string | undefined
   */
  state_registration?: string
  /**
   * @type boolean | undefined
   */
  tax_free?: boolean
  /**
   * @type string | undefined
   */
  gender?: PostCustomersMutationRequestGenderEnumType
  /**
   * @type string | undefined, date-time
   */
  birth_date?: string
  /**
   * @type boolean | undefined
   */
  problematic?: boolean
  /**
   * @minLength 1
   * @type string
   */
  recipient_name: string
  /**
   * @minLength 1
   * @type string
   */
  recipient_phone: string
  /**
   * @minLength 1
   * @type string
   */
  cep: string
  /**
   * @minLength 1
   * @type string
   */
  street: string
  /**
   * @minLength 1
   * @type string
   */
  number: string
  /**
   * @type string | undefined
   */
  complement?: string
  /**
   * @minLength 1
   * @type string
   */
  neighborhood: string
  /**
   * @minLength 1
   * @type string
   */
  city: string
  /**
   * @minLength 1
   * @type string
   */
  state: string
}

export type PostCustomersMutationResponseType = PostCustomers201Type

export type PostCustomersTypeMutation = {
  Response: PostCustomers201Type
  Request: PostCustomersMutationRequestType
  Errors: PostCustomers401Type | PostCustomers409Type
}