/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PutCustomersIdPathParamsType = {
  /**
   * @type string
   */
  id: string
}

export const putCustomersId200Enum = {
  null: 'null',
} as const

export type PutCustomersId200EnumType = (typeof putCustomersId200Enum)[keyof typeof putCustomersId200Enum]

/**
 * @description Cliente atualizado com sucesso.
 */
export type PutCustomersId200Type = PutCustomersId200EnumType | null

/**
 * @description Usuário não autenticado.
 */
export type PutCustomersId401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Cliente não encontrado.
 */
export type PutCustomersId404Type = {
  /**
   * @type string
   */
  message: string
}

export const putCustomersIdMutationRequestDocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type PutCustomersIdMutationRequestDocumentTypeEnumType =
  (typeof putCustomersIdMutationRequestDocumentTypeEnum)[keyof typeof putCustomersIdMutationRequestDocumentTypeEnum]

export const putCustomersIdMutationRequestGenderEnum = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const

export type PutCustomersIdMutationRequestGenderEnumType = (typeof putCustomersIdMutationRequestGenderEnum)[keyof typeof putCustomersIdMutationRequestGenderEnum]

export type PutCustomersIdMutationRequestType = {
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @minLength 1
   * @type string
   */
  phone: string
  /**
   * @type string | undefined
   */
  phone_2?: string
  /**
   * @type string
   */
  document_type: PutCustomersIdMutationRequestDocumentTypeEnumType
  /**
   * @minLength 1
   * @type string
   */
  document: string
  /**
   * @type string | undefined
   */
  document_2?: string
  /**
   * @minLength 1
   * @type string, email
   */
  email: string
  /**
   * @type string | undefined
   */
  state_registration?: string
  /**
   * @type boolean | undefined
   */
  tax_free?: boolean
  /**
   * @type string | undefined
   */
  gender?: PutCustomersIdMutationRequestGenderEnumType
  /**
   * @type string | undefined, date-time
   */
  birth_date?: string
  /**
   * @type boolean | undefined
   */
  problematic?: boolean
  /**
   * @minLength 1
   * @pattern ^[cC][^\s-]{8,}$
   * @type string
   */
  address_id: string
  /**
   * @minLength 1
   * @type string
   */
  recipient_name: string
  /**
   * @minLength 1
   * @type string
   */
  recipient_phone: string
  /**
   * @minLength 1
   * @type string
   */
  cep: string
  /**
   * @minLength 1
   * @type string
   */
  street: string
  /**
   * @minLength 1
   * @type string
   */
  number: string
  /**
   * @type string | undefined
   */
  complement?: string
  /**
   * @minLength 1
   * @type string
   */
  neighborhood: string
  /**
   * @minLength 1
   * @type string
   */
  city: string
  /**
   * @minLength 1
   * @type string
   */
  state: string
}

export type PutCustomersIdMutationResponseType = PutCustomersId200Type

export type PutCustomersIdTypeMutation = {
  Response: PutCustomersId200Type
  Request: PutCustomersIdMutationRequestType
  PathParams: PutCustomersIdPathParamsType
  Errors: PutCustomersId401Type | PutCustomersId404Type
}