/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Usuário cadastrado com sucesso.
 */
export type PostUsers201Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Este email já está cadastrado em nossa base de dados.
 */
export type PostUsers409Type = {
  /**
   * @type string
   */
  message: string
}

export type PostUsersMutationRequestType = {
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @minLength 1
   * @type string, email
   */
  email: string
  /**
   * @minLength 6
   * @type string
   */
  password: string
}

export type PostUsersMutationResponseType = PostUsers201Type

export type PostUsersTypeMutation = {
  Response: PostUsers201Type
  Request: PostUsersMutationRequestType
  Errors: PostUsers409Type
}