/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteEmployeesIdPathParamsType = {
  /**
   * @type string
   */
  id: string
}

export const deleteEmployeesId200Enum = {
  null: 'null',
} as const

export type DeleteEmployeesId200EnumType =
  (typeof deleteEmployeesId200Enum)[keyof typeof deleteEmployeesId200Enum]

/**
 * @description Colaborador deletado com sucesso.
 */
export type DeleteEmployeesId200Type = DeleteEmployeesId200EnumType | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteEmployeesId401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Colaborador não encontrado.
 */
export type DeleteEmployeesId404Type = {
  /**
   * @type string
   */
  message: string
}

export type DeleteEmployeesIdMutationResponseType = DeleteEmployeesId200Type

export type DeleteEmployeesIdTypeMutation = {
  Response: DeleteEmployeesId200Type
  PathParams: DeleteEmployeesIdPathParamsType
  Errors: DeleteEmployeesId401Type | DeleteEmployeesId404Type
}
