/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from '@kubb/plugin-zod/utils'
import { z } from 'zod'
import type {
  DeleteProductsVariationsId200Type,
  DeleteProductsVariationsId401Type,
  DeleteProductsVariationsId404Type,
  DeleteProductsVariationsIdMutationResponseType,
  DeleteProductsVariationsIdPathParamsType,
} from '../../types/Produtos (Varia\u00E7\u00F5es)Types/DeleteProductsVariationsIdType'

export const deleteProductsVariationsIdPathParamsSchema = z.object({
  id: z.string(),
}) as unknown as ToZod<DeleteProductsVariationsIdPathParamsType>

/**
 * @description Variação de produto deletado com sucesso.
 */
export const deleteProductsVariationsId200Schema = z
  .enum(['null'])
  .describe('Variação de produto deletado com sucesso.')
  .nullable() as unknown as ToZod<DeleteProductsVariationsId200Type>

/**
 * @description Usuário não autenticado.
 */
export const deleteProductsVariationsId401Schema = z
  .object({
    message: z.string(),
  })
  .describe(
    'Usuário não autenticado.'
  ) as unknown as ToZod<DeleteProductsVariationsId401Type>

/**
 * @description Variação de produto não encontrado.
 */
export const deleteProductsVariationsId404Schema = z
  .object({
    message: z.string(),
  })
  .describe(
    'Variação de produto não encontrado.'
  ) as unknown as ToZod<DeleteProductsVariationsId404Type>

export const deleteProductsVariationsIdMutationResponseSchema = z.lazy(
  () => deleteProductsVariationsId200Schema
) as unknown as ToZod<DeleteProductsVariationsIdMutationResponseType>
