/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from '@kubb/plugin-zod/utils'
import type {
  DeleteProductsAttributesValuesIdPathParamsType,
  DeleteProductsAttributesValuesId200Type,
  DeleteProductsAttributesValuesId401Type,
  DeleteProductsAttributesValuesId404Type,
  DeleteProductsAttributesValuesIdMutationResponseType,
} from '../../types/Produtos (Atributos)Types/DeleteProductsAttributesValuesIdType.ts'
import { z } from 'zod'

export const deleteProductsAttributesValuesIdPathParamsSchema = z.object({
  id: z.string(),
}) as unknown as ToZod<DeleteProductsAttributesValuesIdPathParamsType>

/**
 * @description Valor de atributo do produto deletado com sucesso.
 */
export const deleteProductsAttributesValuesId200Schema = z
  .enum(['null'])
  .describe('Valor de atributo do produto deletado com sucesso.')
  .nullable() as unknown as ToZod<DeleteProductsAttributesValuesId200Type>

/**
 * @description Usuário não autenticado.
 */
export const deleteProductsAttributesValuesId401Schema = z
  .object({
    message: z.string(),
  })
  .describe('Usuário não autenticado.') as unknown as ToZod<DeleteProductsAttributesValuesId401Type>

/**
 * @description Valor de atributo do produto não encontrado.
 */
export const deleteProductsAttributesValuesId404Schema = z
  .object({
    message: z.string(),
  })
  .describe('Valor de atributo do produto não encontrado.') as unknown as ToZod<DeleteProductsAttributesValuesId404Type>

export const deleteProductsAttributesValuesIdMutationResponseSchema = z.lazy(
  () => deleteProductsAttributesValuesId200Schema,
) as unknown as ToZod<DeleteProductsAttributesValuesIdMutationResponseType>