/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from '@kubb/plugin-zod/utils'
import { z } from 'zod'
import type {
  DeleteProductsBrandsId200Type,
  DeleteProductsBrandsId401Type,
  DeleteProductsBrandsId404Type,
  DeleteProductsBrandsIdMutationResponseType,
  DeleteProductsBrandsIdPathParamsType,
} from '../../types/Produtos (Marcas)Types/DeleteProductsBrandsIdType.ts'

export const deleteProductsBrandsIdPathParamsSchema = z.object({
  id: z.string(),
}) as unknown as ToZod<DeleteProductsBrandsIdPathParamsType>

/**
 * @description Marca deletada com sucesso.
 */
export const deleteProductsBrandsId200Schema = z
  .enum(['null'])
  .describe('Marca deletada com sucesso.')
  .nullable() as unknown as ToZod<DeleteProductsBrandsId200Type>

/**
 * @description Usuário não autenticado.
 */
export const deleteProductsBrandsId401Schema = z
  .object({
    message: z.string(),
  })
  .describe(
    'Usuário não autenticado.'
  ) as unknown as ToZod<DeleteProductsBrandsId401Type>

/**
 * @description Marca não encontrado.
 */
export const deleteProductsBrandsId404Schema = z
  .object({
    message: z.string(),
  })
  .describe(
    'Marca não encontrado.'
  ) as unknown as ToZod<DeleteProductsBrandsId404Type>

export const deleteProductsBrandsIdMutationResponseSchema = z.lazy(
  () => deleteProductsBrandsId200Schema
) as unknown as ToZod<DeleteProductsBrandsIdMutationResponseType>
