/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from '@kubb/plugin-zod/utils'
import type {
  DeleteProductsAttributesNamesIdPathParamsType,
  DeleteProductsAttributesNamesId200Type,
  DeleteProductsAttributesNamesId401Type,
  DeleteProductsAttributesNamesId404Type,
  DeleteProductsAttributesNamesIdMutationResponseType,
} from '../../types/products/DeleteProductsAttributesNamesIdType'
import { z } from 'zod'

export const deleteProductsAttributesNamesIdPathParamsSchema = z.object({
  id: z.string(),
}) as unknown as ToZod<DeleteProductsAttributesNamesIdPathParamsType>

/**
 * @description Nome de atributo do produto deletado com sucesso.
 */
export const deleteProductsAttributesNamesId200Schema = z
  .enum(['null'])
  .describe('Nome de atributo do produto deletado com sucesso.')
  .nullable() as unknown as ToZod<DeleteProductsAttributesNamesId200Type>

/**
 * @description Usuário não autenticado.
 */
export const deleteProductsAttributesNamesId401Schema = z
  .object({
    message: z.string(),
  })
  .describe('Usuário não autenticado.') as unknown as ToZod<DeleteProductsAttributesNamesId401Type>

/**
 * @description Nome de atributo do produto não encontrado.
 */
export const deleteProductsAttributesNamesId404Schema = z
  .object({
    message: z.string(),
  })
  .describe('Nome de atributo do produto não encontrado.') as unknown as ToZod<DeleteProductsAttributesNamesId404Type>

export const deleteProductsAttributesNamesIdMutationResponseSchema = z.lazy(
  () => deleteProductsAttributesNamesId200Schema,
) as unknown as ToZod<DeleteProductsAttributesNamesIdMutationResponseType>