/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from '@kubb/plugin-zod/utils'
import type {
  GetProductsVariationsIdPathParamsType,
  GetProductsVariationsId200Type,
  GetProductsVariationsId401Type,
  GetProductsVariationsId404Type,
  GetProductsVariationsIdQueryResponseType,
} from '../../types/Produtos (Varia\u00E7\u00F5es)Types/GetProductsVariationsIdType'
import { z } from 'zod'

export const getProductsVariationsIdPathParamsSchema = z.object({
  id: z.string(),
}) as unknown as ToZod<GetProductsVariationsIdPathParamsType>

/**
 * @description Variação de produto obtido com sucesso.
 */
export const getProductsVariationsId200Schema = z
  .object({
    product_id: z.string(),
    id: z.string(),
    barcode: z.string().nullable(),
    name: z.string().min(1),
    average_cost: z.number(),
    cost_price: z.number(),
    selling_price: z.number(),
    product_storage_location: z.string().nullable(),
    current_stock: z.number(),
    minimum_stock_level: z.number(),
    products_in_review: z.number(),
    track_inventory: z.boolean().optional(),
    is_available: z.boolean().optional(),
    product_attribute_names: z.array(
      z.object({
        id: z.string(),
        name: z.string(),
        product_attribute_values: z.array(
          z.object({
            id: z.string(),
            value: z.string(),
          }),
        ),
      }),
    ),
  })
  .describe('Variação de produto obtido com sucesso.') as unknown as ToZod<GetProductsVariationsId200Type>

/**
 * @description Usuário não autenticado.
 */
export const getProductsVariationsId401Schema = z
  .object({
    message: z.string(),
  })
  .describe('Usuário não autenticado.') as unknown as ToZod<GetProductsVariationsId401Type>

/**
 * @description Variação de produto não encontrado.
 */
export const getProductsVariationsId404Schema = z
  .object({
    message: z.string(),
  })
  .describe('Variação de produto não encontrado.') as unknown as ToZod<GetProductsVariationsId404Type>

export const getProductsVariationsIdQueryResponseSchema = z.lazy(
  () => getProductsVariationsId200Schema,
) as unknown as ToZod<GetProductsVariationsIdQueryResponseType>