/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from '@kubb/plugin-zod/utils'
import type {
  GetProductsCategories200Type,
  GetProductsCategories401Type,
  GetProductsCategoriesQueryResponseType,
} from '../../types/Produtos (Categorias)Types/GetProductsCategoriesType.ts'
import { z } from 'zod'

/**
 * @description Categorias de produtos obtidas com sucesso.
 */
export const getProductsCategories200Schema = z
  .array(
    z.object({
      id: z.string(),
      name: z.string(),
    }),
  )
  .describe('Categorias de produtos obtidas com sucesso.') as unknown as ToZod<GetProductsCategories200Type>

/**
 * @description Usuário não autenticado.
 */
export const getProductsCategories401Schema = z
  .object({
    message: z.string(),
  })
  .describe('Usuário não autenticado.') as unknown as ToZod<GetProductsCategories401Type>

export const getProductsCategoriesQueryResponseSchema = z.lazy(() => getProductsCategories200Schema) as unknown as ToZod<GetProductsCategoriesQueryResponseType>