/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from '@kubb/plugin-zod/utils'
import type {
  GetProductsAttributesNamesQueryParamsType,
  GetProductsAttributesNames200Type,
  GetProductsAttributesNames401Type,
  GetProductsAttributesNamesQueryResponseType,
} from '../../types/products/GetProductsAttributesNamesType'
import { z } from 'zod'

export const getProductsAttributesNamesQueryParamsSchema = z
  .object({
    perPage: z.number().default(10),
    pageIndex: z.number().default(0),
    orderBy: z.enum(['desc', 'asc']).default('desc'),
    attributeName: z.string().optional(),
  })
  .optional() as unknown as ToZod<GetProductsAttributesNamesQueryParamsType>

/**
 * @description Nomes dos atributos dos produtos obtidos com sucesso.
 */
export const getProductsAttributesNames200Schema = z
  .object({
    totalCount: z.number(),
    pageCount: z.number(),
    productAttributeNames: z.array(
      z.object({
        id: z.string(),
        name: z.string(),
      }),
    ),
  })
  .describe('Nomes dos atributos dos produtos obtidos com sucesso.') as unknown as ToZod<GetProductsAttributesNames200Type>

/**
 * @description Usuário não autenticado.
 */
export const getProductsAttributesNames401Schema = z
  .object({
    message: z.string(),
  })
  .describe('Usuário não autenticado.') as unknown as ToZod<GetProductsAttributesNames401Type>

export const getProductsAttributesNamesQueryResponseSchema = z.lazy(
  () => getProductsAttributesNames200Schema,
) as unknown as ToZod<GetProductsAttributesNamesQueryResponseType>