/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from '@kubb/plugin-zod/utils'
import type {
  GetProductsMeasurementUnits200Type,
  GetProductsMeasurementUnits401Type,
  GetProductsMeasurementUnitsQueryResponseType,
} from '../../types/Produtos (Unidades de Medida)Types/GetProductsMeasurementUnitsType.ts'
import { z } from 'zod'

/**
 * @description Unidades de medida de produtos obtidas com sucesso.
 */
export const getProductsMeasurementUnits200Schema = z
  .array(
    z.object({
      id: z.string(),
      name: z.string(),
      acronym: z.string(),
    })
  )
  .describe(
    'Unidades de medida de produtos obtidas com sucesso.'
  ) as unknown as ToZod<GetProductsMeasurementUnits200Type>

/**
 * @description Usuário não autenticado.
 */
export const getProductsMeasurementUnits401Schema = z
  .object({
    message: z.string(),
  })
  .describe(
    'Usuário não autenticado.'
  ) as unknown as ToZod<GetProductsMeasurementUnits401Type>

export const getProductsMeasurementUnitsQueryResponseSchema = z.lazy(
  () => getProductsMeasurementUnits200Schema
) as unknown as ToZod<GetProductsMeasurementUnitsQueryResponseType>
