/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from '@kubb/plugin-zod/utils'
import type {
  PostProductsUpload201Type,
  PostProductsUpload400Type,
  PostProductsUpload401Type,
  PostProductsUploadMutationRequestType,
  PostProductsUploadMutationResponseType,
} from '../../types/ProdutosTypes/PostProductsUploadType.ts'
import { z } from 'zod'

/**
 * @description Produto cadastrado com sucesso.
 */
export const postProductsUpload201Schema = z
  .object({
    fileUrl: z.string(),
  })
  .describe(
    'Produto cadastrado com sucesso.'
  ) as unknown as ToZod<PostProductsUpload201Type>

/**
 * @description Imagem inválida.
 */
export const postProductsUpload400Schema = z
  .object({
    message: z.string(),
  })
  .describe('Imagem inválida.') as unknown as ToZod<PostProductsUpload400Type>

/**
 * @description Usuário não autenticado.
 */
export const postProductsUpload401Schema = z
  .object({
    message: z.string(),
  })
  .describe(
    'Usuário não autenticado.'
  ) as unknown as ToZod<PostProductsUpload401Type>

export const postProductsUploadMutationRequestSchema = z.object({
  file: z.unknown().optional(),
}) as unknown as ToZod<PostProductsUploadMutationRequestType>

export const postProductsUploadMutationResponseSchema = z.lazy(
  () => postProductsUpload201Schema
) as unknown as ToZod<PostProductsUploadMutationResponseType>
