/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from '@kubb/plugin-zod/utils'
import type {
  PostProductsCategories201Type,
  PostProductsCategories401Type,
  PostProductsCategories409Type,
  PostProductsCategoriesMutationRequestType,
  PostProductsCategoriesMutationResponseType,
} from '../../types/Produtos (Categorias)Types/PostProductsCategoriesType.ts'
import { z } from 'zod'

/**
 * @description Categoria cadastrado com sucesso.
 */
export const postProductsCategories201Schema = z
  .enum(['null'])
  .describe('Categoria cadastrado com sucesso.')
  .nullable() as unknown as ToZod<PostProductsCategories201Type>

/**
 * @description Usuário não autenticado.
 */
export const postProductsCategories401Schema = z
  .object({
    message: z.string(),
  })
  .describe(
    'Usuário não autenticado.'
  ) as unknown as ToZod<PostProductsCategories401Type>

/**
 * @description Categoria já cadastrado.
 */
export const postProductsCategories409Schema = z
  .object({
    message: z.string(),
  })
  .describe(
    'Categoria já cadastrado.'
  ) as unknown as ToZod<PostProductsCategories409Type>

export const postProductsCategoriesMutationRequestSchema = z.object({
  name: z.string(),
}) as unknown as ToZod<PostProductsCategoriesMutationRequestType>

export const postProductsCategoriesMutationResponseSchema = z.lazy(
  () => postProductsCategories201Schema
) as unknown as ToZod<PostProductsCategoriesMutationResponseType>
