/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from '@kubb/plugin-zod/utils'
import type {
  PostProductsAttributesValues201Type,
  PostProductsAttributesValues401Type,
  PostProductsAttributesValues409Type,
  PostProductsAttributesValuesMutationRequestType,
  PostProductsAttributesValuesMutationResponseType,
} from '../../types/products/PostProductsAttributesValuesType'
import { z } from 'zod'

/**
 * @description Valor do atributo do produto cadastrado com sucesso.
 */
export const postProductsAttributesValues201Schema = z
  .enum(['null'])
  .describe('Valor do atributo do produto cadastrado com sucesso.')
  .nullable() as unknown as ToZod<PostProductsAttributesValues201Type>

/**
 * @description Usuário não autenticado.
 */
export const postProductsAttributesValues401Schema = z
  .object({
    message: z.string(),
  })
  .describe('Usuário não autenticado.') as unknown as ToZod<PostProductsAttributesValues401Type>

/**
 * @description Valor do atributo do produto já cadastrado.
 */
export const postProductsAttributesValues409Schema = z
  .object({
    message: z.string(),
  })
  .describe('Valor do atributo do produto já cadastrado.') as unknown as ToZod<PostProductsAttributesValues409Type>

export const postProductsAttributesValuesMutationRequestSchema = z.object({
  product_attribute_name_id: z.string(),
  value: z.string(),
}) as unknown as ToZod<PostProductsAttributesValuesMutationRequestType>

export const postProductsAttributesValuesMutationResponseSchema = z.lazy(
  () => postProductsAttributesValues201Schema,
) as unknown as ToZod<PostProductsAttributesValuesMutationResponseType>