/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from '@kubb/plugin-zod/utils'
import type {
  PostProductsAttributesNames201Type,
  PostProductsAttributesNames401Type,
  PostProductsAttributesNames409Type,
  PostProductsAttributesNamesMutationRequestType,
  PostProductsAttributesNamesMutationResponseType,
} from '../../types/products/PostProductsAttributesNamesType'
import { z } from 'zod'

/**
 * @description Nome do atributo do produto cadastrado com sucesso.
 */
export const postProductsAttributesNames201Schema = z
  .enum(['null'])
  .describe('Nome do atributo do produto cadastrado com sucesso.')
  .nullable() as unknown as ToZod<PostProductsAttributesNames201Type>

/**
 * @description Usuário não autenticado.
 */
export const postProductsAttributesNames401Schema = z
  .object({
    message: z.string(),
  })
  .describe('Usuário não autenticado.') as unknown as ToZod<PostProductsAttributesNames401Type>

/**
 * @description Nome do atributo do produto já cadastrado.
 */
export const postProductsAttributesNames409Schema = z
  .object({
    message: z.string(),
  })
  .describe('Nome do atributo do produto já cadastrado.') as unknown as ToZod<PostProductsAttributesNames409Type>

export const postProductsAttributesNamesMutationRequestSchema = z.object({
  name: z.string(),
}) as unknown as ToZod<PostProductsAttributesNamesMutationRequestType>

export const postProductsAttributesNamesMutationResponseSchema = z.lazy(
  () => postProductsAttributesNames201Schema,
) as unknown as ToZod<PostProductsAttributesNamesMutationResponseType>