/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from '@kubb/plugin-zod/utils'
import type {
  PutProductsAttributesValuesIdPathParamsType,
  PutProductsAttributesValuesId200Type,
  PutProductsAttributesValuesId401Type,
  PutProductsAttributesValuesId404Type,
  PutProductsAttributesValuesIdMutationRequestType,
  PutProductsAttributesValuesIdMutationResponseType,
} from '../../types/Produtos (Atributos)Types/PutProductsAttributesValuesIdType'
import { z } from 'zod'

export const putProductsAttributesValuesIdPathParamsSchema = z.object({
  id: z.string(),
}) as unknown as ToZod<PutProductsAttributesValuesIdPathParamsType>

/**
 * @description Valor de atributo do produto atualizado com sucesso.
 */
export const putProductsAttributesValuesId200Schema = z
  .enum(['null'])
  .describe('Valor de atributo do produto atualizado com sucesso.')
  .nullable() as unknown as ToZod<PutProductsAttributesValuesId200Type>

/**
 * @description Usuário não autenticado.
 */
export const putProductsAttributesValuesId401Schema = z
  .object({
    message: z.string(),
  })
  .describe('Usuário não autenticado.') as unknown as ToZod<PutProductsAttributesValuesId401Type>

/**
 * @description Valor de atributo do produto não encontrado.
 */
export const putProductsAttributesValuesId404Schema = z
  .object({
    message: z.string(),
  })
  .describe('Valor de atributo do produto não encontrado.') as unknown as ToZod<PutProductsAttributesValuesId404Type>

export const putProductsAttributesValuesIdMutationRequestSchema = z.object({
  value: z.string(),
}) as unknown as ToZod<PutProductsAttributesValuesIdMutationRequestType>

export const putProductsAttributesValuesIdMutationResponseSchema = z.lazy(
  () => putProductsAttributesValuesId200Schema,
) as unknown as ToZod<PutProductsAttributesValuesIdMutationResponseType>