/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from '@kubb/plugin-zod/utils'
import { z } from 'zod'
import type {
  PutProductsAttributesNamesId200Type,
  PutProductsAttributesNamesId401Type,
  PutProductsAttributesNamesId404Type,
  PutProductsAttributesNamesIdMutationRequestType,
  PutProductsAttributesNamesIdMutationResponseType,
  PutProductsAttributesNamesIdPathParamsType,
} from '../../types/Produtos (Atributos)Types/PutProductsAttributesNamesIdType'

export const putProductsAttributesNamesIdPathParamsSchema = z.object({
  id: z.string(),
}) as unknown as ToZod<PutProductsAttributesNamesIdPathParamsType>

/**
 * @description Nome de atributo do produto atualizado com sucesso.
 */
export const putProductsAttributesNamesId200Schema = z
  .enum(['null'])
  .describe('Nome de atributo do produto atualizado com sucesso.')
  .nullable() as unknown as ToZod<PutProductsAttributesNamesId200Type>

/**
 * @description Usuário não autenticado.
 */
export const putProductsAttributesNamesId401Schema = z
  .object({
    message: z.string(),
  })
  .describe(
    'Usuário não autenticado.'
  ) as unknown as ToZod<PutProductsAttributesNamesId401Type>

/**
 * @description Nome de atributo do produto não encontrado.
 */
export const putProductsAttributesNamesId404Schema = z
  .object({
    message: z.string(),
  })
  .describe(
    'Nome de atributo do produto não encontrado.'
  ) as unknown as ToZod<PutProductsAttributesNamesId404Type>

export const putProductsAttributesNamesIdMutationRequestSchema = z.object({
  name: z.string(),
}) as unknown as ToZod<PutProductsAttributesNamesIdMutationRequestType>

export const putProductsAttributesNamesIdMutationResponseSchema = z.lazy(
  () => putProductsAttributesNamesId200Schema
) as unknown as ToZod<PutProductsAttributesNamesIdMutationResponseType>
