/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from '@kubb/plugin-zod/utils'
import type {
  PutSuppliersIdPathParamsType,
  PutSuppliersId200Type,
  PutSuppliersId401Type,
  PutSuppliersId404Type,
  PutSuppliersIdMutationRequestType,
  PutSuppliersIdMutationResponseType,
} from '../../types/FornecedoresTypes/PutSuppliersIdType'
import { z } from 'zod'

export const putSuppliersIdPathParamsSchema = z.object({
  id: z.string(),
}) as unknown as ToZod<PutSuppliersIdPathParamsType>

/**
 * @description Fornecedor atualizado com sucesso.
 */
export const putSuppliersId200Schema = z.enum(['null']).describe('Fornecedor atualizado com sucesso.').nullable() as unknown as ToZod<PutSuppliersId200Type>

/**
 * @description Usuário não autenticado.
 */
export const putSuppliersId401Schema = z
  .object({
    message: z.string(),
  })
  .describe('Usuário não autenticado.') as unknown as ToZod<PutSuppliersId401Type>

/**
 * @description Fornecedor não encontrado.
 */
export const putSuppliersId404Schema = z
  .object({
    message: z.string(),
  })
  .describe('Fornecedor não encontrado.') as unknown as ToZod<PutSuppliersId404Type>

export const putSuppliersIdMutationRequestSchema = z.object({
  name: z.string().min(1),
  phone: z.string().min(1),
  phone_2: z.string().optional(),
  document_type: z.enum(['PERSON', 'COMPANY']),
  document: z.string().min(1),
  document_2: z.string().optional(),
  email: z.string().email().min(1),
  state_registration: z.string().optional(),
  tax_free: z.boolean().optional(),
  address_id: z
    .string()
    .regex(/^[cC][^\s-]{8,}$/)
    .min(1),
  recipient_name: z.string().min(1),
  recipient_phone: z.string().min(1),
  cep: z.string().min(1),
  street: z.string().min(1),
  number: z.string().min(1),
  complement: z.string().optional(),
  neighborhood: z.string().min(1),
  city: z.string().min(1),
  state: z.string().min(1),
}) as unknown as ToZod<PutSuppliersIdMutationRequestType>

export const putSuppliersIdMutationResponseSchema = z.lazy(() => putSuppliersId200Schema) as unknown as ToZod<PutSuppliersIdMutationResponseType>