/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const getProductsQueryParamsOrderByEnum = {
  desc: 'desc',
  asc: 'asc',
} as const

export type GetProductsQueryParamsOrderByEnumType = (typeof getProductsQueryParamsOrderByEnum)[keyof typeof getProductsQueryParamsOrderByEnum]

export type GetProductsQueryParamsType = {
  /**
   * @default 10
   * @type number | undefined
   */
  perPage?: number
  /**
   * @default 0
   * @type number | undefined
   */
  pageIndex?: number
  /**
   * @default "desc"
   * @type string | undefined
   */
  orderBy?: GetProductsQueryParamsOrderByEnumType
  /**
   * @type string | undefined
   */
  productName?: string
}

/**
 * @description Produtos obtidos com sucesso.
 */
export type GetProducts200Type = {
  /**
   * @type number
   */
  totalCount: number
  /**
   * @type number
   */
  pageCount: number
  /**
   * @type array
   */
  products: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    name: string
    /**
     * @type number
     */
    ncm: number | null
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetProducts401Type = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsQueryResponseType = GetProducts200Type

export type GetProductsTypeQuery = {
  Response: GetProducts200Type
  QueryParams: GetProductsQueryParamsType
  Errors: GetProducts401Type
}