/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const postProductsBrands201Enum = {
  null: 'null',
} as const

export type PostProductsBrands201EnumType = (typeof postProductsBrands201Enum)[keyof typeof postProductsBrands201Enum]

/**
 * @description Marca cadastrado com sucesso.
 */
export type PostProductsBrands201Type = PostProductsBrands201EnumType | null

/**
 * @description Usuário não autenticado.
 */
export type PostProductsBrands401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Marca já cadastrado.
 */
export type PostProductsBrands409Type = {
  /**
   * @type string
   */
  message: string
}

export type PostProductsBrandsMutationRequestType = {
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  reference_code: string
}

export type PostProductsBrandsMutationResponseType = PostProductsBrands201Type

export type PostProductsBrandsTypeMutation = {
  Response: PostProductsBrands201Type
  Request: PostProductsBrandsMutationRequestType
  Errors: PostProductsBrands401Type | PostProductsBrands409Type
}