/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteProductsAttributesValuesIdPathParamsType = {
  /**
   * @type string
   */
  id: string
}

export const deleteProductsAttributesValuesId200Enum = {
  null: 'null',
} as const

export type DeleteProductsAttributesValuesId200EnumType =
  (typeof deleteProductsAttributesValuesId200Enum)[keyof typeof deleteProductsAttributesValuesId200Enum]

/**
 * @description Valor de atributo do produto deletado com sucesso.
 */
export type DeleteProductsAttributesValuesId200Type =
  DeleteProductsAttributesValuesId200EnumType | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteProductsAttributesValuesId401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Valor de atributo do produto não encontrado.
 */
export type DeleteProductsAttributesValuesId404Type = {
  /**
   * @type string
   */
  message: string
}

export type DeleteProductsAttributesValuesIdMutationResponseType =
  DeleteProductsAttributesValuesId200Type

export type DeleteProductsAttributesValuesIdTypeMutation = {
  Response: DeleteProductsAttributesValuesId200Type
  PathParams: DeleteProductsAttributesValuesIdPathParamsType
  Errors:
    | DeleteProductsAttributesValuesId401Type
    | DeleteProductsAttributesValuesId404Type
}
