/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetProductsAttributesValuesIdPathParamsType = {
  /**
   * @type string
   */
  id: string
}

/**
 * @description Valor de atributo do produto obtido com sucesso.
 */
export type GetProductsAttributesValuesId200Type = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  value: string
  /**
   * @type string, date-time
   */
  created_at: string
}

/**
 * @description Usuário não autenticado.
 */
export type GetProductsAttributesValuesId401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Valor de atributo do produto não encontrado.
 */
export type GetProductsAttributesValuesId404Type = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsAttributesValuesIdQueryResponseType =
  GetProductsAttributesValuesId200Type

export type GetProductsAttributesValuesIdTypeQuery = {
  Response: GetProductsAttributesValuesId200Type
  PathParams: GetProductsAttributesValuesIdPathParamsType
  Errors:
    | GetProductsAttributesValuesId401Type
    | GetProductsAttributesValuesId404Type
}
