/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const getProductsAttributesNamesQueryParamsOrderByEnum = {
  desc: 'desc',
  asc: 'asc',
} as const

export type GetProductsAttributesNamesQueryParamsOrderByEnumType =
  (typeof getProductsAttributesNamesQueryParamsOrderByEnum)[keyof typeof getProductsAttributesNamesQueryParamsOrderByEnum]

export type GetProductsAttributesNamesQueryParamsType = {
  /**
   * @default 10
   * @type number | undefined
   */
  perPage?: number
  /**
   * @default 0
   * @type number | undefined
   */
  pageIndex?: number
  /**
   * @default "desc"
   * @type string | undefined
   */
  orderBy?: GetProductsAttributesNamesQueryParamsOrderByEnumType
  /**
   * @type string | undefined
   */
  attributeName?: string
}

/**
 * @description Nomes dos atributos dos produtos obtidos com sucesso.
 */
export type GetProductsAttributesNames200Type = {
  /**
   * @type number
   */
  totalCount: number
  /**
   * @type number
   */
  pageCount: number
  /**
   * @type array
   */
  productAttributeNames: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    name: string
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetProductsAttributesNames401Type = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsAttributesNamesQueryResponseType =
  GetProductsAttributesNames200Type

export type GetProductsAttributesNamesTypeQuery = {
  Response: GetProductsAttributesNames200Type
  QueryParams: GetProductsAttributesNamesQueryParamsType
  Errors: GetProductsAttributesNames401Type
}
