/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const postProductsAttributesValues201Enum = {
  null: 'null',
} as const

export type PostProductsAttributesValues201EnumType = (typeof postProductsAttributesValues201Enum)[keyof typeof postProductsAttributesValues201Enum]

/**
 * @description Valor do atributo do produto cadastrado com sucesso.
 */
export type PostProductsAttributesValues201Type = PostProductsAttributesValues201EnumType | null

/**
 * @description Usuário não autenticado.
 */
export type PostProductsAttributesValues401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Valor do atributo do produto já cadastrado.
 */
export type PostProductsAttributesValues409Type = {
  /**
   * @type string
   */
  message: string
}

export type PostProductsAttributesValuesMutationRequestType = {
  /**
   * @type string
   */
  product_attribute_name_id: string
  /**
   * @type string
   */
  value: string
}

export type PostProductsAttributesValuesMutationResponseType = PostProductsAttributesValues201Type

export type PostProductsAttributesValuesTypeMutation = {
  Response: PostProductsAttributesValues201Type
  Request: PostProductsAttributesValuesMutationRequestType
  Errors: PostProductsAttributesValues401Type | PostProductsAttributesValues409Type
}