/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PutProductsAttributesValuesIdPathParamsType = {
  /**
   * @type string
   */
  id: string
}

export const putProductsAttributesValuesId200Enum = {
  null: 'null',
} as const

export type PutProductsAttributesValuesId200EnumType =
  (typeof putProductsAttributesValuesId200Enum)[keyof typeof putProductsAttributesValuesId200Enum]

/**
 * @description Valor de atributo do produto atualizado com sucesso.
 */
export type PutProductsAttributesValuesId200Type =
  PutProductsAttributesValuesId200EnumType | null

/**
 * @description Usuário não autenticado.
 */
export type PutProductsAttributesValuesId401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Valor de atributo do produto não encontrado.
 */
export type PutProductsAttributesValuesId404Type = {
  /**
   * @type string
   */
  message: string
}

export type PutProductsAttributesValuesIdMutationRequestType = {
  /**
   * @type string
   */
  value: string
}

export type PutProductsAttributesValuesIdMutationResponseType =
  PutProductsAttributesValuesId200Type

export type PutProductsAttributesValuesIdTypeMutation = {
  Response: PutProductsAttributesValuesId200Type
  Request: PutProductsAttributesValuesIdMutationRequestType
  PathParams: PutProductsAttributesValuesIdPathParamsType
  Errors:
    | PutProductsAttributesValuesId401Type
    | PutProductsAttributesValuesId404Type
}
