/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  DeleteProductsCategoriesIdMutationResponse,
  DeleteProductsCategoriesIdPathParams,
  DeleteProductsCategoriesId401,
  DeleteProductsCategoriesId404,
} from './models.ts'

function getDeleteProductsCategoriesIdUrl(id: DeleteProductsCategoriesIdPathParams['id']) {
  return `/products/categories/${id}` as const
}

/**
 * @description Esta rota permite a remoção de uma categoria de produto específica do sistema. A operação é irreversível e requer o ID da categoria como parâmetro. É importante verificar se a categoria não está sendo utilizada por nenhum produto antes da remoção para evitar inconsistências no sistema. A remoção de categorias deve ser realizada com cautela, pois pode impactar a organização e classificação dos produtos existentes.
 * @summary Remove uma categoria de produto específica.
 * {@link /products/categories/:id}
 */
export async function deleteProductsCategoriesId(
  id: DeleteProductsCategoriesIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    DeleteProductsCategoriesIdMutationResponse,
    ResponseErrorConfig<DeleteProductsCategoriesId401 | DeleteProductsCategoriesId404>,
    unknown
  >({ method: 'DELETE', url: getDeleteProductsCategoriesIdUrl(id).toString(), ...requestConfig })
  return res.data
}