/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type { GetEmployeesIdQueryResponse, GetEmployeesIdPathParams, GetEmployeesId401, GetEmployeesId404 } from './models.ts'

function getGetEmployeesIdUrl(id: GetEmployeesIdPathParams['id']) {
  return `/employees/${id}` as const
}

/**
 * @description Requer autenticação via token JWT para garantir acesso seguro. Retorna informações detalhadas de um colaborador específico, incluindo dados pessoais, profissionais, documentos, informações de contato e dados bancários. O ID do colaborador deve ser fornecido como parâmetro na URL. A rota valida a existência do colaborador antes de retornar os dados e garante que apenas usuários autorizados tenham acesso às informações.
 * @summary Retorna informações um colaborador específico.
 * {@link /employees/:id}
 */
export async function getEmployeesId(id: GetEmployeesIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetEmployeesIdQueryResponse, ResponseErrorConfig<GetEmployeesId401 | GetEmployeesId404>, unknown>({
    method: 'GET',
    url: getGetEmployeesIdUrl(id).toString(),
    ...requestConfig,
  })
  return res.data
}