/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type { GetEmployeesQueryResponse, GetEmployeesQueryParams, GetEmployees401, GetEmployees404 } from './models.ts'

function getGetEmployeesUrl() {
  return `/employees` as const
}

/**
 * @description Requer autenticação via token JWT para garantir acesso seguro. Retorna uma lista paginada de colaboradores cadastrados no sistema, com opções de filtro por nome, cargo e departamento. Os resultados podem ser ordenados por diferentes campos e a quantidade de itens por página pode ser personalizada. Inclui informações básicas como nome, cargo, departamento e status do colaborador. Metadados de paginação são incluídos na resposta para facilitar a navegação.
 * @summary Retorna uma lista de colaboradores cadastrados.
 * {@link /employees}
 */
export async function getEmployees(params?: GetEmployeesQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetEmployeesQueryResponse, ResponseErrorConfig<GetEmployees401 | GetEmployees404>, unknown>({
    method: 'GET',
    url: getGetEmployeesUrl().toString(),
    params,
    ...requestConfig,
  })
  return res.data
}