/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type { GetProductsIdQueryResponseType, GetProductsIdPathParamsType, GetProductsId401Type, GetProductsId404Type } from './types/GetProductsIdType.ts'

function getGetProductsIdUrl(id: GetProductsIdPathParamsType['id']) {
  return `/products/${id}` as const
}

/**
 * @description Esta rota requer autenticação através de um token JWT válido. Retorna informações detalhadas de um produto específico com base no ID fornecido nos parâmetros da URL. Os dados retornados incluem todas as informações cadastrais do produto, como nome, descrição, preço, categoria, data de cadastro e última atualização. Caso o produto não seja encontrado, será retornado um erro apropriado.
 * @summary Retorna as informações de um produto específico.
 * {@link /products/:id}
 */
export async function getProductsId(id: GetProductsIdPathParamsType['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetProductsIdQueryResponseType, ResponseErrorConfig<GetProductsId401Type | GetProductsId404Type>, unknown>({
    method: 'GET',
    url: getGetProductsIdUrl(id).toString(),
    ...requestConfig,
  })
  return res.data
}