/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type { GetSuppliersIdQueryResponse, GetSuppliersIdPathParams, GetSuppliersId401, GetSuppliersId404 } from './models.ts'

function getGetSuppliersIdUrl(id: GetSuppliersIdPathParams['id']) {
  return `/suppliers/${id}` as const
}

/**
 * @summary Retorna as informações de um fornecedor específico.
 * {@link /suppliers/:id}
 */
export async function getSuppliersId(id: GetSuppliersIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetSuppliersIdQueryResponse, ResponseErrorConfig<GetSuppliersId401 | GetSuppliersId404>, unknown>({
    method: 'GET',
    url: getGetSuppliersIdUrl(id).toString(),
    ...requestConfig,
  })
  return res.data
}