/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type FileUpload = {
  /**
   * @description Arquivo de imagem a ser enviado
   * @type string | undefined, binary
   */
  file?: Blob
}

export const postUsers201Enum = {
  null: 'null',
} as const

export type PostUsers201Enum = (typeof postUsers201Enum)[keyof typeof postUsers201Enum]

/**
 * @description Usuário cadastrado com sucesso.
 */
export type PostUsers201 = PostUsers201Enum | null

/**
 * @description Este email já está cadastrado em nossa base de dados.
 */
export type PostUsers409 = {
  /**
   * @type string
   */
  message: string
}

export type PostUsersMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @minLength 1
   * @type string, email
   */
  email: string
  /**
   * @minLength 6
   * @type string
   */
  password: string
}

export type PostUsersMutationResponse = PostUsers201

export type PostUsersMutation = {
  Response: PostUsers201
  Request: PostUsersMutationRequest
  Errors: PostUsers409
}

/**
 * @description Usuário autenticado com sucesso.
 */
export type PostSessionsPassword200 = {
  /**
   * @type string
   */
  access_token: string
  /**
   * @type string
   */
  refresh_token: string
}

/**
 * @description E-mail ou senha incorretos.
 */
export type PostSessionsPassword400 = {
  /**
   * @type string
   */
  message: string
}

export type PostSessionsPasswordMutationRequest = {
  /**
   * @minLength 1
   * @type string, email
   */
  email: string
  /**
   * @minLength 6
   * @type string
   */
  password: string
}

export type PostSessionsPasswordMutationResponse = PostSessionsPassword200

export type PostSessionsPasswordMutation = {
  Response: PostSessionsPassword200
  Request: PostSessionsPasswordMutationRequest
  Errors: PostSessionsPassword400
}

export const getUsersProfile200RoleEnum = {
  MEMBER: 'MEMBER',
  ADMIN: 'ADMIN',
} as const

export type GetUsersProfile200RoleEnum = (typeof getUsersProfile200RoleEnum)[keyof typeof getUsersProfile200RoleEnum]

/**
 * @description Informações do perfil do usuário obtidas com sucesso.
 */
export type GetUsersProfile200 = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  name: string
  /**
   * @type string, email
   */
  email: string
  /**
   * @type string
   */
  role: GetUsersProfile200RoleEnum
}

/**
 * @description Usuário não autenticado.
 */
export type GetUsersProfile401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Usuário não encontrado.
 */
export type GetUsersProfile404 = {
  /**
   * @type string
   */
  message: string
}

export type GetUsersProfileQueryResponse = GetUsersProfile200

export type GetUsersProfileQuery = {
  Response: GetUsersProfile200
  Errors: GetUsersProfile401 | GetUsersProfile404
}

export const postCustomers201Enum = {
  null: 'null',
} as const

export type PostCustomers201Enum = (typeof postCustomers201Enum)[keyof typeof postCustomers201Enum]

/**
 * @description Cliente cadastrado com sucesso.
 */
export type PostCustomers201 = PostCustomers201Enum | null

/**
 * @description Usuário não autenticado.
 */
export type PostCustomers401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Cliente já cadastrado.
 */
export type PostCustomers409 = {
  /**
   * @type string
   */
  message: string
}

export const postCustomersMutationRequestDocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type PostCustomersMutationRequestDocumentTypeEnum =
  (typeof postCustomersMutationRequestDocumentTypeEnum)[keyof typeof postCustomersMutationRequestDocumentTypeEnum]

export const postCustomersMutationRequestGenderEnum = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const

export type PostCustomersMutationRequestGenderEnum = (typeof postCustomersMutationRequestGenderEnum)[keyof typeof postCustomersMutationRequestGenderEnum]

export type PostCustomersMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @minLength 1
   * @type string
   */
  phone: string
  /**
   * @type string | undefined
   */
  phone_2?: string
  /**
   * @type string
   */
  document_type: PostCustomersMutationRequestDocumentTypeEnum
  /**
   * @minLength 1
   * @type string
   */
  document: string
  /**
   * @type string | undefined
   */
  document_2?: string
  /**
   * @minLength 1
   * @type string, email
   */
  email: string
  /**
   * @type string | undefined
   */
  state_registration?: string
  /**
   * @type boolean | undefined
   */
  tax_free?: boolean
  /**
   * @type string | undefined
   */
  gender?: PostCustomersMutationRequestGenderEnum
  /**
   * @type string | undefined, date-time
   */
  birth_date?: string
  /**
   * @type boolean | undefined
   */
  problematic?: boolean
  /**
   * @minLength 1
   * @type string
   */
  recipient_name: string
  /**
   * @minLength 1
   * @type string
   */
  recipient_phone: string
  /**
   * @minLength 1
   * @type string
   */
  cep: string
  /**
   * @minLength 1
   * @type string
   */
  street: string
  /**
   * @minLength 1
   * @type string
   */
  number: string
  /**
   * @type string | undefined
   */
  complement?: string
  /**
   * @minLength 1
   * @type string
   */
  neighborhood: string
  /**
   * @minLength 1
   * @type string
   */
  city: string
  /**
   * @minLength 1
   * @type string
   */
  state: string
}

export type PostCustomersMutationResponse = PostCustomers201

export type PostCustomersMutation = {
  Response: PostCustomers201
  Request: PostCustomersMutationRequest
  Errors: PostCustomers401 | PostCustomers409
}

export const getCustomersQueryParamsOrderByEnum = {
  desc: 'desc',
  asc: 'asc',
} as const

export type GetCustomersQueryParamsOrderByEnum = (typeof getCustomersQueryParamsOrderByEnum)[keyof typeof getCustomersQueryParamsOrderByEnum]

export type GetCustomersQueryParams = {
  /**
   * @default 10
   * @type number | undefined
   */
  perPage?: number
  /**
   * @default 0
   * @type number | undefined
   */
  pageIndex?: number
  /**
   * @default "desc"
   * @type string | undefined
   */
  orderBy?: GetCustomersQueryParamsOrderByEnum
  /**
   * @type string | undefined
   */
  customerName?: string
  /**
   * @type string | undefined
   */
  customerDocument?: string
}

export const customersDocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type CustomersDocumentTypeEnum = (typeof customersDocumentTypeEnum)[keyof typeof customersDocumentTypeEnum]

/**
 * @description Clientes obtidos com sucesso.
 */
export type GetCustomers200 = {
  /**
   * @type number
   */
  totalCount: number
  /**
   * @type number
   */
  pageCount: number
  /**
   * @type array
   */
  customers: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    name: string
    /**
     * @type string
     */
    document_type: CustomersDocumentTypeEnum
    /**
     * @type string
     */
    document: string
    /**
     * @type string
     */
    user_id: string
    /**
     * @type number
     */
    entry_number: number
    /**
     * @type string
     */
    person_id: string
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetCustomers401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Cliente não encontrado.
 */
export type GetCustomers404 = {
  /**
   * @type string
   */
  message: string
}

export type GetCustomersQueryResponse = GetCustomers200

export type GetCustomersQuery = {
  Response: GetCustomers200
  QueryParams: GetCustomersQueryParams
  Errors: GetCustomers401 | GetCustomers404
}

export type GetCustomersIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const getCustomersId200DocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type GetCustomersId200DocumentTypeEnum = (typeof getCustomersId200DocumentTypeEnum)[keyof typeof getCustomersId200DocumentTypeEnum]

export const getCustomersId200GenderEnum = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const

export type GetCustomersId200GenderEnum = (typeof getCustomersId200GenderEnum)[keyof typeof getCustomersId200GenderEnum]

export const addressesPlatformEnum = {
  SHOPEE: 'SHOPEE',
  MERCADO_LIVRE: 'MERCADO_LIVRE',
  TRAY: 'TRAY',
  LOCAL: 'LOCAL',
} as const

export type AddressesPlatformEnum = (typeof addressesPlatformEnum)[keyof typeof addressesPlatformEnum]

/**
 * @description Cliente obtido com sucesso.
 */
export type GetCustomersId200 = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  phone: string
  /**
   * @type string
   */
  phone_2: string | null
  /**
   * @type string
   */
  document_type: GetCustomersId200DocumentTypeEnum
  /**
   * @type string
   */
  document: string
  /**
   * @type string
   */
  document_2: string | null
  /**
   * @type string, email
   */
  email: string | null
  /**
   * @type string
   */
  state_registration: string | null
  /**
   * @type boolean
   */
  tax_free: boolean
  /**
   * @type string, date-time
   */
  created_at: string
  /**
   * @type string, date-time
   */
  updated_at: string
  /**
   * @type string
   */
  user_id: string
  /**
   * @type number
   */
  entry_number: number
  /**
   * @type string
   */
  gender: GetCustomersId200GenderEnum | null
  /**
   * @type string, date-time
   */
  birth_date: string | null
  /**
   * @type boolean
   */
  problematic: boolean
  /**
   * @type string
   */
  person_id: string
  /**
   * @type array
   */
  addresses: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    number: string
    /**
     * @type string, date-time
     */
    created_at: string
    /**
     * @type string, date-time
     */
    updated_at: string
    /**
     * @type string
     */
    recipient_name: string
    /**
     * @type string
     */
    recipient_phone: string
    /**
     * @type string
     */
    cep: string
    /**
     * @type string
     */
    street: string
    /**
     * @type string
     */
    complement: string | null
    /**
     * @type string
     */
    neighborhood: string
    /**
     * @type string
     */
    city: string
    /**
     * @type string
     */
    state: string
    /**
     * @type string
     */
    platform: AddressesPlatformEnum
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetCustomersId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Cliente não encontrado.
 */
export type GetCustomersId404 = {
  /**
   * @type string
   */
  message: string
}

export type GetCustomersIdQueryResponse = GetCustomersId200

export type GetCustomersIdQuery = {
  Response: GetCustomersId200
  PathParams: GetCustomersIdPathParams
  Errors: GetCustomersId401 | GetCustomersId404
}

export type PutCustomersIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const putCustomersId200Enum = {
  null: 'null',
} as const

export type PutCustomersId200Enum = (typeof putCustomersId200Enum)[keyof typeof putCustomersId200Enum]

/**
 * @description Cliente atualizado com sucesso.
 */
export type PutCustomersId200 = PutCustomersId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type PutCustomersId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Cliente não encontrado.
 */
export type PutCustomersId404 = {
  /**
   * @type string
   */
  message: string
}

export const putCustomersIdMutationRequestDocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type PutCustomersIdMutationRequestDocumentTypeEnum =
  (typeof putCustomersIdMutationRequestDocumentTypeEnum)[keyof typeof putCustomersIdMutationRequestDocumentTypeEnum]

export const putCustomersIdMutationRequestGenderEnum = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const

export type PutCustomersIdMutationRequestGenderEnum = (typeof putCustomersIdMutationRequestGenderEnum)[keyof typeof putCustomersIdMutationRequestGenderEnum]

export type PutCustomersIdMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @minLength 1
   * @type string
   */
  phone: string
  /**
   * @type string | undefined
   */
  phone_2?: string
  /**
   * @type string
   */
  document_type: PutCustomersIdMutationRequestDocumentTypeEnum
  /**
   * @minLength 1
   * @type string
   */
  document: string
  /**
   * @type string | undefined
   */
  document_2?: string
  /**
   * @minLength 1
   * @type string, email
   */
  email: string
  /**
   * @type string | undefined
   */
  state_registration?: string
  /**
   * @type boolean | undefined
   */
  tax_free?: boolean
  /**
   * @type string | undefined
   */
  gender?: PutCustomersIdMutationRequestGenderEnum
  /**
   * @type string | undefined, date-time
   */
  birth_date?: string
  /**
   * @type boolean | undefined
   */
  problematic?: boolean
  /**
   * @minLength 1
   * @pattern ^[cC][^\s-]{8,}$
   * @type string
   */
  address_id: string
  /**
   * @minLength 1
   * @type string
   */
  recipient_name: string
  /**
   * @minLength 1
   * @type string
   */
  recipient_phone: string
  /**
   * @minLength 1
   * @type string
   */
  cep: string
  /**
   * @minLength 1
   * @type string
   */
  street: string
  /**
   * @minLength 1
   * @type string
   */
  number: string
  /**
   * @type string | undefined
   */
  complement?: string
  /**
   * @minLength 1
   * @type string
   */
  neighborhood: string
  /**
   * @minLength 1
   * @type string
   */
  city: string
  /**
   * @minLength 1
   * @type string
   */
  state: string
}

export type PutCustomersIdMutationResponse = PutCustomersId200

export type PutCustomersIdMutation = {
  Response: PutCustomersId200
  Request: PutCustomersIdMutationRequest
  PathParams: PutCustomersIdPathParams
  Errors: PutCustomersId401 | PutCustomersId404
}

export type DeleteCustomersIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const deleteCustomersId200Enum = {
  null: 'null',
} as const

export type DeleteCustomersId200Enum = (typeof deleteCustomersId200Enum)[keyof typeof deleteCustomersId200Enum]

/**
 * @description Cliente deletado com sucesso.
 */
export type DeleteCustomersId200 = DeleteCustomersId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteCustomersId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Cliente não encontrado.
 */
export type DeleteCustomersId404 = {
  /**
   * @type string
   */
  message: string
}

export type DeleteCustomersIdMutationResponse = DeleteCustomersId200

export type DeleteCustomersIdMutation = {
  Response: DeleteCustomersId200
  PathParams: DeleteCustomersIdPathParams
  Errors: DeleteCustomersId401 | DeleteCustomersId404
}

export const postSuppliers201Enum = {
  null: 'null',
} as const

export type PostSuppliers201Enum = (typeof postSuppliers201Enum)[keyof typeof postSuppliers201Enum]

/**
 * @description Fornecedor cadastrado com sucesso.
 */
export type PostSuppliers201 = PostSuppliers201Enum | null

/**
 * @description Usuário não autenticado.
 */
export type PostSuppliers401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Fornecedor já cadastrado.
 */
export type PostSuppliers409 = {
  /**
   * @type string
   */
  message: string
}

export const postSuppliersMutationRequestDocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type PostSuppliersMutationRequestDocumentTypeEnum =
  (typeof postSuppliersMutationRequestDocumentTypeEnum)[keyof typeof postSuppliersMutationRequestDocumentTypeEnum]

export type PostSuppliersMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @minLength 1
   * @type string
   */
  phone: string
  /**
   * @type string | undefined
   */
  phone_2?: string
  /**
   * @type string
   */
  document_type: PostSuppliersMutationRequestDocumentTypeEnum
  /**
   * @minLength 1
   * @type string
   */
  document: string
  /**
   * @type string | undefined
   */
  document_2?: string
  /**
   * @minLength 1
   * @type string, email
   */
  email: string
  /**
   * @type string | undefined
   */
  state_registration?: string
  /**
   * @type boolean | undefined
   */
  tax_free?: boolean
  /**
   * @minLength 1
   * @type string
   */
  recipient_name: string
  /**
   * @minLength 1
   * @type string
   */
  recipient_phone: string
  /**
   * @minLength 1
   * @type string
   */
  cep: string
  /**
   * @minLength 1
   * @type string
   */
  street: string
  /**
   * @minLength 1
   * @type string
   */
  number: string
  /**
   * @type string | undefined
   */
  complement?: string
  /**
   * @minLength 1
   * @type string
   */
  neighborhood: string
  /**
   * @minLength 1
   * @type string
   */
  city: string
  /**
   * @minLength 1
   * @type string
   */
  state: string
}

export type PostSuppliersMutationResponse = PostSuppliers201

export type PostSuppliersMutation = {
  Response: PostSuppliers201
  Request: PostSuppliersMutationRequest
  Errors: PostSuppliers401 | PostSuppliers409
}

export const getSuppliersQueryParamsOrderByEnum = {
  desc: 'desc',
  asc: 'asc',
} as const

export type GetSuppliersQueryParamsOrderByEnum = (typeof getSuppliersQueryParamsOrderByEnum)[keyof typeof getSuppliersQueryParamsOrderByEnum]

export type GetSuppliersQueryParams = {
  /**
   * @default 10
   * @type number | undefined
   */
  perPage?: number
  /**
   * @default 0
   * @type number | undefined
   */
  pageIndex?: number
  /**
   * @default "desc"
   * @type string | undefined
   */
  orderBy?: GetSuppliersQueryParamsOrderByEnum
  /**
   * @type string | undefined
   */
  supplierName?: string
  /**
   * @type string | undefined
   */
  supplierDocument?: string
}

export const suppliersDocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type SuppliersDocumentTypeEnum = (typeof suppliersDocumentTypeEnum)[keyof typeof suppliersDocumentTypeEnum]

/**
 * @description Fornecedores obtidos com sucesso.
 */
export type GetSuppliers200 = {
  /**
   * @type number
   */
  totalCount: number
  /**
   * @type number
   */
  pageCount: number
  /**
   * @type array
   */
  suppliers: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    name: string
    /**
     * @type string
     */
    document_type: SuppliersDocumentTypeEnum
    /**
     * @type string
     */
    document: string
    /**
     * @type string
     */
    user_id: string
    /**
     * @type number
     */
    entry_number: number
    /**
     * @type string
     */
    person_id: string
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetSuppliers401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Fornecedor não encontrado.
 */
export type GetSuppliers404 = {
  /**
   * @type string
   */
  message: string
}

export type GetSuppliersQueryResponse = GetSuppliers200

export type GetSuppliersQuery = {
  Response: GetSuppliers200
  QueryParams: GetSuppliersQueryParams
  Errors: GetSuppliers401 | GetSuppliers404
}

export type GetSuppliersIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const getSuppliersId200DocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type GetSuppliersId200DocumentTypeEnum = (typeof getSuppliersId200DocumentTypeEnum)[keyof typeof getSuppliersId200DocumentTypeEnum]

export const addressesPlatformEnum2 = {
  SHOPEE: 'SHOPEE',
  MERCADO_LIVRE: 'MERCADO_LIVRE',
  TRAY: 'TRAY',
  LOCAL: 'LOCAL',
} as const

export type AddressesPlatformEnum2 = (typeof addressesPlatformEnum2)[keyof typeof addressesPlatformEnum2]

/**
 * @description Fornecedor obtido com sucesso.
 */
export type GetSuppliersId200 = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  phone: string
  /**
   * @type string
   */
  phone_2: string | null
  /**
   * @type string
   */
  document_type: GetSuppliersId200DocumentTypeEnum
  /**
   * @type string
   */
  document: string
  /**
   * @type string
   */
  document_2: string | null
  /**
   * @type string, email
   */
  email: string | null
  /**
   * @type string
   */
  state_registration: string | null
  /**
   * @type boolean
   */
  tax_free: boolean
  /**
   * @type string, date-time
   */
  created_at: string
  /**
   * @type string, date-time
   */
  updated_at: string
  /**
   * @type string
   */
  user_id: string
  /**
   * @type number
   */
  entry_number: number
  /**
   * @type string
   */
  person_id: string
  /**
   * @type array
   */
  addresses: {
    /**
     * @type string
     */
    number: string
    /**
     * @type string
     */
    id: string
    /**
     * @type string, date-time
     */
    created_at: string
    /**
     * @type string, date-time
     */
    updated_at: string
    /**
     * @type string
     */
    recipient_name: string
    /**
     * @type string
     */
    recipient_phone: string
    /**
     * @type string
     */
    cep: string
    /**
     * @type string
     */
    street: string
    /**
     * @type string
     */
    complement: string | null
    /**
     * @type string
     */
    neighborhood: string
    /**
     * @type string
     */
    city: string
    /**
     * @type string
     */
    state: string
    /**
     * @type string
     */
    platform: AddressesPlatformEnum2
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetSuppliersId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Fornecedor não encontrado.
 */
export type GetSuppliersId404 = {
  /**
   * @type string
   */
  message: string
}

export type GetSuppliersIdQueryResponse = GetSuppliersId200

export type GetSuppliersIdQuery = {
  Response: GetSuppliersId200
  PathParams: GetSuppliersIdPathParams
  Errors: GetSuppliersId401 | GetSuppliersId404
}

export type PutSuppliersIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const putSuppliersId200Enum = {
  null: 'null',
} as const

export type PutSuppliersId200Enum = (typeof putSuppliersId200Enum)[keyof typeof putSuppliersId200Enum]

/**
 * @description Fornecedor atualizado com sucesso.
 */
export type PutSuppliersId200 = PutSuppliersId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type PutSuppliersId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Fornecedor não encontrado.
 */
export type PutSuppliersId404 = {
  /**
   * @type string
   */
  message: string
}

export const putSuppliersIdMutationRequestDocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type PutSuppliersIdMutationRequestDocumentTypeEnum =
  (typeof putSuppliersIdMutationRequestDocumentTypeEnum)[keyof typeof putSuppliersIdMutationRequestDocumentTypeEnum]

export type PutSuppliersIdMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @minLength 1
   * @type string
   */
  phone: string
  /**
   * @type string | undefined
   */
  phone_2?: string
  /**
   * @type string
   */
  document_type: PutSuppliersIdMutationRequestDocumentTypeEnum
  /**
   * @minLength 1
   * @type string
   */
  document: string
  /**
   * @type string | undefined
   */
  document_2?: string
  /**
   * @minLength 1
   * @type string, email
   */
  email: string
  /**
   * @type string | undefined
   */
  state_registration?: string
  /**
   * @type boolean | undefined
   */
  tax_free?: boolean
  /**
   * @minLength 1
   * @pattern ^[cC][^\s-]{8,}$
   * @type string
   */
  address_id: string
  /**
   * @minLength 1
   * @type string
   */
  recipient_name: string
  /**
   * @minLength 1
   * @type string
   */
  recipient_phone: string
  /**
   * @minLength 1
   * @type string
   */
  cep: string
  /**
   * @minLength 1
   * @type string
   */
  street: string
  /**
   * @minLength 1
   * @type string
   */
  number: string
  /**
   * @type string | undefined
   */
  complement?: string
  /**
   * @minLength 1
   * @type string
   */
  neighborhood: string
  /**
   * @minLength 1
   * @type string
   */
  city: string
  /**
   * @minLength 1
   * @type string
   */
  state: string
}

export type PutSuppliersIdMutationResponse = PutSuppliersId200

export type PutSuppliersIdMutation = {
  Response: PutSuppliersId200
  Request: PutSuppliersIdMutationRequest
  PathParams: PutSuppliersIdPathParams
  Errors: PutSuppliersId401 | PutSuppliersId404
}

export type DeleteSuppliersIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const deleteSuppliersId200Enum = {
  null: 'null',
} as const

export type DeleteSuppliersId200Enum = (typeof deleteSuppliersId200Enum)[keyof typeof deleteSuppliersId200Enum]

/**
 * @description Fornecedor deletado com sucesso.
 */
export type DeleteSuppliersId200 = DeleteSuppliersId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteSuppliersId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Fornecedor não encontrado.
 */
export type DeleteSuppliersId404 = {
  /**
   * @type string
   */
  message: string
}

export type DeleteSuppliersIdMutationResponse = DeleteSuppliersId200

export type DeleteSuppliersIdMutation = {
  Response: DeleteSuppliersId200
  PathParams: DeleteSuppliersIdPathParams
  Errors: DeleteSuppliersId401 | DeleteSuppliersId404
}

export const postEmployees201Enum = {
  null: 'null',
} as const

export type PostEmployees201Enum = (typeof postEmployees201Enum)[keyof typeof postEmployees201Enum]

/**
 * @description Colaborador cadastrado com sucesso.
 */
export type PostEmployees201 = PostEmployees201Enum | null

/**
 * @description Usuário não autenticado.
 */
export type PostEmployees401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Colaborador já cadastrado.
 */
export type PostEmployees409 = {
  /**
   * @type string
   */
  message: string
}

export const postEmployeesMutationRequestDocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type PostEmployeesMutationRequestDocumentTypeEnum =
  (typeof postEmployeesMutationRequestDocumentTypeEnum)[keyof typeof postEmployeesMutationRequestDocumentTypeEnum]

export const postEmployeesMutationRequestGenderEnum = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const

export type PostEmployeesMutationRequestGenderEnum = (typeof postEmployeesMutationRequestGenderEnum)[keyof typeof postEmployeesMutationRequestGenderEnum]

export type PostEmployeesMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @minLength 1
   * @type string
   */
  phone: string
  /**
   * @type string | undefined
   */
  phone_2?: string
  /**
   * @type string
   */
  document_type: PostEmployeesMutationRequestDocumentTypeEnum
  /**
   * @minLength 1
   * @type string
   */
  document: string
  /**
   * @type string | undefined
   */
  document_2?: string
  /**
   * @minLength 1
   * @type string, email
   */
  email: string
  /**
   * @type string | undefined
   */
  state_registration?: string
  /**
   * @type boolean | undefined
   */
  tax_free?: boolean
  /**
   * @type string | undefined
   */
  gender?: PostEmployeesMutationRequestGenderEnum
  /**
   * @type string | undefined, date-time
   */
  birth_date?: string
  /**
   * @minLength 1
   * @type string
   */
  recipient_name: string
  /**
   * @minLength 1
   * @type string
   */
  recipient_phone: string
  /**
   * @minLength 1
   * @type string
   */
  cep: string
  /**
   * @minLength 1
   * @type string
   */
  street: string
  /**
   * @minLength 1
   * @type string
   */
  number: string
  /**
   * @type string | undefined
   */
  complement?: string
  /**
   * @minLength 1
   * @type string
   */
  neighborhood: string
  /**
   * @minLength 1
   * @type string
   */
  city: string
  /**
   * @minLength 1
   * @type string
   */
  state: string
}

export type PostEmployeesMutationResponse = PostEmployees201

export type PostEmployeesMutation = {
  Response: PostEmployees201
  Request: PostEmployeesMutationRequest
  Errors: PostEmployees401 | PostEmployees409
}

export const getEmployeesQueryParamsOrderByEnum = {
  desc: 'desc',
  asc: 'asc',
} as const

export type GetEmployeesQueryParamsOrderByEnum = (typeof getEmployeesQueryParamsOrderByEnum)[keyof typeof getEmployeesQueryParamsOrderByEnum]

export type GetEmployeesQueryParams = {
  /**
   * @default 10
   * @type number | undefined
   */
  perPage?: number
  /**
   * @default 0
   * @type number | undefined
   */
  pageIndex?: number
  /**
   * @default "desc"
   * @type string | undefined
   */
  orderBy?: GetEmployeesQueryParamsOrderByEnum
  /**
   * @type string | undefined
   */
  employeeName?: string
  /**
   * @type string | undefined
   */
  employeeDocument?: string
}

export const employeesDocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type EmployeesDocumentTypeEnum = (typeof employeesDocumentTypeEnum)[keyof typeof employeesDocumentTypeEnum]

/**
 * @description Colaboradores obtidos com sucesso.
 */
export type GetEmployees200 = {
  /**
   * @type number
   */
  totalCount: number
  /**
   * @type number
   */
  pageCount: number
  /**
   * @type array
   */
  employees: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    name: string
    /**
     * @type string
     */
    document_type: EmployeesDocumentTypeEnum
    /**
     * @type string
     */
    document: string
    /**
     * @type string
     */
    user_id: string
    /**
     * @type number
     */
    entry_number: number
    /**
     * @type string
     */
    person_id: string
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetEmployees401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Colaborador não encontrado.
 */
export type GetEmployees404 = {
  /**
   * @type string
   */
  message: string
}

export type GetEmployeesQueryResponse = GetEmployees200

export type GetEmployeesQuery = {
  Response: GetEmployees200
  QueryParams: GetEmployeesQueryParams
  Errors: GetEmployees401 | GetEmployees404
}

export type GetEmployeesIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const getEmployeesId200DocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type GetEmployeesId200DocumentTypeEnum = (typeof getEmployeesId200DocumentTypeEnum)[keyof typeof getEmployeesId200DocumentTypeEnum]

export const getEmployeesId200GenderEnum = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const

export type GetEmployeesId200GenderEnum = (typeof getEmployeesId200GenderEnum)[keyof typeof getEmployeesId200GenderEnum]

export const addressesPlatformEnum3 = {
  SHOPEE: 'SHOPEE',
  MERCADO_LIVRE: 'MERCADO_LIVRE',
  TRAY: 'TRAY',
  LOCAL: 'LOCAL',
} as const

export type AddressesPlatformEnum3 = (typeof addressesPlatformEnum3)[keyof typeof addressesPlatformEnum3]

/**
 * @description Colaborador obtido com sucesso.
 */
export type GetEmployeesId200 = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  phone: string
  /**
   * @type string
   */
  phone_2: string | null
  /**
   * @type string
   */
  document_type: GetEmployeesId200DocumentTypeEnum
  /**
   * @type string
   */
  document: string
  /**
   * @type string
   */
  document_2: string | null
  /**
   * @type string, email
   */
  email: string | null
  /**
   * @type string
   */
  state_registration: string | null
  /**
   * @type boolean
   */
  tax_free: boolean
  /**
   * @type string, date-time
   */
  created_at: string
  /**
   * @type string, date-time
   */
  updated_at: string
  /**
   * @type string
   */
  user_id: string
  /**
   * @type number
   */
  entry_number: number
  /**
   * @type string
   */
  gender: GetEmployeesId200GenderEnum | null
  /**
   * @type string, date-time
   */
  birth_date: string | null
  /**
   * @type string
   */
  person_id: string
  /**
   * @type array
   */
  addresses: {
    /**
     * @type string
     */
    number: string
    /**
     * @type string
     */
    id: string
    /**
     * @type string, date-time
     */
    created_at: string
    /**
     * @type string, date-time
     */
    updated_at: string
    /**
     * @type string
     */
    recipient_name: string
    /**
     * @type string
     */
    recipient_phone: string
    /**
     * @type string
     */
    cep: string
    /**
     * @type string
     */
    street: string
    /**
     * @type string
     */
    complement: string | null
    /**
     * @type string
     */
    neighborhood: string
    /**
     * @type string
     */
    city: string
    /**
     * @type string
     */
    state: string
    /**
     * @type string
     */
    platform: AddressesPlatformEnum3
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetEmployeesId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Colaborador não encontrado.
 */
export type GetEmployeesId404 = {
  /**
   * @type string
   */
  message: string
}

export type GetEmployeesIdQueryResponse = GetEmployeesId200

export type GetEmployeesIdQuery = {
  Response: GetEmployeesId200
  PathParams: GetEmployeesIdPathParams
  Errors: GetEmployeesId401 | GetEmployeesId404
}

export type PutEmployeesIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const putEmployeesId200Enum = {
  null: 'null',
} as const

export type PutEmployeesId200Enum = (typeof putEmployeesId200Enum)[keyof typeof putEmployeesId200Enum]

/**
 * @description Colaborador atualizado com sucesso.
 */
export type PutEmployeesId200 = PutEmployeesId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type PutEmployeesId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Colaborador não encontrado.
 */
export type PutEmployeesId404 = {
  /**
   * @type string
   */
  message: string
}

export const putEmployeesIdMutationRequestDocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type PutEmployeesIdMutationRequestDocumentTypeEnum =
  (typeof putEmployeesIdMutationRequestDocumentTypeEnum)[keyof typeof putEmployeesIdMutationRequestDocumentTypeEnum]

export const putEmployeesIdMutationRequestGenderEnum = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const

export type PutEmployeesIdMutationRequestGenderEnum = (typeof putEmployeesIdMutationRequestGenderEnum)[keyof typeof putEmployeesIdMutationRequestGenderEnum]

export type PutEmployeesIdMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @minLength 1
   * @type string
   */
  phone: string
  /**
   * @type string | undefined
   */
  phone_2?: string
  /**
   * @type string
   */
  document_type: PutEmployeesIdMutationRequestDocumentTypeEnum
  /**
   * @minLength 1
   * @type string
   */
  document: string
  /**
   * @type string | undefined
   */
  document_2?: string
  /**
   * @minLength 1
   * @type string, email
   */
  email: string
  /**
   * @type string | undefined
   */
  state_registration?: string
  /**
   * @type boolean | undefined
   */
  tax_free?: boolean
  /**
   * @type string | undefined
   */
  gender?: PutEmployeesIdMutationRequestGenderEnum
  /**
   * @type string | undefined, date-time
   */
  birth_date?: string
  /**
   * @minLength 1
   * @pattern ^[cC][^\s-]{8,}$
   * @type string
   */
  address_id: string
  /**
   * @minLength 1
   * @type string
   */
  recipient_name: string
  /**
   * @minLength 1
   * @type string
   */
  recipient_phone: string
  /**
   * @minLength 1
   * @type string
   */
  cep: string
  /**
   * @minLength 1
   * @type string
   */
  street: string
  /**
   * @minLength 1
   * @type string
   */
  number: string
  /**
   * @type string | undefined
   */
  complement?: string
  /**
   * @minLength 1
   * @type string
   */
  neighborhood: string
  /**
   * @minLength 1
   * @type string
   */
  city: string
  /**
   * @minLength 1
   * @type string
   */
  state: string
}

export type PutEmployeesIdMutationResponse = PutEmployeesId200

export type PutEmployeesIdMutation = {
  Response: PutEmployeesId200
  Request: PutEmployeesIdMutationRequest
  PathParams: PutEmployeesIdPathParams
  Errors: PutEmployeesId401 | PutEmployeesId404
}

export type DeleteEmployeesIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const deleteEmployeesId200Enum = {
  null: 'null',
} as const

export type DeleteEmployeesId200Enum = (typeof deleteEmployeesId200Enum)[keyof typeof deleteEmployeesId200Enum]

/**
 * @description Colaborador deletado com sucesso.
 */
export type DeleteEmployeesId200 = DeleteEmployeesId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteEmployeesId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Colaborador não encontrado.
 */
export type DeleteEmployeesId404 = {
  /**
   * @type string
   */
  message: string
}

export type DeleteEmployeesIdMutationResponse = DeleteEmployeesId200

export type DeleteEmployeesIdMutation = {
  Response: DeleteEmployeesId200
  PathParams: DeleteEmployeesIdPathParams
  Errors: DeleteEmployeesId401 | DeleteEmployeesId404
}

export const postProducts201Enum = {
  null: 'null',
} as const

export type PostProducts201Enum = (typeof postProducts201Enum)[keyof typeof postProducts201Enum]

/**
 * @description Produto cadastrado com sucesso.
 */
export type PostProducts201 = PostProducts201Enum | null

/**
 * @description Usuário não autenticado.
 */
export type PostProducts401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Fornecedor, marca, categoria ou unidade comercial não encontrado.
 */
export type PostProducts404 = {
  /**
   * @type string
   */
  message: string
}

export type PostProductsMutationRequest = {
  /**
   * @type string | undefined
   */
  supplier_id?: string
  /**
   * @type string | undefined
   */
  product_measurement_unit_id?: string
  /**
   * @type string
   */
  product_brand_id: string
  /**
   * @type array | undefined
   */
  product_category_ids?: {
    /**
     * @type string
     */
    id: string
  }[]
  /**
   * @minLength 1
   * @type string
   */
  reference_code: string
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @type string | undefined
   */
  model?: string
  /**
   * @type string | undefined
   */
  description?: string
  /**
   * @type integer | undefined
   */
  ncm?: number
  /**
   * @type integer | undefined
   */
  cfop?: number
  /**
   * @type string | undefined
   */
  cest?: string
  /**
   * @type string | undefined
   */
  merchandise_origin?: string
}

export type PostProductsMutationResponse = PostProducts201

export type PostProductsMutation = {
  Response: PostProducts201
  Request: PostProductsMutationRequest
  Errors: PostProducts401 | PostProducts404
}

export const getProductsQueryParamsOrderByEnum = {
  desc: 'desc',
  asc: 'asc',
} as const

export type GetProductsQueryParamsOrderByEnum = (typeof getProductsQueryParamsOrderByEnum)[keyof typeof getProductsQueryParamsOrderByEnum]

export type GetProductsQueryParams = {
  /**
   * @default 10
   * @type number | undefined
   */
  perPage?: number
  /**
   * @default 0
   * @type number | undefined
   */
  pageIndex?: number
  /**
   * @default "desc"
   * @type string | undefined
   */
  orderBy?: GetProductsQueryParamsOrderByEnum
  /**
   * @type string | undefined
   */
  productName?: string
}

/**
 * @description Produtos obtidos com sucesso.
 */
export type GetProducts200 = {
  /**
   * @type number
   */
  totalCount: number
  /**
   * @type number
   */
  pageCount: number
  /**
   * @type array
   */
  products: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    name: string
    /**
     * @type number
     */
    ncm: number | null
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetProducts401 = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsQueryResponse = GetProducts200

export type GetProductsQuery = {
  Response: GetProducts200
  QueryParams: GetProductsQueryParams
  Errors: GetProducts401
}

export type GetProductsIdPathParams = {
  /**
   * @type string
   */
  id: string
}

/**
 * @description Produto obtido com sucesso.
 */
export type GetProductsId200 = {
  /**
   * @type string
   */
  id: string
  /**
   * @minLength 1
   * @type string
   */
  reference_code: string
  /**
   * @minLength 1
   * @type string
   */
  product_sku: string
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @type string
   */
  model: string | null
  /**
   * @type string
   */
  description: string | null
  /**
   * @type integer
   */
  ncm: number | null
  /**
   * @type integer
   */
  cfop: number | null
  /**
   * @type string
   */
  cest: string | null
  /**
   * @type string
   */
  merchandise_origin: string | null
  /**
   * @type string, date-time
   */
  created_at: string
  /**
   * @type string, date-time
   */
  updated_at: string
  /**
   * @type object
   */
  product_measurement_unit: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    name: string
    /**
     * @type string
     */
    acronym: string
  } | null
  /**
   * @type object
   */
  product_brand: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    name: string
    /**
     * @type string
     */
    reference_code: string
    /**
     * @type string, date-time
     */
    created_at: string
  } | null
  /**
   * @type array
   */
  product_categories: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    name: string
    /**
     * @type string, date-time
     */
    created_at: string
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetProductsId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Produto não encontrado.
 */
export type GetProductsId404 = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsIdQueryResponse = GetProductsId200

export type GetProductsIdQuery = {
  Response: GetProductsId200
  PathParams: GetProductsIdPathParams
  Errors: GetProductsId401 | GetProductsId404
}

export type PutProductsIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const putProductsId200Enum = {
  null: 'null',
} as const

export type PutProductsId200Enum = (typeof putProductsId200Enum)[keyof typeof putProductsId200Enum]

/**
 * @description Produto atualizado com sucesso.
 */
export type PutProductsId200 = PutProductsId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type PutProductsId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Produto, marca ou fornecedor não encontrado.
 */
export type PutProductsId404 = {
  /**
   * @type string
   */
  message: string
}

export type PutProductsIdMutationRequest = {
  /**
   * @type string | undefined
   */
  supplier_id?: string
  /**
   * @type string | undefined
   */
  product_measurement_unit_id?: string
  /**
   * @type string | undefined
   */
  product_brand_id?: string
  /**
   * @type array | undefined
   */
  product_category_ids?: {
    /**
     * @type string
     */
    id: string
  }[]
  /**
   * @minLength 1
   * @type string
   */
  reference_code: string
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @type string | undefined
   */
  model?: string
  /**
   * @type string | undefined
   */
  description?: string
  /**
   * @type integer | undefined
   */
  ncm?: number
  /**
   * @type integer | undefined
   */
  cfop?: number
  /**
   * @type string | undefined
   */
  cest?: string
  /**
   * @type string | undefined
   */
  merchandise_origin?: string
}

export type PutProductsIdMutationResponse = PutProductsId200

export type PutProductsIdMutation = {
  Response: PutProductsId200
  Request: PutProductsIdMutationRequest
  PathParams: PutProductsIdPathParams
  Errors: PutProductsId401 | PutProductsId404
}

export type DeleteProductsIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const deleteProductsId200Enum = {
  null: 'null',
} as const

export type DeleteProductsId200Enum = (typeof deleteProductsId200Enum)[keyof typeof deleteProductsId200Enum]

/**
 * @description Produto deletado com sucesso.
 */
export type DeleteProductsId200 = DeleteProductsId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteProductsId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Produto não encontrado.
 */
export type DeleteProductsId404 = {
  /**
   * @type string
   */
  message: string
}

export type DeleteProductsIdMutationResponse = DeleteProductsId200

export type DeleteProductsIdMutation = {
  Response: DeleteProductsId200
  PathParams: DeleteProductsIdPathParams
  Errors: DeleteProductsId401 | DeleteProductsId404
}

/**
 * @description Produto cadastrado com sucesso.
 */
export type PostProductsUpload201 = {
  /**
   * @type string
   */
  fileUrl: string
}

/**
 * @description Imagem inválida.
 */
export type PostProductsUpload400 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Usuário não autenticado.
 */
export type PostProductsUpload401 = {
  /**
   * @type string
   */
  message: string
}

export type PostProductsUploadMutationRequest = {
  file?: any
}

export type PostProductsUploadMutationResponse = PostProductsUpload201

export type PostProductsUploadMutation = {
  Response: PostProductsUpload201
  Request: PostProductsUploadMutationRequest
  Errors: PostProductsUpload400 | PostProductsUpload401
}

/**
 * @description Unidades de medida de produtos obtidas com sucesso.
 */
export type GetProductsMeasurementUnits200 = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  acronym: string
}[]

/**
 * @description Usuário não autenticado.
 */
export type GetProductsMeasurementUnits401 = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsMeasurementUnitsQueryResponse = GetProductsMeasurementUnits200

export type GetProductsMeasurementUnitsQuery = {
  Response: GetProductsMeasurementUnits200
  Errors: GetProductsMeasurementUnits401
}

export const postProductsBrands201Enum = {
  null: 'null',
} as const

export type PostProductsBrands201Enum = (typeof postProductsBrands201Enum)[keyof typeof postProductsBrands201Enum]

/**
 * @description Marca cadastrado com sucesso.
 */
export type PostProductsBrands201 = PostProductsBrands201Enum | null

/**
 * @description Usuário não autenticado.
 */
export type PostProductsBrands401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Marca já cadastrado.
 */
export type PostProductsBrands409 = {
  /**
   * @type string
   */
  message: string
}

export type PostProductsBrandsMutationRequest = {
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  reference_code: string
}

export type PostProductsBrandsMutationResponse = PostProductsBrands201

export type PostProductsBrandsMutation = {
  Response: PostProductsBrands201
  Request: PostProductsBrandsMutationRequest
  Errors: PostProductsBrands401 | PostProductsBrands409
}

/**
 * @description Marcas de produtos obtidas com sucesso.
 */
export type GetProductsBrands200 = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  reference_code: string
}[]

/**
 * @description Usuário não autenticado.
 */
export type GetProductsBrands401 = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsBrandsQueryResponse = GetProductsBrands200

export type GetProductsBrandsQuery = {
  Response: GetProductsBrands200
  Errors: GetProductsBrands401
}

export type DeleteProductsBrandsIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const deleteProductsBrandsId200Enum = {
  null: 'null',
} as const

export type DeleteProductsBrandsId200Enum = (typeof deleteProductsBrandsId200Enum)[keyof typeof deleteProductsBrandsId200Enum]

/**
 * @description Marca deletada com sucesso.
 */
export type DeleteProductsBrandsId200 = DeleteProductsBrandsId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteProductsBrandsId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Marca não encontrado.
 */
export type DeleteProductsBrandsId404 = {
  /**
   * @type string
   */
  message: string
}

export type DeleteProductsBrandsIdMutationResponse = DeleteProductsBrandsId200

export type DeleteProductsBrandsIdMutation = {
  Response: DeleteProductsBrandsId200
  PathParams: DeleteProductsBrandsIdPathParams
  Errors: DeleteProductsBrandsId401 | DeleteProductsBrandsId404
}

export const postProductsCategories201Enum = {
  null: 'null',
} as const

export type PostProductsCategories201Enum = (typeof postProductsCategories201Enum)[keyof typeof postProductsCategories201Enum]

/**
 * @description Categoria cadastrado com sucesso.
 */
export type PostProductsCategories201 = PostProductsCategories201Enum | null

/**
 * @description Usuário não autenticado.
 */
export type PostProductsCategories401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Categoria já cadastrado.
 */
export type PostProductsCategories409 = {
  /**
   * @type string
   */
  message: string
}

export type PostProductsCategoriesMutationRequest = {
  /**
   * @type string
   */
  name: string
}

export type PostProductsCategoriesMutationResponse = PostProductsCategories201

export type PostProductsCategoriesMutation = {
  Response: PostProductsCategories201
  Request: PostProductsCategoriesMutationRequest
  Errors: PostProductsCategories401 | PostProductsCategories409
}

/**
 * @description Categorias de produtos obtidas com sucesso.
 */
export type GetProductsCategories200 = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  name: string
}[]

/**
 * @description Usuário não autenticado.
 */
export type GetProductsCategories401 = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsCategoriesQueryResponse = GetProductsCategories200

export type GetProductsCategoriesQuery = {
  Response: GetProductsCategories200
  Errors: GetProductsCategories401
}

export type DeleteProductsCategoriesIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const deleteProductsCategoriesId200Enum = {
  null: 'null',
} as const

export type DeleteProductsCategoriesId200Enum = (typeof deleteProductsCategoriesId200Enum)[keyof typeof deleteProductsCategoriesId200Enum]

/**
 * @description Categoria deletada com sucesso.
 */
export type DeleteProductsCategoriesId200 = DeleteProductsCategoriesId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteProductsCategoriesId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Categoria não encontrado.
 */
export type DeleteProductsCategoriesId404 = {
  /**
   * @type string
   */
  message: string
}

export type DeleteProductsCategoriesIdMutationResponse = DeleteProductsCategoriesId200

export type DeleteProductsCategoriesIdMutation = {
  Response: DeleteProductsCategoriesId200
  PathParams: DeleteProductsCategoriesIdPathParams
  Errors: DeleteProductsCategoriesId401 | DeleteProductsCategoriesId404
}

export const postProductsAttributesNames201Enum = {
  null: 'null',
} as const

export type PostProductsAttributesNames201Enum = (typeof postProductsAttributesNames201Enum)[keyof typeof postProductsAttributesNames201Enum]

/**
 * @description Nome do atributo do produto cadastrado com sucesso.
 */
export type PostProductsAttributesNames201 = PostProductsAttributesNames201Enum | null

/**
 * @description Usuário não autenticado.
 */
export type PostProductsAttributesNames401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Nome do atributo do produto já cadastrado.
 */
export type PostProductsAttributesNames409 = {
  /**
   * @type string
   */
  message: string
}

export type PostProductsAttributesNamesMutationRequest = {
  /**
   * @type string
   */
  name: string
}

export type PostProductsAttributesNamesMutationResponse = PostProductsAttributesNames201

export type PostProductsAttributesNamesMutation = {
  Response: PostProductsAttributesNames201
  Request: PostProductsAttributesNamesMutationRequest
  Errors: PostProductsAttributesNames401 | PostProductsAttributesNames409
}

export const getProductsAttributesNamesQueryParamsOrderByEnum = {
  desc: 'desc',
  asc: 'asc',
} as const

export type GetProductsAttributesNamesQueryParamsOrderByEnum =
  (typeof getProductsAttributesNamesQueryParamsOrderByEnum)[keyof typeof getProductsAttributesNamesQueryParamsOrderByEnum]

export type GetProductsAttributesNamesQueryParams = {
  /**
   * @default 10
   * @type number | undefined
   */
  perPage?: number
  /**
   * @default 0
   * @type number | undefined
   */
  pageIndex?: number
  /**
   * @default "desc"
   * @type string | undefined
   */
  orderBy?: GetProductsAttributesNamesQueryParamsOrderByEnum
  /**
   * @type string | undefined
   */
  attributeName?: string
}

/**
 * @description Nomes dos atributos dos produtos obtidos com sucesso.
 */
export type GetProductsAttributesNames200 = {
  /**
   * @type number
   */
  totalCount: number
  /**
   * @type number
   */
  pageCount: number
  /**
   * @type array
   */
  productAttributeNames: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    name: string
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetProductsAttributesNames401 = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsAttributesNamesQueryResponse = GetProductsAttributesNames200

export type GetProductsAttributesNamesQuery = {
  Response: GetProductsAttributesNames200
  QueryParams: GetProductsAttributesNamesQueryParams
  Errors: GetProductsAttributesNames401
}

export const postProductsAttributesValues201Enum = {
  null: 'null',
} as const

export type PostProductsAttributesValues201Enum = (typeof postProductsAttributesValues201Enum)[keyof typeof postProductsAttributesValues201Enum]

/**
 * @description Valor do atributo do produto cadastrado com sucesso.
 */
export type PostProductsAttributesValues201 = PostProductsAttributesValues201Enum | null

/**
 * @description Usuário não autenticado.
 */
export type PostProductsAttributesValues401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Valor do atributo do produto já cadastrado.
 */
export type PostProductsAttributesValues409 = {
  /**
   * @type string
   */
  message: string
}

export type PostProductsAttributesValuesMutationRequest = {
  /**
   * @type string
   */
  product_attribute_name_id: string
  /**
   * @type string
   */
  value: string
}

export type PostProductsAttributesValuesMutationResponse = PostProductsAttributesValues201

export type PostProductsAttributesValuesMutation = {
  Response: PostProductsAttributesValues201
  Request: PostProductsAttributesValuesMutationRequest
  Errors: PostProductsAttributesValues401 | PostProductsAttributesValues409
}

export const getProductsAttributesValuesQueryParamsOrderByEnum = {
  desc: 'desc',
  asc: 'asc',
} as const

export type GetProductsAttributesValuesQueryParamsOrderByEnum =
  (typeof getProductsAttributesValuesQueryParamsOrderByEnum)[keyof typeof getProductsAttributesValuesQueryParamsOrderByEnum]

export type GetProductsAttributesValuesQueryParams = {
  /**
   * @type string
   */
  productAttributeNameId: string
  /**
   * @default 10
   * @type number | undefined
   */
  perPage?: number
  /**
   * @default 0
   * @type number | undefined
   */
  pageIndex?: number
  /**
   * @default "desc"
   * @type string | undefined
   */
  orderBy?: GetProductsAttributesValuesQueryParamsOrderByEnum
  /**
   * @type string | undefined
   */
  attributeValue?: string
}

/**
 * @description Valores dos atributos dos produtos obtidos com sucesso.
 */
export type GetProductsAttributesValues200 = {
  /**
   * @type number
   */
  totalCount: number
  /**
   * @type number
   */
  pageCount: number
  /**
   * @type array
   */
  productAttributeValues: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    value: string
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetProductsAttributesValues401 = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsAttributesValuesQueryResponse = GetProductsAttributesValues200

export type GetProductsAttributesValuesQuery = {
  Response: GetProductsAttributesValues200
  QueryParams: GetProductsAttributesValuesQueryParams
  Errors: GetProductsAttributesValues401
}

export type GetProductsAttributesNamesIdPathParams = {
  /**
   * @type string
   */
  id: string
}

/**
 * @description Nome de atributo do produto obtido com sucesso.
 */
export type GetProductsAttributesNamesId200 = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  name: string
  /**
   * @type string, date-time
   */
  created_at: string
}

/**
 * @description Usuário não autenticado.
 */
export type GetProductsAttributesNamesId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Nome de atributo do produto não encontrado.
 */
export type GetProductsAttributesNamesId404 = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsAttributesNamesIdQueryResponse = GetProductsAttributesNamesId200

export type GetProductsAttributesNamesIdQuery = {
  Response: GetProductsAttributesNamesId200
  PathParams: GetProductsAttributesNamesIdPathParams
  Errors: GetProductsAttributesNamesId401 | GetProductsAttributesNamesId404
}

export type PutProductsAttributesNamesIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const putProductsAttributesNamesId200Enum = {
  null: 'null',
} as const

export type PutProductsAttributesNamesId200Enum = (typeof putProductsAttributesNamesId200Enum)[keyof typeof putProductsAttributesNamesId200Enum]

/**
 * @description Nome de atributo do produto atualizado com sucesso.
 */
export type PutProductsAttributesNamesId200 = PutProductsAttributesNamesId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type PutProductsAttributesNamesId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Nome de atributo do produto não encontrado.
 */
export type PutProductsAttributesNamesId404 = {
  /**
   * @type string
   */
  message: string
}

export type PutProductsAttributesNamesIdMutationRequest = {
  /**
   * @type string
   */
  name: string
}

export type PutProductsAttributesNamesIdMutationResponse = PutProductsAttributesNamesId200

export type PutProductsAttributesNamesIdMutation = {
  Response: PutProductsAttributesNamesId200
  Request: PutProductsAttributesNamesIdMutationRequest
  PathParams: PutProductsAttributesNamesIdPathParams
  Errors: PutProductsAttributesNamesId401 | PutProductsAttributesNamesId404
}

export type DeleteProductsAttributesNamesIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const deleteProductsAttributesNamesId200Enum = {
  null: 'null',
} as const

export type DeleteProductsAttributesNamesId200Enum = (typeof deleteProductsAttributesNamesId200Enum)[keyof typeof deleteProductsAttributesNamesId200Enum]

/**
 * @description Nome de atributo do produto deletado com sucesso.
 */
export type DeleteProductsAttributesNamesId200 = DeleteProductsAttributesNamesId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteProductsAttributesNamesId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Nome de atributo do produto não encontrado.
 */
export type DeleteProductsAttributesNamesId404 = {
  /**
   * @type string
   */
  message: string
}

export type DeleteProductsAttributesNamesIdMutationResponse = DeleteProductsAttributesNamesId200

export type DeleteProductsAttributesNamesIdMutation = {
  Response: DeleteProductsAttributesNamesId200
  PathParams: DeleteProductsAttributesNamesIdPathParams
  Errors: DeleteProductsAttributesNamesId401 | DeleteProductsAttributesNamesId404
}

export type GetProductsAttributesValuesIdPathParams = {
  /**
   * @type string
   */
  id: string
}

/**
 * @description Valor de atributo do produto obtido com sucesso.
 */
export type GetProductsAttributesValuesId200 = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  value: string
  /**
   * @type string, date-time
   */
  created_at: string
}

/**
 * @description Usuário não autenticado.
 */
export type GetProductsAttributesValuesId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Valor de atributo do produto não encontrado.
 */
export type GetProductsAttributesValuesId404 = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsAttributesValuesIdQueryResponse = GetProductsAttributesValuesId200

export type GetProductsAttributesValuesIdQuery = {
  Response: GetProductsAttributesValuesId200
  PathParams: GetProductsAttributesValuesIdPathParams
  Errors: GetProductsAttributesValuesId401 | GetProductsAttributesValuesId404
}

export type PutProductsAttributesValuesIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const putProductsAttributesValuesId200Enum = {
  null: 'null',
} as const

export type PutProductsAttributesValuesId200Enum = (typeof putProductsAttributesValuesId200Enum)[keyof typeof putProductsAttributesValuesId200Enum]

/**
 * @description Valor de atributo do produto atualizado com sucesso.
 */
export type PutProductsAttributesValuesId200 = PutProductsAttributesValuesId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type PutProductsAttributesValuesId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Valor de atributo do produto não encontrado.
 */
export type PutProductsAttributesValuesId404 = {
  /**
   * @type string
   */
  message: string
}

export type PutProductsAttributesValuesIdMutationRequest = {
  /**
   * @type string
   */
  value: string
}

export type PutProductsAttributesValuesIdMutationResponse = PutProductsAttributesValuesId200

export type PutProductsAttributesValuesIdMutation = {
  Response: PutProductsAttributesValuesId200
  Request: PutProductsAttributesValuesIdMutationRequest
  PathParams: PutProductsAttributesValuesIdPathParams
  Errors: PutProductsAttributesValuesId401 | PutProductsAttributesValuesId404
}

export type DeleteProductsAttributesValuesIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const deleteProductsAttributesValuesId200Enum = {
  null: 'null',
} as const

export type DeleteProductsAttributesValuesId200Enum = (typeof deleteProductsAttributesValuesId200Enum)[keyof typeof deleteProductsAttributesValuesId200Enum]

/**
 * @description Valor de atributo do produto deletado com sucesso.
 */
export type DeleteProductsAttributesValuesId200 = DeleteProductsAttributesValuesId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteProductsAttributesValuesId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Valor de atributo do produto não encontrado.
 */
export type DeleteProductsAttributesValuesId404 = {
  /**
   * @type string
   */
  message: string
}

export type DeleteProductsAttributesValuesIdMutationResponse = DeleteProductsAttributesValuesId200

export type DeleteProductsAttributesValuesIdMutation = {
  Response: DeleteProductsAttributesValuesId200
  PathParams: DeleteProductsAttributesValuesIdPathParams
  Errors: DeleteProductsAttributesValuesId401 | DeleteProductsAttributesValuesId404
}

export const postProductsVariations201Enum = {
  null: 'null',
} as const

export type PostProductsVariations201Enum = (typeof postProductsVariations201Enum)[keyof typeof postProductsVariations201Enum]

/**
 * @description Variação cadastrada com sucesso.
 */
export type PostProductsVariations201 = PostProductsVariations201Enum | null

/**
 * @description Usuário não autenticado.
 */
export type PostProductsVariations401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Variação já cadastrada.
 */
export type PostProductsVariations409 = {
  /**
   * @type string
   */
  message: string
}

export type PostProductsVariationsMutationRequest = {
  /**
   * @pattern ^[cC][^\s-]{8,}$
   * @type string
   */
  product_id: string
  /**
   * @type string | undefined
   */
  barcode?: string
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @type number | undefined
   */
  length_in_centimeters?: number
  /**
   * @type number | undefined
   */
  height_in_centimeters?: number
  /**
   * @type number | undefined
   */
  width_in_centimeters?: number
  /**
   * @type number | undefined
   */
  weight_in_grams?: number
  /**
   * @type number
   */
  average_cost: number
  /**
   * @type number
   */
  cost_price: number
  /**
   * @type number
   */
  selling_price: number
  /**
   * @type number | undefined
   */
  suggested_maximum_discount?: number
  /**
   * @type string | undefined, date-time
   */
  promotion_starts_at?: string
  /**
   * @type string | undefined, date-time
   */
  promotion_ends_at?: string
  /**
   * @type string | undefined
   */
  product_storage_location?: string
  /**
   * @type string
   */
  product_condition: string
  /**
   * @type string | undefined, date-time
   */
  product_expiration_date?: string
  /**
   * @type string | undefined, date-time
   */
  warranty_date?: string
  /**
   * @type number
   */
  current_stock: number
  /**
   * @type number
   */
  minimum_stock_level: number
  /**
   * @type number
   */
  products_in_review: number
  /**
   * @type boolean | undefined
   */
  update_stock?: boolean
  /**
   * @type boolean | undefined
   */
  track_inventory?: boolean
  /**
   * @type boolean | undefined
   */
  is_available?: boolean
}

export type PostProductsVariationsMutationResponse = PostProductsVariations201

export type PostProductsVariationsMutation = {
  Response: PostProductsVariations201
  Request: PostProductsVariationsMutationRequest
  Errors: PostProductsVariations401 | PostProductsVariations409
}

export const getProductsVariationsQueryParamsOrderByEnum = {
  desc: 'desc',
  asc: 'asc',
} as const

export type GetProductsVariationsQueryParamsOrderByEnum =
  (typeof getProductsVariationsQueryParamsOrderByEnum)[keyof typeof getProductsVariationsQueryParamsOrderByEnum]

export type GetProductsVariationsQueryParams = {
  /**
   * @default 10
   * @type number | undefined
   */
  perPage?: number
  /**
   * @default 0
   * @type number | undefined
   */
  pageIndex?: number
  /**
   * @default "desc"
   * @type string | undefined
   */
  orderBy?: GetProductsVariationsQueryParamsOrderByEnum
  /**
   * @type string | undefined
   */
  productId?: string
  /**
   * @type string | undefined
   */
  productVariationName?: string
}

/**
 * @description Variações de produtos obtidos com sucesso.
 */
export type GetProductsVariations200 = {
  /**
   * @type number
   */
  totalCount: number
  /**
   * @type number
   */
  pageCount: number
  /**
   * @type array
   */
  productVariations: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    barcode: string | null
    /**
     * @minLength 1
     * @type string
     */
    name: string
    /**
     * @type number
     */
    average_cost: number
    /**
     * @type number
     */
    cost_price: number
    /**
     * @type number
     */
    selling_price: number
    /**
     * @type string
     */
    product_storage_location: string | null
    /**
     * @type number
     */
    current_stock: number
    /**
     * @type number
     */
    minimum_stock_level: number
    /**
     * @type number
     */
    products_in_review: number
    /**
     * @type boolean | undefined
     */
    track_inventory?: boolean
    /**
     * @type boolean | undefined
     */
    is_available?: boolean
    /**
     * @type string, date-time
     */
    created_at: string
    /**
     * @type string
     */
    product_id: string
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetProductsVariations401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Variações de produtos não encontrado.
 */
export type GetProductsVariations404 = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsVariationsQueryResponse = GetProductsVariations200

export type GetProductsVariationsQuery = {
  Response: GetProductsVariations200
  QueryParams: GetProductsVariationsQueryParams
  Errors: GetProductsVariations401 | GetProductsVariations404
}

export type GetProductsVariationsIdPathParams = {
  /**
   * @type string
   */
  id: string
}

/**
 * @description Variação de produto obtido com sucesso.
 */
export type GetProductsVariationsId200 = {
  /**
   * @type string
   */
  product_id: string
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  barcode: string | null
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @type number
   */
  average_cost: number
  /**
   * @type number
   */
  cost_price: number
  /**
   * @type number
   */
  selling_price: number
  /**
   * @type string
   */
  product_storage_location: string | null
  /**
   * @type number
   */
  current_stock: number
  /**
   * @type number
   */
  minimum_stock_level: number
  /**
   * @type number
   */
  products_in_review: number
  /**
   * @type boolean | undefined
   */
  track_inventory?: boolean
  /**
   * @type boolean | undefined
   */
  is_available?: boolean
  /**
   * @type array
   */
  product_attribute_names: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    name: string
    /**
     * @type array
     */
    product_attribute_values: {
      /**
       * @type string
       */
      id: string
      /**
       * @type string
       */
      value: string
    }[]
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetProductsVariationsId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Variação de produto não encontrado.
 */
export type GetProductsVariationsId404 = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsVariationsIdQueryResponse = GetProductsVariationsId200

export type GetProductsVariationsIdQuery = {
  Response: GetProductsVariationsId200
  PathParams: GetProductsVariationsIdPathParams
  Errors: GetProductsVariationsId401 | GetProductsVariationsId404
}

export type PutProductsVariationsIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const putProductsVariationsId200Enum = {
  null: 'null',
} as const

export type PutProductsVariationsId200Enum = (typeof putProductsVariationsId200Enum)[keyof typeof putProductsVariationsId200Enum]

/**
 * @description Variação atualizada com sucesso.
 */
export type PutProductsVariationsId200 = PutProductsVariationsId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type PutProductsVariationsId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Variação não encontrada.
 */
export type PutProductsVariationsId404 = {
  /**
   * @type string
   */
  message: string
}

export type PutProductsVariationsIdMutationRequest = {
  /**
   * @pattern ^[cC][^\s-]{8,}$
   * @type string
   */
  product_id: string
  /**
   * @type string | undefined
   */
  barcode?: string
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @type number | undefined
   */
  length_in_centimeters?: number
  /**
   * @type number | undefined
   */
  height_in_centimeters?: number
  /**
   * @type number | undefined
   */
  width_in_centimeters?: number
  /**
   * @type number | undefined
   */
  weight_in_grams?: number
  /**
   * @type number
   */
  average_cost: number
  /**
   * @type number
   */
  cost_price: number
  /**
   * @type number
   */
  selling_price: number
  /**
   * @type number | undefined
   */
  suggested_maximum_discount?: number
  /**
   * @type string | undefined, date-time
   */
  promotion_starts_at?: string
  /**
   * @type string | undefined, date-time
   */
  promotion_ends_at?: string
  /**
   * @type string | undefined
   */
  product_storage_location?: string
  /**
   * @type string
   */
  product_condition: string
  /**
   * @type string | undefined, date-time
   */
  product_expiration_date?: string
  /**
   * @type string | undefined, date-time
   */
  warranty_date?: string
  /**
   * @type number
   */
  current_stock: number
  /**
   * @type number
   */
  minimum_stock_level: number
  /**
   * @type number
   */
  products_in_review: number
  /**
   * @type boolean | undefined
   */
  update_stock?: boolean
  /**
   * @type boolean | undefined
   */
  track_inventory?: boolean
  /**
   * @type boolean | undefined
   */
  is_available?: boolean
}

export type PutProductsVariationsIdMutationResponse = PutProductsVariationsId200

export type PutProductsVariationsIdMutation = {
  Response: PutProductsVariationsId200
  Request: PutProductsVariationsIdMutationRequest
  PathParams: PutProductsVariationsIdPathParams
  Errors: PutProductsVariationsId401 | PutProductsVariationsId404
}

export type DeleteProductsVariationsIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const deleteProductsVariationsId200Enum = {
  null: 'null',
} as const

export type DeleteProductsVariationsId200Enum = (typeof deleteProductsVariationsId200Enum)[keyof typeof deleteProductsVariationsId200Enum]

/**
 * @description Variação de produto deletado com sucesso.
 */
export type DeleteProductsVariationsId200 = DeleteProductsVariationsId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteProductsVariationsId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Variação de produto não encontrado.
 */
export type DeleteProductsVariationsId404 = {
  /**
   * @type string
   */
  message: string
}

export type DeleteProductsVariationsIdMutationResponse = DeleteProductsVariationsId200

export type DeleteProductsVariationsIdMutation = {
  Response: DeleteProductsVariationsId200
  PathParams: DeleteProductsVariationsIdPathParams
  Errors: DeleteProductsVariationsId401 | DeleteProductsVariationsId404
}

export const postOrders201Enum = {
  null: 'null',
} as const

export type PostOrders201Enum = (typeof postOrders201Enum)[keyof typeof postOrders201Enum]

/**
 * @description Pedido criado com sucesso.
 */
export type PostOrders201 = PostOrders201Enum | null

/**
 * @description Dados inválidos.
 */
export type PostOrders400 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Usuário não autenticado.
 */
export type PostOrders401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Cliente ou Endereço não encontrado.
 */
export type PostOrders404 = {
  /**
   * @type string
   */
  message: string
}

export const postOrdersMutationRequestStatusEnum = {
  PROCESSED: 'PROCESSED',
  CANCELLED: 'CANCELLED',
} as const

export type PostOrdersMutationRequestStatusEnum = (typeof postOrdersMutationRequestStatusEnum)[keyof typeof postOrdersMutationRequestStatusEnum]

export const postOrdersMutationRequestShippingCarrierEnum = {
  CORREIOS: 'CORREIOS',
  JADLOG: 'JADLOG',
} as const

export type PostOrdersMutationRequestShippingCarrierEnum =
  (typeof postOrdersMutationRequestShippingCarrierEnum)[keyof typeof postOrdersMutationRequestShippingCarrierEnum]

export const postOrdersMutationRequestPaymentMethodEnum = {
  CREDIT_CARD: 'CREDIT_CARD',
  DEBIT_CARD: 'DEBIT_CARD',
  PIX: 'PIX',
} as const

export type PostOrdersMutationRequestPaymentMethodEnum =
  (typeof postOrdersMutationRequestPaymentMethodEnum)[keyof typeof postOrdersMutationRequestPaymentMethodEnum]

export type PostOrdersMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  customer_id: string
  /**
   * @minLength 1
   * @type string
   */
  address_id: string
  /**
   * @default "PROCESSED"
   * @type string | undefined
   */
  status?: PostOrdersMutationRequestStatusEnum
  /**
   * @default "CORREIOS"
   * @type string | undefined
   */
  shipping_carrier?: PostOrdersMutationRequestShippingCarrierEnum
  /**
   * @type string
   */
  payment_method: PostOrdersMutationRequestPaymentMethodEnum
  /**
   * @minLength 0
   * @default 0
   * @type number | undefined
   */
  shipping_cost?: number
  /**
   * @type array
   */
  items: {
    /**
     * @minLength 1
     * @type string
     */
    product_variation_id: string
    /**
     * @minLength 1
     * @type number
     */
    quantity: number
    /**
     * @minLength 0
     * @type number
     */
    discount: number
  }[]
}

export type PostOrdersMutationResponse = PostOrders201

export type PostOrdersMutation = {
  Response: PostOrders201
  Request: PostOrdersMutationRequest
  Errors: PostOrders400 | PostOrders401 | PostOrders404
}

export const getOrdersQueryParamsOrderByEnum = {
  asc: 'asc',
  desc: 'desc',
} as const

export type GetOrdersQueryParamsOrderByEnum = (typeof getOrdersQueryParamsOrderByEnum)[keyof typeof getOrdersQueryParamsOrderByEnum]

export const getOrdersQueryParamsStatusEnum = {
  PROCESSED: 'PROCESSED',
  CANCELLED: 'CANCELLED',
} as const

export type GetOrdersQueryParamsStatusEnum = (typeof getOrdersQueryParamsStatusEnum)[keyof typeof getOrdersQueryParamsStatusEnum]

export type GetOrdersQueryParams = {
  /**
   * @default "10"
   * @type string | undefined
   */
  perPage?: string
  /**
   * @default "0"
   * @type string | undefined
   */
  pageIndex?: string
  /**
   * @default "desc"
   * @type string | undefined
   */
  orderBy?: GetOrdersQueryParamsOrderByEnum
  /**
   * @type string | undefined
   */
  status?: GetOrdersQueryParamsStatusEnum
  /**
   * @type string | undefined
   */
  orderId?: string
  /**
   * @type string | undefined
   */
  platformOrderId?: string
  /**
   * @type string | undefined, date-time
   */
  timeFrom?: string
  /**
   * @type string | undefined, date-time
   */
  timeTo?: string
}

/**
 * @description Default Response
 */
export type GetOrders200 = {
  /**
   * @type number
   */
  totalCount: number
  /**
   * @type number
   */
  pageCount: number
  /**
   * @type array
   */
  orders: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    status: string
    /**
     * @type string
     */
    shipping_carrier: string
    /**
     * @type string, date-time
     */
    order_placed_at: string
    /**
     * @type string, date-time
     */
    created_at: string
    /**
     * @type string, date-time
     */
    updated_at: string
  }[]
}

export type GetOrdersQueryResponse = GetOrders200

export type GetOrdersQuery = {
  Response: GetOrders200
  QueryParams: GetOrdersQueryParams
  Errors: any
}

export type GetOrdersIdPathParams = {
  /**
   * @type string
   */
  id: string
}

/**
 * @description Detalhes do pedido obtidos com sucesso.
 */
export type GetOrdersId200 = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  status: string
  /**
   * @type string
   */
  shipping_carrier: string
  /**
   * @type string, date-time
   */
  order_placed_at: string
  /**
   * @type string, date-time
   */
  created_at: string
  /**
   * @type string, date-time
   */
  updated_at: string
  /**
   * @type string
   */
  user_id: string
  /**
   * @type string
   */
  customer_id: string
  /**
   * @type string
   */
  address_id: string
  /**
   * @type array
   */
  items: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    variation_sku: string
    /**
     * @type string
     */
    name: string
    /**
     * @type number
     */
    quantity: number
    /**
     * @type number
     */
    unit_price: number
    /**
     * @type number
     */
    unit_price_with_discount: number
    /**
     * @type string, date-time
     */
    created_at: string
    /**
     * @type string, date-time
     */
    updated_at: string
    /**
     * @type string
     */
    order_id: string
    /**
     * @type string
     */
    product_variation_id: string | null
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetOrdersId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Pedido não encontrado.
 */
export type GetOrdersId404 = {
  /**
   * @type string
   */
  message: string
}

export type GetOrdersIdQueryResponse = GetOrdersId200

export type GetOrdersIdQuery = {
  Response: GetOrdersId200
  PathParams: GetOrdersIdPathParams
  Errors: GetOrdersId401 | GetOrdersId404
}

export type PutOrdersIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const putOrdersId200Enum = {
  null: 'null',
} as const

export type PutOrdersId200Enum = (typeof putOrdersId200Enum)[keyof typeof putOrdersId200Enum]

/**
 * @description Pedido atualizado com sucesso.
 */
export type PutOrdersId200 = PutOrdersId200Enum | null

/**
 * @description Dados inválidos.
 */
export type PutOrdersId400 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Usuário não autenticado.
 */
export type PutOrdersId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Pedido não encontrado.
 */
export type PutOrdersId404 = {
  /**
   * @type string
   */
  message: string
}

export const putOrdersIdMutationRequestStatusEnum = {
  PROCESSED: 'PROCESSED',
  CANCELLED: 'CANCELLED',
} as const

export type PutOrdersIdMutationRequestStatusEnum = (typeof putOrdersIdMutationRequestStatusEnum)[keyof typeof putOrdersIdMutationRequestStatusEnum]

export const putOrdersIdMutationRequestShippingCarrierEnum = {
  CORREIOS: 'CORREIOS',
  JADLOG: 'JADLOG',
} as const

export type PutOrdersIdMutationRequestShippingCarrierEnum =
  (typeof putOrdersIdMutationRequestShippingCarrierEnum)[keyof typeof putOrdersIdMutationRequestShippingCarrierEnum]

export const putOrdersIdMutationRequestPaymentMethodEnum = {
  CREDIT_CARD: 'CREDIT_CARD',
  DEBIT_CARD: 'DEBIT_CARD',
  PIX: 'PIX',
} as const

export type PutOrdersIdMutationRequestPaymentMethodEnum =
  (typeof putOrdersIdMutationRequestPaymentMethodEnum)[keyof typeof putOrdersIdMutationRequestPaymentMethodEnum]

export type PutOrdersIdMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  customer_id: string
  /**
   * @minLength 1
   * @type string
   */
  address_id: string
  /**
   * @default "PROCESSED"
   * @type string | undefined
   */
  status?: PutOrdersIdMutationRequestStatusEnum
  /**
   * @default "CORREIOS"
   * @type string | undefined
   */
  shipping_carrier?: PutOrdersIdMutationRequestShippingCarrierEnum
  /**
   * @type string
   */
  payment_method: PutOrdersIdMutationRequestPaymentMethodEnum
  /**
   * @minLength 0
   * @default 0
   * @type number | undefined
   */
  shipping_cost?: number
  /**
   * @type array
   */
  items: {
    /**
     * @minLength 1
     * @type string
     */
    product_variation_id: string
    /**
     * @minLength 1
     * @type number
     */
    quantity: number
    /**
     * @minLength 0
     * @type number
     */
    discount: number
  }[]
  /**
   * @description Retornar itens do pedido anterior ao estoque
   * @default true
   * @type boolean | undefined
   */
  return_previous_items_to_stock?: boolean
  /**
   * @description Remover itens do novo pedido do estoque
   * @default true
   * @type boolean | undefined
   */
  remove_current_items_from_stock?: boolean
}

export type PutOrdersIdMutationResponse = PutOrdersId200

export type PutOrdersIdMutation = {
  Response: PutOrdersId200
  Request: PutOrdersIdMutationRequest
  PathParams: PutOrdersIdPathParams
  Errors: PutOrdersId400 | PutOrdersId401 | PutOrdersId404
}

export type DeleteOrdersIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const deleteOrdersId200Enum = {
  null: 'null',
} as const

export type DeleteOrdersId200Enum = (typeof deleteOrdersId200Enum)[keyof typeof deleteOrdersId200Enum]

/**
 * @description Pedido deletado com sucesso.
 */
export type DeleteOrdersId200 = DeleteOrdersId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteOrdersId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Pedido não encontrado.
 */
export type DeleteOrdersId404 = {
  /**
   * @type string
   */
  message: string
}

export type DeleteOrdersIdMutationResponse = DeleteOrdersId200

export type DeleteOrdersIdMutation = {
  Response: DeleteOrdersId200
  PathParams: DeleteOrdersIdPathParams
  Errors: DeleteOrdersId401 | DeleteOrdersId404
}

/**
 * @description Default Response
 */
export type GetShopeeAuthUrl200 = {
  /**
   * @type string
   */
  url: string
}

/**
 * @description Usuário não autenticado.
 */
export type GetShopeeAuthUrl401 = {
  /**
   * @type string
   */
  message: string
}

export type GetShopeeAuthUrlQueryResponse = GetShopeeAuthUrl200

export type GetShopeeAuthUrlQuery = {
  Response: GetShopeeAuthUrl200
  Errors: GetShopeeAuthUrl401
}

export const postShopeeAuthToken200Enum = {
  null: 'null',
} as const

export type PostShopeeAuthToken200Enum = (typeof postShopeeAuthToken200Enum)[keyof typeof postShopeeAuthToken200Enum]

/**
 * @description Shopee authenticated.
 */
export type PostShopeeAuthToken200 = PostShopeeAuthToken200Enum | null

/**
 * @description Shopee already exists.
 */
export type PostShopeeAuthToken400 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Usuário não autenticado.
 */
export type PostShopeeAuthToken401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Connection not found.
 */
export type PostShopeeAuthToken404 = {
  /**
   * @type string
   */
  message: string
}

export type PostShopeeAuthTokenMutationRequest = {
  /**
   * @type string
   */
  code: string
  /**
   * @type number
   */
  shopId: number
}

export type PostShopeeAuthTokenMutationResponse = PostShopeeAuthToken200

export type PostShopeeAuthTokenMutation = {
  Response: PostShopeeAuthToken200
  Request: PostShopeeAuthTokenMutationRequest
  Errors: PostShopeeAuthToken400 | PostShopeeAuthToken401 | PostShopeeAuthToken404
}

export type PostShopeeOrderImportQueryParams = {
  /**
   * @type string
   */
  orderPeriodStartDate: string
  /**
   * @type string
   */
  orderPeriodEndDate: string
}

export const postShopeeOrderImport200Enum = {
  null: 'null',
} as const

export type PostShopeeOrderImport200Enum = (typeof postShopeeOrderImport200Enum)[keyof typeof postShopeeOrderImport200Enum]

/**
 * @description Pedidos importados com sucesso.
 */
export type PostShopeeOrderImport200 = PostShopeeOrderImport200Enum | null

/**
 * @description Erro ao importar pedidos.
 */
export type PostShopeeOrderImport400 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Usuário não autenticado.
 */
export type PostShopeeOrderImport401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Connection not found.
 */
export type PostShopeeOrderImport404 = {
  /**
   * @type string
   */
  message: string
}

export type PostShopeeOrderImportMutationResponse = PostShopeeOrderImport200

export type PostShopeeOrderImportMutation = {
  Response: PostShopeeOrderImport200
  QueryParams: PostShopeeOrderImportQueryParams
  Errors: PostShopeeOrderImport400 | PostShopeeOrderImport401 | PostShopeeOrderImport404
}

/**
 * @description Default Response
 */
export type PostShopeeDownloadShippingDocument200 = any

export type PostShopeeDownloadShippingDocumentMutationResponse = PostShopeeDownloadShippingDocument200

export type PostShopeeDownloadShippingDocumentMutation = {
  Response: PostShopeeDownloadShippingDocument200
  Errors: any
}