/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type { PostShopeeDownloadShippingDocumentMutationResponse } from './models.ts'

function getPostShopeeDownloadShippingDocumentUrl() {
  return `/shopee/download/shipping-document` as const
}

/**
 * {@link /shopee/download/shipping-document}
 */
export async function postShopeeDownloadShippingDocument(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PostShopeeDownloadShippingDocumentMutationResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'POST',
    url: getPostShopeeDownloadShippingDocumentUrl().toString(),
    ...requestConfig,
  })
  return res.data
}