/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  PostProductsVariationsMutationRequest,
  PostProductsVariationsMutationResponse,
  PostProductsVariations401,
  PostProductsVariations409,
} from './models.ts'

function getPostProductsVariationsUrl() {
  return `/products/variations` as const
}

/**
 * @description Esta rota permite o cadastro de variações de produtos no sistema. Uma variação representa uma versão específica de um produto base, podendo ter características únicas como tamanho, cor, modelo, material ou outras especificações. Cada variação pode ter seu próprio preço, código SKU e controle de estoque independente. O acesso a esta funcionalidade requer autenticação prévia através de token JWT válido. As variações cadastradas podem ser posteriormente consultadas, atualizadas ou removidas através das demais rotas disponíveis.
 * @summary Cadastra uma nova variação de produto.
 * {@link /products/variations}
 */
export async function postProductsVariations(
  data: PostProductsVariationsMutationRequest,
  config: Partial<RequestConfig<PostProductsVariationsMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    PostProductsVariationsMutationResponse,
    ResponseErrorConfig<PostProductsVariations401 | PostProductsVariations409>,
    PostProductsVariationsMutationRequest
  >({ method: 'POST', url: getPostProductsVariationsUrl().toString(), data, ...requestConfig })
  return res.data
}