/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  PostShopeeAuthTokenMutationRequestType,
  PostShopeeAuthTokenMutationResponseType,
  PostShopeeAuthToken400Type,
  PostShopeeAuthToken401Type,
  PostShopeeAuthToken404Type,
} from './types/PostShopeeAuthTokenType.ts'

function getPostShopeeAuthTokenUrl() {
  return `/shopee/auth/token` as const
}

/**
 * @description Realiza a autenticação e vinculação de uma conta Shopee ao sistema através do código de autorização obtido no processo de autenticação. Este endpoint processa o código recebido e estabelece as credenciais necessárias para futuras interações com a API da Shopee.
 * @summary Realiza autenticação e vinculação da conta Shopee ao sistema.
 * {@link /shopee/auth/token}
 */
export async function postShopeeAuthToken(
  data: PostShopeeAuthTokenMutationRequestType,
  config: Partial<RequestConfig<PostShopeeAuthTokenMutationRequestType>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    PostShopeeAuthTokenMutationResponseType,
    ResponseErrorConfig<PostShopeeAuthToken400Type | PostShopeeAuthToken401Type | PostShopeeAuthToken404Type>,
    PostShopeeAuthTokenMutationRequestType
  >({ method: 'POST', url: getPostShopeeAuthTokenUrl().toString(), data, ...requestConfig })
  return res.data
}