/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  PostProductsCategoriesMutationRequest,
  PostProductsCategoriesMutationResponse,
  PostProductsCategories401,
  PostProductsCategories409,
} from './models.ts'

function getPostProductsCategoriesUrl() {
  return `/products/categories` as const
}

/**
 * @description Esta rota permite o cadastro de uma nova categoria de produto no sistema. A categoria criada poderá ser utilizada para classificar e organizar produtos de forma eficiente no catálogo. É necessário fornecer um nome único para a categoria, garantindo que não existam duplicatas. A categorização adequada facilita a busca e filtragem de produtos tanto para gestão interna quanto para exibição aos clientes.
 * @summary Cadastra uma nova categoria de produto.
 * {@link /products/categories}
 */
export async function postProductsCategories(
  data: PostProductsCategoriesMutationRequest,
  config: Partial<RequestConfig<PostProductsCategoriesMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    PostProductsCategoriesMutationResponse,
    ResponseErrorConfig<PostProductsCategories401 | PostProductsCategories409>,
    PostProductsCategoriesMutationRequest
  >({ method: 'POST', url: getPostProductsCategoriesUrl().toString(), data, ...requestConfig })
  return res.data
}