/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  PostProductsAttributesNamesMutationRequest,
  PostProductsAttributesNamesMutationResponse,
  PostProductsAttributesNames401,
  PostProductsAttributesNames409,
} from './models.ts'

function getPostProductsAttributesNamesUrl() {
  return `/products/attributes/names` as const
}

/**
 * @description O nome do atributo é uma característica que pode ser associada a diferentes produtos, como por exemplo "Cor", "Tamanho", "Material", etc. Este registro é necessário antes de cadastrar valores específicos para cada atributo.
 * @summary Registra um novo nome de atributo de produto.
 * {@link /products/attributes/names}
 */
export async function postProductsAttributesNames(
  data: PostProductsAttributesNamesMutationRequest,
  config: Partial<RequestConfig<PostProductsAttributesNamesMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    PostProductsAttributesNamesMutationResponse,
    ResponseErrorConfig<PostProductsAttributesNames401 | PostProductsAttributesNames409>,
    PostProductsAttributesNamesMutationRequest
  >({ method: 'POST', url: getPostProductsAttributesNamesUrl().toString(), data, ...requestConfig })
  return res.data
}