/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type { PutCustomersIdMutationRequest, PutCustomersIdMutationResponse, PutCustomersIdPathParams, PutCustomersId401, PutCustomersId404 } from './models.ts'

function getPutCustomersIdUrl(id: PutCustomersIdPathParams['id']) {
  return `/customers/${id}` as const
}

/**
 * @description Esta rota permite atualizar as informações de um cliente específico no sistema. É necessário fornecer o ID do cliente como parâmetro na URL e os dados a serem atualizados no corpo da requisição. Os campos disponíveis para atualização incluem nome, documento (CPF/CNPJ), endereço e informações de contato. Todos os dados fornecidos serão validados antes da atualização. As informações anteriores do cliente serão substituídas pelos novos dados fornecidos. Requer autenticação através de um token JWT válido no cabeçalho da requisição.
 * @summary Altera as informações de um cliente específico.
 * {@link /customers/:id}
 */
export async function putCustomersId(
  id: PutCustomersIdPathParams['id'],
  data: PutCustomersIdMutationRequest,
  config: Partial<RequestConfig<PutCustomersIdMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PutCustomersIdMutationResponse, ResponseErrorConfig<PutCustomersId401 | PutCustomersId404>, PutCustomersIdMutationRequest>({
    method: 'PUT',
    url: getPutCustomersIdUrl(id).toString(),
    data,
    ...requestConfig,
  })
  return res.data
}