/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  PutOrdersIdMutationRequest,
  PutOrdersIdMutationResponse,
  PutOrdersIdPathParams,
  PutOrdersId400,
  PutOrdersId401,
  PutOrdersId404,
} from './models.ts'

function getPutOrdersIdUrl(id: PutOrdersIdPathParams['id']) {
  return `/orders/${id}` as const
}

/**
 * @description Permite a modificação de informações de um pedido existente, como dados do cliente, itens, quantidades, valores e status. É necessário fornecer o ID do pedido na URL e os dados atualizados no corpo da requisição. O sistema recalculará automaticamente os valores totais e impostos aplicáveis. Requer autenticação através de um token JWT válido no cabeçalho da requisição.
 * @summary Altera as informações de um pedido existente.
 * {@link /orders/:id}
 */
export async function putOrdersId(
  id: PutOrdersIdPathParams['id'],
  data: PutOrdersIdMutationRequest,
  config: Partial<RequestConfig<PutOrdersIdMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PutOrdersIdMutationResponse, ResponseErrorConfig<PutOrdersId400 | PutOrdersId401 | PutOrdersId404>, PutOrdersIdMutationRequest>({
    method: 'PUT',
    url: getPutOrdersIdUrl(id).toString(),
    data,
    ...requestConfig,
  })
  return res.data
}