/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  PutProductsVariationsIdMutationRequest,
  PutProductsVariationsIdMutationResponse,
  PutProductsVariationsIdPathParams,
  PutProductsVariationsId401,
  PutProductsVariationsId404,
} from './models.ts'

function getPutProductsVariationsIdUrl(id: PutProductsVariationsIdPathParams['id']) {
  return `/products/variations/${id}` as const
}

/**
 * @description Esta rota permite a modificação das informações de uma variação específica de produto através do seu ID. É possível atualizar dados como preço, SKU, estoque, características específicas (tamanho, cor, modelo, etc.) e outras informações relevantes da variação. As alterações são aplicadas mantendo o histórico e integridade dos dados. O acesso a esta funcionalidade requer autenticação prévia através de token JWT válido.
 * @summary Altera as informações de uma variação de produto.
 * {@link /products/variations/:id}
 */
export async function putProductsVariationsId(
  id: PutProductsVariationsIdPathParams['id'],
  data: PutProductsVariationsIdMutationRequest,
  config: Partial<RequestConfig<PutProductsVariationsIdMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    PutProductsVariationsIdMutationResponse,
    ResponseErrorConfig<PutProductsVariationsId401 | PutProductsVariationsId404>,
    PutProductsVariationsIdMutationRequest
  >({ method: 'PUT', url: getPutProductsVariationsIdUrl(id).toString(), data, ...requestConfig })
  return res.data
}