/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Marcas de produtos obtidas com sucesso.
 */
export type GetProductsBrands200Type = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  reference_code: string
}[]

/**
 * @description Usuário não autenticado.
 */
export type GetProductsBrands401Type = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsBrandsQueryResponseType = GetProductsBrands200Type

export type GetProductsBrandsTypeQuery = {
  Response: GetProductsBrands200Type
  Errors: GetProductsBrands401Type
}
