/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from '@kubb/plugin-zod/utils'
import { z } from 'zod'
import type {
  DeleteCustomersId200Type,
  DeleteCustomersId401Type,
  DeleteCustomersId404Type,
  DeleteCustomersIdMutationResponseType,
  DeleteCustomersIdPathParamsType,
} from '../../types/ClientesTypes/DeleteCustomersIdType'

export const deleteCustomersIdPathParamsSchema = z.object({
  id: z.string(),
}) as unknown as ToZod<DeleteCustomersIdPathParamsType>

/**
 * @description Cliente deletado com sucesso.
 */
export const deleteCustomersId200Schema = z
  .enum(['null'])
  .describe('Cliente deletado com sucesso.')
  .nullable() as unknown as ToZod<DeleteCustomersId200Type>

/**
 * @description Usuário não autenticado.
 */
export const deleteCustomersId401Schema = z
  .object({
    message: z.string(),
  })
  .describe(
    'Usuário não autenticado.'
  ) as unknown as ToZod<DeleteCustomersId401Type>

/**
 * @description Cliente não encontrado.
 */
export const deleteCustomersId404Schema = z
  .object({
    message: z.string(),
  })
  .describe(
    'Cliente não encontrado.'
  ) as unknown as ToZod<DeleteCustomersId404Type>

export const deleteCustomersIdMutationResponseSchema = z.lazy(
  () => deleteCustomersId200Schema
) as unknown as ToZod<DeleteCustomersIdMutationResponseType>
