/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  DeleteProductsCategoriesIdMutationResponseType,
  DeleteProductsCategoriesIdPathParamsType,
  DeleteProductsCategoriesId401Type,
  DeleteProductsCategoriesId404Type,
} from '../types/Produtos (Categorias)Types/DeleteProductsCategoriesIdType.ts'

function getDeleteProductsCategoriesIdUrl(
  id: DeleteProductsCategoriesIdPathParamsType['id']
) {
  return `/products/categories/${id}` as const
}

/**
 * @description Esta rota permite a remoção de uma categoria de produto específica do sistema. A operação é irreversível e requer o ID da categoria como parâmetro. É importante verificar se a categoria não está sendo utilizada por nenhum produto antes da remoção para evitar inconsistências no sistema. A remoção de categorias deve ser realizada com cautela, pois pode impactar a organização e classificação dos produtos existentes.
 * @summary Remove uma categoria de produto específica.
 * {@link /products/categories/:id}
 */
export async function deleteProductsCategoriesId(
  id: DeleteProductsCategoriesIdPathParamsType['id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    DeleteProductsCategoriesIdMutationResponseType,
    ResponseErrorConfig<
      DeleteProductsCategoriesId401Type | DeleteProductsCategoriesId404Type
    >,
    unknown
  >({
    method: 'DELETE',
    url: getDeleteProductsCategoriesIdUrl(id).toString(),
    ...requestConfig,
  })
  return res.data
}
