/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  DeleteProductsAttributesNamesIdMutationResponseType,
  DeleteProductsAttributesNamesIdPathParamsType,
  DeleteProductsAttributesNamesId401Type,
  DeleteProductsAttributesNamesId404Type,
} from '../types/products/DeleteProductsAttributesNamesIdType'

function getDeleteProductsAttributesNamesIdUrl(id: DeleteProductsAttributesNamesIdPathParamsType['id']) {
  return `http://localhost:3333/products/attributes/names/${id}` as const
}

/**
 * @description Esta rota permite remover um nome de atributo de produto específico do sistema. É necessário fornecer o ID do nome do atributo como parâmetro na URL. O sistema verifica se o nome do atributo não está sendo utilizado em produtos ativos antes de realizar a remoção. A remoção de um nome de atributo também remove automaticamente todos os valores de atributo associados a ele. Esta operação é irreversível.
 * @summary Remove um nome de atributo de produto específico.
 * {@link /products/attributes/names/:id}
 */
export async function deleteProductsAttributesNamesId(
  id: DeleteProductsAttributesNamesIdPathParamsType['id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    DeleteProductsAttributesNamesIdMutationResponseType,
    ResponseErrorConfig<DeleteProductsAttributesNamesId401Type | DeleteProductsAttributesNamesId404Type>,
    unknown
  >({ method: 'DELETE', url: getDeleteProductsAttributesNamesIdUrl(id).toString(), ...requestConfig })
  return res.data
}