/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from './src/http/client.ts'
import type { RequestConfig, ResponseErrorConfig } from './src/http/client.ts'
import type {
  DeleteProductsVariationsIdMutationResponse,
  DeleteProductsVariationsIdPathParams,
  DeleteProductsVariationsId401,
  DeleteProductsVariationsId404,
} from '../types/DeleteProductsVariationsId.ts'

function getDeleteProductsVariationsIdUrl({ id }: { id: DeleteProductsVariationsIdPathParams['id'] }) {
  return `http://localhost:3333/products/variations/${id}` as const
}

/**
 * @description Esta rota permite a remoção de uma variação específica de produto através do seu ID. A exclusão é permanente e remove todos os dados associados à variação, incluindo histórico de estoque, preços e características específicas. É importante notar que esta operação não pode ser desfeita e deve ser utilizada com cautela. A remoção de uma variação não afeta o produto base ou outras variações existentes. O acesso a esta funcionalidade requer autenticação prévia através de token JWT válido.
 * @summary Remove uma variação de produto.
 * {@link /products/variations/:id}
 */
export async function deleteProductsVariationsId(
  { id }: { id: DeleteProductsVariationsIdPathParams['id'] },
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    DeleteProductsVariationsIdMutationResponse,
    ResponseErrorConfig<DeleteProductsVariationsId401 | DeleteProductsVariationsId404>,
    unknown
  >({ method: 'DELETE', url: getDeleteProductsVariationsIdUrl({ id }).toString(), ...requestConfig })
  return res.data
}