/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from './src/http/client.ts'
import type { RequestConfig, ResponseErrorConfig } from './src/http/client.ts'
import type { DeleteCustomersIdMutationResponse, DeleteCustomersIdPathParams, DeleteCustomersId401, DeleteCustomersId404 } from '../types/DeleteCustomersId.ts'

function getDeleteCustomersIdUrl({ id }: { id: DeleteCustomersIdPathParams['id'] }) {
  return `http://localhost:3333/customers/${id}` as const
}

/**
 * @description Esta rota permite remover permanentemente um cliente específico do sistema com base no ID fornecido. A remoção é irreversível e todos os dados associados ao cliente serão excluídos. É necessário fornecer o ID do cliente como parâmetro na URL. Por questões de segurança, requer autenticação através de um token JWT válido no cabeçalho da requisição.
 * @summary Remove um cliente específico.
 * {@link /customers/:id}
 */
export async function deleteCustomersId({ id }: { id: DeleteCustomersIdPathParams['id'] }, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<DeleteCustomersIdMutationResponse, ResponseErrorConfig<DeleteCustomersId401 | DeleteCustomersId404>, unknown>({
    method: 'DELETE',
    url: getDeleteCustomersIdUrl({ id }).toString(),
    ...requestConfig,
  })
  return res.data
}