/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from './src/http/client.ts'
import type { RequestConfig, ResponseErrorConfig } from './src/http/client.ts'
import type { DeleteOrdersIdMutationResponse, DeleteOrdersIdPathParams, DeleteOrdersId401, DeleteOrdersId404 } from '../types/DeleteOrdersId.ts'

function getDeleteOrdersIdUrl({ id }: { id: DeleteOrdersIdPathParams['id'] }) {
  return `http://localhost:3333/orders/${id}` as const
}

/**
 * @description Remove permanentemente um pedido específico do sistema. Esta operação não pode ser desfeita e só deve ser utilizada em casos específicos, como correção de erros de cadastro. Para pedidos que precisam ser cancelados mas mantidos no histórico, utilize a alteração de status ao invés da remoção. É necessário fornecer o ID do pedido como parâmetro na URL. Requer autenticação através de um token JWT válido no cabeçalho da requisição.
 * @summary Remove um pedido existente.
 * {@link /orders/:id}
 */
export async function deleteOrdersId({ id }: { id: DeleteOrdersIdPathParams['id'] }, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<DeleteOrdersIdMutationResponse, ResponseErrorConfig<DeleteOrdersId401 | DeleteOrdersId404>, unknown>({
    method: 'DELETE',
    url: getDeleteOrdersIdUrl({ id }).toString(),
    ...requestConfig,
  })
  return res.data
}