/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  DeleteProductsAttributesValuesId401Type,
  DeleteProductsAttributesValuesId404Type,
  DeleteProductsAttributesValuesIdMutationResponseType,
  DeleteProductsAttributesValuesIdPathParamsType,
} from '../types/Produtos (Atributos)Types/DeleteProductsAttributesValuesIdType.ts'

function getDeleteProductsAttributesValuesIdUrl(
  id: DeleteProductsAttributesValuesIdPathParamsType['id']
) {
  return `/products/attributes/values/${id}` as const
}

/**
 * @description Esta rota permite remover um valor de atributo de produto específico do sistema. É necessário fornecer o ID do valor do atributo como parâmetro na URL. O sistema verifica se o valor do atributo não está sendo utilizado em produtos ativos antes de realizar a remoção. Esta operação é irreversível e deve ser utilizada com cautela, pois pode afetar o histórico de produtos que utilizaram este valor de atributo.
 * @summary Remove um valor de atributo de produto específico.
 * {@link /products/attributes/values/:id}
 */
export async function deleteProductsAttributesValuesId(
  id: DeleteProductsAttributesValuesIdPathParamsType['id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    DeleteProductsAttributesValuesIdMutationResponseType,
    ResponseErrorConfig<
      | DeleteProductsAttributesValuesId401Type
      | DeleteProductsAttributesValuesId404Type
    >,
    unknown
  >({
    method: 'DELETE',
    url: getDeleteProductsAttributesValuesIdUrl(id).toString(),
    ...requestConfig,
  })
  return res.data
}
