/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  DeleteEmployeesIdMutationResponseType,
  DeleteEmployeesIdPathParamsType,
  DeleteEmployeesId401Type,
  DeleteEmployeesId404Type,
} from '../types/employees/DeleteEmployeesIdType'

function getDeleteEmployeesIdUrl({ id }: { id: DeleteEmployeesIdPathParamsType['id'] }) {
  return `http://localhost:3333/employees/${id}` as const
}

/**
 * @description Requer autenticação via token JWT para garantir acesso seguro. Permite a remoção de um colaborador específico do sistema através do seu ID, que deve ser fornecido como parâmetro na URL. A operação é irreversível e remove todos os dados associados ao colaborador. A rota verifica a existência do colaborador antes de realizar a remoção e garante que apenas usuários autorizados possam executar esta ação. Após a remoção bem-sucedida, o sistema retorna uma confirmação da operação.
 * @summary Remove um colaborador específico.
 * {@link /employees/:id}
 */
export async function deleteEmployeesId(
  { id }: { id: DeleteEmployeesIdPathParamsType['id'] },
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<DeleteEmployeesIdMutationResponseType, ResponseErrorConfig<DeleteEmployeesId401Type | DeleteEmployeesId404Type>, unknown>({
    method: 'DELETE',
    url: getDeleteEmployeesIdUrl({ id }).toString(),
    ...requestConfig,
  })
  return res.data
}