/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  DeleteProductsIdMutationResponseType,
  DeleteProductsIdPathParamsType,
  DeleteProductsId401Type,
  DeleteProductsId404Type,
} from '../types/products/DeleteProductsIdType'

function getDeleteProductsIdUrl({ id }: { id: DeleteProductsIdPathParamsType['id'] }) {
  return `http://localhost:3333/products/${id}` as const
}

/**
 * @description Esta rota requer autenticação através de um token JWT válido. Permite a remoção de um produto específico do sistema com base no ID fornecido nos parâmetros da URL. A operação é irreversível e todos os dados associados ao produto serão permanentemente excluídos. É importante notar que esta ação não pode ser desfeita após a confirmação. Caso o produto não seja encontrado, será retornado um erro apropriado.
 * @summary Remove um produto específico.
 * {@link /products/:id}
 */
export async function deleteProductsId({ id }: { id: DeleteProductsIdPathParamsType['id'] }, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<DeleteProductsIdMutationResponseType, ResponseErrorConfig<DeleteProductsId401Type | DeleteProductsId404Type>, unknown>({
    method: 'DELETE',
    url: getDeleteProductsIdUrl({ id }).toString(),
    ...requestConfig,
  })
  return res.data
}