/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  GetCustomersQueryResponseType,
  GetCustomersQueryParamsType,
  GetCustomers401Type,
  GetCustomers404Type,
} from '../types/customers/GetCustomersType'

function getGetCustomersUrl() {
  return 'http://localhost:3333/customers' as const
}

/**
 * @description Esta rota retorna uma lista paginada de todos os clientes cadastrados no sistema. É possível filtrar os resultados por nome, documento (CPF/CNPJ) e status do cliente. A resposta inclui informações básicas de cada cliente, como ID, nome, documento e data de cadastro. Os resultados podem ser ordenados por diferentes campos e a quantidade de itens por página pode ser personalizada. Requer autenticação através de um token JWT válido no cabeçalho da requisição.
 * @summary Retorna uma lista de clientes castrados.
 * {@link /customers}
 */
export async function getCustomers({ params }: { params?: GetCustomersQueryParamsType }, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetCustomersQueryResponseType, ResponseErrorConfig<GetCustomers401Type | GetCustomers404Type>, unknown>({
    method: 'GET',
    url: getGetCustomersUrl().toString(),
    params,
    ...requestConfig,
  })
  return res.data
}