/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  GetCustomersIdQueryResponseType,
  GetCustomersIdPathParamsType,
  GetCustomersId401Type,
  GetCustomersId404Type,
} from '../types/ClientesTypes/GetCustomersIdType.ts'

function getGetCustomersIdUrl(id: GetCustomersIdPathParamsType['id']) {
  return `/customers/${id}` as const
}

/**
 * @description Esta rota retorna informações detalhadas de um cliente específico com base no ID fornecido. Os dados retornados incluem todas as informações do cliente, como nome completo, documento (CPF/CNPJ), endereço completo, informações de contato, data de cadastro e última atualização. É necessário fornecer o ID do cliente como parâmetro na URL. Requer autenticação através de um token JWT válido no cabeçalho da requisição.
 * @summary Retorna informações de um cliente específico.
 * {@link /customers/:id}
 */
export async function getCustomersId(
  id: GetCustomersIdPathParamsType['id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    GetCustomersIdQueryResponseType,
    ResponseErrorConfig<GetCustomersId401Type | GetCustomersId404Type>,
    unknown
  >({
    method: 'GET',
    url: getGetCustomersIdUrl(id).toString(),
    ...requestConfig,
  })
  return res.data
}
