/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from './src/http/client.ts'
import type { RequestConfig, ResponseErrorConfig } from './src/http/client.ts'
import type { GetCustomersIdQueryResponse, GetCustomersIdPathParams, GetCustomersId401, GetCustomersId404 } from '../types/GetCustomersId.ts'

function getGetCustomersIdUrl({ id }: { id: GetCustomersIdPathParams['id'] }) {
  return `http://localhost:3333/customers/${id}` as const
}

/**
 * @description Esta rota retorna informações detalhadas de um cliente específico com base no ID fornecido. Os dados retornados incluem todas as informações do cliente, como nome completo, documento (CPF/CNPJ), endereço completo, informações de contato, data de cadastro e última atualização. É necessário fornecer o ID do cliente como parâmetro na URL. Requer autenticação através de um token JWT válido no cabeçalho da requisição.
 * @summary Retorna informações de um cliente específico.
 * {@link /customers/:id}
 */
export async function getCustomersId({ id }: { id: GetCustomersIdPathParams['id'] }, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetCustomersIdQueryResponse, ResponseErrorConfig<GetCustomersId401 | GetCustomersId404>, unknown>({
    method: 'GET',
    url: getGetCustomersIdUrl({ id }).toString(),
    ...requestConfig,
  })
  return res.data
}