/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type { GetOrdersIdQueryResponseType, GetOrdersIdPathParamsType, GetOrdersId401Type, GetOrdersId404Type } from '../types/PedidosTypes/GetOrdersIdType'

function getGetOrdersIdUrl(id: GetOrdersIdPathParamsType['id']) {
  return `/orders/${id}` as const
}

/**
 * @description Retorna informações detalhadas de um pedido específico, incluindo dados do cliente, itens do pedido, valores, status de pagamento e entrega. É necessário fornecer o ID do pedido como parâmetro na URL. Requer autenticação através de um token JWT válido no cabeçalho da requisição.
 * @summary Retorna informações detalhadas de um pedido específico.
 * {@link /orders/:id}
 */
export async function getOrdersId(id: GetOrdersIdPathParamsType['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetOrdersIdQueryResponseType, ResponseErrorConfig<GetOrdersId401Type | GetOrdersId404Type>, unknown>({
    method: 'GET',
    url: getGetOrdersIdUrl(id).toString(),
    ...requestConfig,
  })
  return res.data
}