/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from './src/http/client.ts'
import type { RequestConfig, ResponseErrorConfig } from './src/http/client.ts'
import type { GetOrdersQueryResponse, GetOrdersQueryParams } from '../types/GetOrders.ts'

function getGetOrdersUrl() {
  return `http://localhost:3333/orders` as const
}

/**
 * @description Lista todos os pedidos cadastrados no sistema. Permite filtrar por data, status, cliente e outros parâmetros. Os resultados são paginados e podem ser ordenados por diferentes critérios. É necessário um token JWT válido no cabeçalho da requisição para autenticação.
 * @summary Retorna uma lista de pedidos.
 * {@link /orders}
 */
export async function getOrders({ params }: { params?: GetOrdersQueryParams }, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetOrdersQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: getGetOrdersUrl().toString(),
    params,
    ...requestConfig,
  })
  return res.data
}