/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from './src/http/client.ts'
import type { RequestConfig, ResponseErrorConfig } from './src/http/client.ts'
import type { GetOrdersIdQueryResponse, GetOrdersIdPathParams, GetOrdersId401, GetOrdersId404 } from '../types/GetOrdersId.ts'

function getGetOrdersIdUrl({ id }: { id: GetOrdersIdPathParams['id'] }) {
  return `http://localhost:3333/orders/${id}` as const
}

/**
 * @description Retorna informações detalhadas de um pedido específico, incluindo dados do cliente, itens do pedido, valores, status de pagamento e entrega. É necessário fornecer o ID do pedido como parâmetro na URL. Requer autenticação através de um token JWT válido no cabeçalho da requisição.
 * @summary Retorna informações detalhadas de um pedido específico.
 * {@link /orders/:id}
 */
export async function getOrdersId({ id }: { id: GetOrdersIdPathParams['id'] }, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetOrdersIdQueryResponse, ResponseErrorConfig<GetOrdersId401 | GetOrdersId404>, unknown>({
    method: 'GET',
    url: getGetOrdersIdUrl({ id }).toString(),
    ...requestConfig,
  })
  return res.data
}