/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type { GetOrdersQueryResponseType, GetOrdersQueryParamsType, GetOrders401Type } from '../types/orders/GetOrdersType'

function getGetOrdersUrl() {
  return 'http://localhost:3333/orders' as const
}

/**
 * @description Lista todos os pedidos cadastrados no sistema. Permite filtrar por data, status, cliente e outros parâmetros. Os resultados são paginados e podem ser ordenados por diferentes critérios. É necessário um token JWT válido no cabeçalho da requisição para autenticação.
 * @summary Retorna uma lista de pedidos.
 * {@link /orders}
 */
export async function getOrders({ params }: { params?: GetOrdersQueryParamsType }, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetOrdersQueryResponseType, ResponseErrorConfig<GetOrders401Type>, unknown>({
    method: 'GET',
    url: getGetOrdersUrl().toString(),
    params,
    ...requestConfig,
  })
  return res.data
}