/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  GetProductsBrands401Type,
  GetProductsBrandsQueryResponseType,
} from '../types/Produtos (Marcas)Types/GetProductsBrandsType.ts'

function getGetProductsBrandsUrl() {
  return '/products/brands' as const
}

/**
 * @description Esta rota requer autenticação via JWT (JSON Web Token) para garantir a segurança do acesso. Fornece uma listagem completa das marcas cadastradas no sistema, incluindo seus identificadores únicos, nomes e descrições. A consulta permite visualizar todas as marcas disponíveis para associação com produtos, facilitando a gestão e organização do catálogo. Os dados retornados podem ser utilizados para diversos fins, como preenchimento de formulários de cadastro de produtos, relatórios gerenciais e análises de portfólio.
 * @summary Retorna uma lista de marcas cadastradas.
 * {@link /products/brands}
 */
export async function getProductsBrands(
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    GetProductsBrandsQueryResponseType,
    ResponseErrorConfig<GetProductsBrands401Type>,
    unknown
  >({
    method: 'GET',
    url: getGetProductsBrandsUrl().toString(),
    ...requestConfig,
  })
  return res.data
}
