/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  GetProductsMeasurementUnitsQueryResponseType,
  GetProductsMeasurementUnits401Type,
} from '../types/Produtos (Unidades de Medida)Types/GetProductsMeasurementUnitsType'

function getGetProductsMeasurementUnitsUrl() {
  return '/products/measurement-units' as const
}

/**
 * @description Retorna uma lista completa de todas as unidades de medida disponíveis para produtos no sistema. Essas unidades de medida são utilizadas para definir as quantidades e dimensões dos produtos cadastrados. A listagem inclui unidades como quilogramas, litros, metros, entre outras medidas padrão.
 * @summary Retorna uma lista de unidades de medida de produtos.
 * {@link /products/measurement-units}
 */
export async function getProductsMeasurementUnits(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetProductsMeasurementUnitsQueryResponseType, ResponseErrorConfig<GetProductsMeasurementUnits401Type>, unknown>({
    method: 'GET',
    url: getGetProductsMeasurementUnitsUrl().toString(),
    ...requestConfig,
  })
  return res.data
}