/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  GetProductsVariationsQueryResponseType,
  GetProductsVariationsQueryParamsType,
  GetProductsVariations401Type,
  GetProductsVariations404Type,
} from '../types/Produtos (Varia\u00E7\u00F5es)Types/GetProductsVariationsType'

function getGetProductsVariationsUrl() {
  return '/products/variations' as const
}

/**
 * @description Esta rota permite a listagem de todas as variações de produtos cadastradas no sistema. As variações são versões específicas dos produtos base, contendo informações como preço, SKU, estoque e características únicas (tamanho, cor, modelo, etc.). A listagem pode ser filtrada e paginada através dos parâmetros de consulta disponíveis. Os resultados incluem detalhes completos de cada variação, permitindo uma visão abrangente do catálogo de produtos. O acesso a esta funcionalidade requer autenticação prévia através de token JWT válido.
 * @summary Retorna uma lista de variações de produtos.
 * {@link /products/variations}
 */
export async function getProductsVariations(params?: GetProductsVariationsQueryParamsType, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetProductsVariationsQueryResponseType, ResponseErrorConfig<GetProductsVariations401Type | GetProductsVariations404Type>, unknown>({
    method: 'GET',
    url: getGetProductsVariationsUrl().toString(),
    params,
    ...requestConfig,
  })
  return res.data
}