/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type { GetProductsQueryResponseType, GetProductsQueryParamsType, GetProducts401Type } from '../types/products/GetProductsType'

function getGetProductsUrl() {
  return 'http://localhost:3333/products' as const
}

/**
 * @description Esta rota requer autenticação através de um token JWT válido. Retorna uma lista paginada de produtos cadastrados no sistema. É possível filtrar os resultados através de parâmetros de consulta (query parameters) como página, limite por página, termo de busca e ordenação. Os produtos são retornados em ordem decrescente de data de cadastro por padrão. Todos os filtros são opcionais e, caso não sejam fornecidos, serão utilizados valores padrão.
 * @summary Retorna uma lista de produtos cadastrados.
 * {@link /products}
 */
export async function getProducts(params?: GetProductsQueryParamsType, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetProductsQueryResponseType, ResponseErrorConfig<GetProducts401Type>, unknown>({
    method: 'GET',
    url: getGetProductsUrl().toString(),
    params,
    ...requestConfig,
  })
  return res.data
}