/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type { GetProductsCategoriesQueryResponseType, GetProductsCategories401Type } from '../types/products/GetProductsCategoriesType'

function getGetProductsCategoriesUrl() {
  return '/products/categories' as const
}

/**
 * @description Esta rota retorna uma lista completa de todas as categorias de produtos cadastradas no sistema. As categorias são elementos fundamentais para a organização e classificação dos produtos, permitindo uma gestão eficiente do catálogo. A listagem inclui informações como ID e nome de cada categoria, facilitando a visualização e seleção das categorias disponíveis para uso na categorização de produtos.
 * @summary Retorna uma lista de categorias de produtos cadastradas.
 * {@link /products/categories}
 */
export async function getProductsCategories(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetProductsCategoriesQueryResponseType, ResponseErrorConfig<GetProductsCategories401Type>, unknown>({
    method: 'GET',
    url: getGetProductsCategoriesUrl().toString(),
    ...requestConfig,
  })
  return res.data
}