/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  GetProductsAttributesNames401Type,
  GetProductsAttributesNamesQueryParamsType,
  GetProductsAttributesNamesQueryResponseType,
} from '../types/Produtos (Atributos)Types/GetProductsAttributesNamesType.ts'

function getGetProductsAttributesNamesUrl() {
  return '/products/attributes/names' as const
}

/**
 * @description Esta rota retorna uma lista paginada de nomes de atributos de produtos cadastrados no sistema. Os resultados podem ser filtrados e ordenados através dos parâmetros de consulta disponíveis. Cada item da lista contém informações como o identificador único, nome do atributo e data de cadastro.
 * @summary Retorna uma lista de nomes de atributos de produto.
 * {@link /products/attributes/names}
 */
export async function getProductsAttributesNames(
  params?: GetProductsAttributesNamesQueryParamsType,
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    GetProductsAttributesNamesQueryResponseType,
    ResponseErrorConfig<GetProductsAttributesNames401Type>,
    unknown
  >({
    method: 'GET',
    url: getGetProductsAttributesNamesUrl().toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
