/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from './src/http/client.ts'
import type { RequestConfig, ResponseErrorConfig } from './src/http/client.ts'
import type {
  GetProductsVariationsQueryResponse,
  GetProductsVariationsQueryParams,
  GetProductsVariations401,
  GetProductsVariations404,
} from '../types/GetProductsVariations.ts'

function getGetProductsVariationsUrl() {
  return `http://localhost:3333/products/variations` as const
}

/**
 * @description Esta rota permite a listagem de todas as variações de produtos cadastradas no sistema. As variações são versões específicas dos produtos base, contendo informações como preço, SKU, estoque e características únicas (tamanho, cor, modelo, etc.). A listagem pode ser filtrada e paginada através dos parâmetros de consulta disponíveis. Os resultados incluem detalhes completos de cada variação, permitindo uma visão abrangente do catálogo de produtos. O acesso a esta funcionalidade requer autenticação prévia através de token JWT válido.
 * @summary Retorna uma lista de variações de produtos.
 * {@link /products/variations}
 */
export async function getProductsVariations(
  { params }: { params?: GetProductsVariationsQueryParams },
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetProductsVariationsQueryResponse, ResponseErrorConfig<GetProductsVariations401 | GetProductsVariations404>, unknown>({
    method: 'GET',
    url: getGetProductsVariationsUrl().toString(),
    params,
    ...requestConfig,
  })
  return res.data
}