/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  GetProductsVariationsId401Type,
  GetProductsVariationsId404Type,
  GetProductsVariationsIdPathParamsType,
  GetProductsVariationsIdQueryResponseType,
} from '../types/Produtos (Varia\u00E7\u00F5es)Types/GetProductsVariationsIdType.ts'

function getGetProductsVariationsIdUrl(
  id: GetProductsVariationsIdPathParamsType['id']
) {
  return `/products/variations/${id}` as const
}

/**
 * @description Esta rota permite consultar informações detalhadas de uma variação específica de produto através do seu ID. Retorna dados completos como preço, SKU, estoque, características específicas (tamanho, cor, modelo, etc.) e outras informações relevantes da variação. É possível verificar o status atual do estoque, disponibilidade e demais atributos únicos desta versão do produto. O acesso a esta funcionalidade requer autenticação prévia através de token JWT válido.
 * @summary Retorna as informações de uma variação de produto específica.
 * {@link /products/variations/:id}
 */
export async function getProductsVariationsId(
  id: GetProductsVariationsIdPathParamsType['id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    GetProductsVariationsIdQueryResponseType,
    ResponseErrorConfig<
      GetProductsVariationsId401Type | GetProductsVariationsId404Type
    >,
    unknown
  >({
    method: 'GET',
    url: getGetProductsVariationsIdUrl(id).toString(),
    ...requestConfig,
  })
  return res.data
}
