/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from './src/http/client.ts'
import type { RequestConfig, ResponseErrorConfig } from './src/http/client.ts'
import type {
  GetProductsAttributesNamesIdQueryResponse,
  GetProductsAttributesNamesIdPathParams,
  GetProductsAttributesNamesId401,
  GetProductsAttributesNamesId404,
} from '../types/GetProductsAttributesNamesId.ts'

function getGetProductsAttributesNamesIdUrl({ id }: { id: GetProductsAttributesNamesIdPathParams['id'] }) {
  return `http://localhost:3333/products/attributes/names/${id}` as const
}

/**
 * @description Esta rota retorna informações detalhadas sobre um nome de atributo de produto específico. Os dados retornados incluem o identificador único, nome do atributo, data de cadastro e última atualização, além de uma lista dos valores associados a este atributo. É necessário fornecer o ID do nome do atributo como parâmetro na URL.
 * @summary Retorna as informações de um nome de atributo de produto específico.
 * {@link /products/attributes/names/:id}
 */
export async function getProductsAttributesNamesId(
  { id }: { id: GetProductsAttributesNamesIdPathParams['id'] },
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    GetProductsAttributesNamesIdQueryResponse,
    ResponseErrorConfig<GetProductsAttributesNamesId401 | GetProductsAttributesNamesId404>,
    unknown
  >({ method: 'GET', url: getGetProductsAttributesNamesIdUrl({ id }).toString(), ...requestConfig })
  return res.data
}