/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  GetProductsAttributesValuesQueryResponseType,
  GetProductsAttributesValuesQueryParamsType,
  GetProductsAttributesValues401Type,
} from '../types/Produtos (Atributos)Types/GetProductsAttributesValuesType.ts'

function getGetProductsAttributesValuesUrl() {
  return `/products/attributes/values` as const
}

/**
 * @description Esta rota retorna uma lista paginada de valores de atributos de produtos cadastrados no sistema. Os resultados podem ser filtrados e ordenados através dos parâmetros de consulta disponíveis. Cada item da lista contém informações como o identificador único, valor do atributo, nome do atributo associado e data de cadastro.
 * @summary Retorna uma lista de valores de atributos de produto.
 * {@link /products/attributes/values}
 */
export async function getProductsAttributesValues(
  params: GetProductsAttributesValuesQueryParamsType,
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    GetProductsAttributesValuesQueryResponseType,
    ResponseErrorConfig<GetProductsAttributesValues401Type>,
    unknown
  >({
    method: 'GET',
    url: getGetProductsAttributesValuesUrl().toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
