/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from './src/http/client.ts'
import type { RequestConfig, ResponseErrorConfig } from './src/http/client.ts'
import type {
  GetProductsAttributesValuesQueryResponse,
  GetProductsAttributesValuesQueryParams,
  GetProductsAttributesValues401,
} from '../types/GetProductsAttributesValues.ts'

function getGetProductsAttributesValuesUrl() {
  return `http://localhost:3333/products/attributes/values` as const
}

/**
 * @description Esta rota retorna uma lista paginada de valores de atributos de produtos cadastrados no sistema. Os resultados podem ser filtrados e ordenados através dos parâmetros de consulta disponíveis. Cada item da lista contém informações como o identificador único, valor do atributo, nome do atributo associado e data de cadastro.
 * @summary Retorna uma lista de valores de atributos de produto.
 * {@link /products/attributes/values}
 */
export async function getProductsAttributesValues(
  { params }: { params: GetProductsAttributesValuesQueryParams },
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetProductsAttributesValuesQueryResponse, ResponseErrorConfig<GetProductsAttributesValues401>, unknown>({
    method: 'GET',
    url: getGetProductsAttributesValuesUrl().toString(),
    params,
    ...requestConfig,
  })
  return res.data
}