/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  GetSuppliers401Type,
  GetSuppliers404Type,
  GetSuppliersQueryParamsType,
  GetSuppliersQueryResponseType,
} from '../types/FornecedoresTypes/GetSuppliersType.ts'

function getGetSuppliersUrl() {
  return '/suppliers' as const
}

/**
 * @description Esta rota permite listar todos os fornecedores cadastrados no sistema. Os resultados podem ser filtrados através de parâmetros de consulta, como nome, CPF/CNPJ, cidade ou estado. A lista retornada é paginada, permitindo a navegação através das páginas de resultados, com opções para definir o número de itens por página. Os fornecedores são apresentados em ordem alfabética por padrão, incluindo suas informações básicas como nome, documento, cidade e contatos. É necessário que o usuário esteja autenticado com um token JWT válido para acessar esta rota.
 * @summary Retorna uma lista de fornecedores cadastrados.
 * {@link /suppliers}
 */
export async function getSuppliers(
  params?: GetSuppliersQueryParamsType,
  config: Partial<RequestConfig> & { client?: typeof client } = {}
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    GetSuppliersQueryResponseType,
    ResponseErrorConfig<GetSuppliers401Type | GetSuppliers404Type>,
    unknown
  >({
    method: 'GET',
    url: getGetSuppliersUrl().toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
