/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type { GetUsersProfileQueryResponseType, GetUsersProfile401Type, GetUsersProfile404Type } from '../types/users/GetUsersProfileType'

function getGetUsersProfileUrl() {
  return '/users/profile' as const
}

/**
 * @description Utilize esta função para recuperar dados de perfil do usuário autenticado. Esta rota retorna todas as informações de perfil do usuário, incluindo nome, email e outros dados cadastrais.
 * @summary Retorna dados de perfil do usuário.
 * {@link /users/profile}
 */
export async function getUsersProfile(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetUsersProfileQueryResponseType, ResponseErrorConfig<GetUsersProfile401Type | GetUsersProfile404Type>, unknown>({
    method: 'GET',
    url: getGetUsersProfileUrl().toString(),
    ...requestConfig,
  })
  return res.data
}