/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from './src/http/client.ts'
import type { RequestConfig, ResponseErrorConfig } from './src/http/client.ts'
import type { GetUsersProfileQueryResponse, GetUsersProfile401, GetUsersProfile404 } from '../types/GetUsersProfile.ts'

function getGetUsersProfileUrl() {
  return `http://localhost:3333/users/profile` as const
}

/**
 * @description Utilize esta função para recuperar dados de perfil do usuário autenticado. Esta rota retorna todas as informações de perfil do usuário, incluindo nome, email e outros dados cadastrais.
 * @summary Retorna dados de perfil do usuário.
 * {@link /users/profile}
 */
export async function getUsersProfile(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetUsersProfileQueryResponse, ResponseErrorConfig<GetUsersProfile401 | GetUsersProfile404>, unknown>({
    method: 'GET',
    url: getGetUsersProfileUrl().toString(),
    ...requestConfig,
  })
  return res.data
}