/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  PostProductsMutationRequestType,
  PostProductsMutationResponseType,
  PostProducts401Type,
  PostProducts404Type,
} from '../types/ProdutosTypes/PostProductsType.ts'

function getPostProductsUrl() {
  return `/products` as const
}

/**
 * @description Esta rota requer autenticação através de um token JWT válido. Para cadastrar um novo produto, os dados devem ser enviados no corpo da requisição (request body) seguindo estritamente o schema de validação definido. Os campos obrigatórios incluem nome, descrição, preço e categoria do produto. O sistema validará automaticamente todos os dados enviados antes de realizar o cadastro.
 * @summary Cadastra um novo produto.
 * {@link /products}
 */
export async function postProducts(
  data: PostProductsMutationRequestType,
  config: Partial<RequestConfig<PostProductsMutationRequestType>> & {
    client?: typeof client
  } = {}
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    PostProductsMutationResponseType,
    ResponseErrorConfig<PostProducts401Type | PostProducts404Type>,
    PostProductsMutationRequestType
  >({
    method: 'POST',
    url: getPostProductsUrl().toString(),
    data,
    ...requestConfig,
  })
  return res.data
}
