/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  PostCustomersMutationRequestType,
  PostCustomersMutationResponseType,
  PostCustomers401Type,
  PostCustomers409Type,
} from '../types/ClientesTypes/PostCustomersType.ts'

function getPostCustomersUrl() {
  return `/customers` as const
}

/**
 * @description Esta rota permite cadastrar um novo cliente no sistema. É necessário fornecer os dados do cliente no corpo da requisição, incluindo nome, documento (CPF/CNPJ), endereço e informações de contato. Os dados serão validados antes do cadastro. Requer autenticação através de um token JWT válido no cabeçalho da requisição.
 * @summary Cadastra um novo cliente.
 * {@link /customers}
 */
export async function postCustomers(
  data: PostCustomersMutationRequestType,
  config: Partial<RequestConfig<PostCustomersMutationRequestType>> & {
    client?: typeof client
  } = {}
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    PostCustomersMutationResponseType,
    ResponseErrorConfig<PostCustomers401Type | PostCustomers409Type>,
    PostCustomersMutationRequestType
  >({
    method: 'POST',
    url: getPostCustomersUrl().toString(),
    data,
    ...requestConfig,
  })
  return res.data
}
