/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  PostUsersMutationRequestType,
  PostUsersMutationResponseType,
  PostUsers409Type,
} from '../types/Usu\u00E1riosTypes/PostUsersType.ts'

function getPostUsersUrl() {
  return `/users` as const
}

/**
 * @description Esta rota não retorna nenhum dado caso o usurário seja criado com sucesso. O email e a senha informados são utilizados para autenticar o usuário em futuras requisições. O nome e o email são obrigatórios, e a senha deve ter no mínimo 6 caracteres.
 * @summary Registra um novo usuário.
 * {@link /users}
 */
export async function postUsers(
  data: PostUsersMutationRequestType,
  config: Partial<RequestConfig<PostUsersMutationRequestType>> & {
    client?: typeof client
  } = {}
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    PostUsersMutationResponseType,
    ResponseErrorConfig<PostUsers409Type>,
    PostUsersMutationRequestType
  >({
    method: 'POST',
    url: getPostUsersUrl().toString(),
    data,
    ...requestConfig,
  })
  return res.data
}
