/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from './src/http/client.ts'
import type { RequestConfig, ResponseErrorConfig } from './src/http/client.ts'
import type { PostOrdersMutationRequest, PostOrdersMutationResponse, PostOrders400, PostOrders401, PostOrders404 } from '../types/PostOrders.ts'

function getPostOrdersUrl() {
  return `http://localhost:3333/orders` as const
}

/**
 * @description O pedido deve conter informações cliente, produtos selecionados (código, descrição), quantidades solicitadas por item, valores unitários e totais, forma de pagamento e observações adicionais. O sistema calculará automaticamente impostos e descontos aplicáveis. Para utilizar este recurso, é obrigatório o envio de um token JWT válido no cabeçalho da requisição para autenticação do usuário.
 * @summary Registra um novo pedido.
 * {@link /orders}
 */
export async function postOrders(
  { data }: { data: PostOrdersMutationRequest },
  config: Partial<RequestConfig<PostOrdersMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PostOrdersMutationResponse, ResponseErrorConfig<PostOrders400 | PostOrders401 | PostOrders404>, PostOrdersMutationRequest>({
    method: 'POST',
    url: getPostOrdersUrl().toString(),
    data,
    ...requestConfig,
  })
  return res.data
}