/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from './src/http/client.ts'
import type { RequestConfig, ResponseErrorConfig } from './src/http/client.ts'
import type {
  PostProductsAttributesValuesMutationRequest,
  PostProductsAttributesValuesMutationResponse,
  PostProductsAttributesValues401,
  PostProductsAttributesValues409,
} from '../types/PostProductsAttributesValues.ts'

function getPostProductsAttributesValuesUrl() {
  return `http://localhost:3333/products/attributes/values` as const
}

/**
 * @description O valor do atributo é um dado específico que pode ser associado a um nome de atributo previamente cadastrado. Por exemplo, para o atributo "Cor", podem ser cadastrados valores como "Vermelho", "Azul", "Verde", etc. É necessário ter um nome de atributo cadastrado antes de registrar seus valores correspondentes.
 * @summary Registra um novo valor de atributo de produto.
 * {@link /products/attributes/values}
 */
export async function postProductsAttributesValues(
  { data }: { data: PostProductsAttributesValuesMutationRequest },
  config: Partial<RequestConfig<PostProductsAttributesValuesMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    PostProductsAttributesValuesMutationResponse,
    ResponseErrorConfig<PostProductsAttributesValues401 | PostProductsAttributesValues409>,
    PostProductsAttributesValuesMutationRequest
  >({ method: 'POST', url: getPostProductsAttributesValuesUrl().toString(), data, ...requestConfig })
  return res.data
}