/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from './src/http/client.ts'
import type { RequestConfig, ResponseErrorConfig } from './src/http/client.ts'
import type {
  PostShopeeOrderImportMutationResponse,
  PostShopeeOrderImportQueryParams,
  PostShopeeOrderImport400,
  PostShopeeOrderImport401,
  PostShopeeOrderImport404,
} from '../types/PostShopeeOrderImport.ts'

function getPostShopeeOrderImportUrl() {
  return `http://localhost:3333/shopee/order/import` as const
}

/**
 * {@link /shopee/order/import}
 */
export async function postShopeeOrderImport(
  { params }: { params: PostShopeeOrderImportQueryParams },
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    PostShopeeOrderImportMutationResponse,
    ResponseErrorConfig<PostShopeeOrderImport400 | PostShopeeOrderImport401 | PostShopeeOrderImport404>,
    unknown
  >({ method: 'POST', url: getPostShopeeOrderImportUrl().toString(), params, ...requestConfig })
  return res.data
}