/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  PostShopeeOrderImportMutationResponseType,
  PostShopeeOrderImportQueryParamsType,
  PostShopeeOrderImport400Type,
  PostShopeeOrderImport401Type,
  PostShopeeOrderImport404Type,
} from '../types/shopee/PostShopeeOrderImportType'

function getPostShopeeOrderImportUrl() {
  return '/shopee/order/import' as const
}

/**
 * {@link /shopee/order/import}
 */
export async function postShopeeOrderImport(params: PostShopeeOrderImportQueryParamsType, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    PostShopeeOrderImportMutationResponseType,
    ResponseErrorConfig<PostShopeeOrderImport400Type | PostShopeeOrderImport401Type | PostShopeeOrderImport404Type>,
    unknown
  >({ method: 'POST', url: getPostShopeeOrderImportUrl().toString(), params, ...requestConfig })
  return res.data
}