/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from './src/http/client.ts'
import type { RequestConfig, ResponseErrorConfig } from './src/http/client.ts'
import type { PostCustomersMutationRequest, PostCustomersMutationResponse, PostCustomers401, PostCustomers409 } from '../types/PostCustomers.ts'

function getPostCustomersUrl() {
  return `http://localhost:3333/customers` as const
}

/**
 * @description Esta rota permite cadastrar um novo cliente no sistema. É necessário fornecer os dados do cliente no corpo da requisição, incluindo nome, documento (CPF/CNPJ), endereço e informações de contato. Os dados serão validados antes do cadastro. Requer autenticação através de um token JWT válido no cabeçalho da requisição.
 * @summary Cadastra um novo cliente.
 * {@link /customers}
 */
export async function postCustomers(
  { data }: { data: PostCustomersMutationRequest },
  config: Partial<RequestConfig<PostCustomersMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PostCustomersMutationResponse, ResponseErrorConfig<PostCustomers401 | PostCustomers409>, PostCustomersMutationRequest>({
    method: 'POST',
    url: getPostCustomersUrl().toString(),
    data,
    ...requestConfig,
  })
  return res.data
}