/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  PostEmployees401Type,
  PostEmployees409Type,
  PostEmployeesMutationRequestType,
  PostEmployeesMutationResponseType,
} from '../types/ColaboradoresTypes/PostEmployeesType.ts'

function getPostEmployeesUrl() {
  return '/employees' as const
}

/**
 * @description Requer autenticação via token JWT para garantir acesso seguro. Permite o registro completo de informações do colaborador, incluindo: nome completo, cargo, departamento, data de admissão, documentos pessoais, informações de contato e dados bancários. Todos os campos devem ser preenchidos conforme as especificações definidas no schema do corpo da requisição. Os dados são validados antes do processamento para garantir a integridade e consistência das informações.
 * @summary Cadastra um novo colaborador.
 * {@link /employees}
 */
export async function postEmployees(
  data: PostEmployeesMutationRequestType,
  config: Partial<RequestConfig<PostEmployeesMutationRequestType>> & {
    client?: typeof client
  } = {}
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    PostEmployeesMutationResponseType,
    ResponseErrorConfig<PostEmployees401Type | PostEmployees409Type>,
    PostEmployeesMutationRequestType
  >({
    method: 'POST',
    url: getPostEmployeesUrl().toString(),
    data,
    ...requestConfig,
  })
  return res.data
}
