/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from './src/http/client.ts'
import type { RequestConfig, ResponseErrorConfig } from './src/http/client.ts'
import type { PostProductsMutationRequest, PostProductsMutationResponse, PostProducts401, PostProducts404 } from '../types/PostProducts.ts'

function getPostProductsUrl() {
  return `http://localhost:3333/products` as const
}

/**
 * @description Esta rota requer autenticação através de um token JWT válido. Para cadastrar um novo produto, os dados devem ser enviados no corpo da requisição (request body) seguindo estritamente o schema de validação definido. Os campos obrigatórios incluem nome, descrição, preço e categoria do produto. O sistema validará automaticamente todos os dados enviados antes de realizar o cadastro.
 * @summary Cadastra um novo produto.
 * {@link /products}
 */
export async function postProducts(
  { data }: { data: PostProductsMutationRequest },
  config: Partial<RequestConfig<PostProductsMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PostProductsMutationResponse, ResponseErrorConfig<PostProducts401 | PostProducts404>, PostProductsMutationRequest>({
    method: 'POST',
    url: getPostProductsUrl().toString(),
    data,
    ...requestConfig,
  })
  return res.data
}