/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  PostSuppliers401Type,
  PostSuppliers409Type,
  PostSuppliersMutationRequestType,
  PostSuppliersMutationResponseType,
} from '../types/FornecedoresTypes/PostSuppliersType'

function getPostSuppliersUrl() {
  return '/suppliers' as const
}

/**
 * @description Esta rota permite o cadastro de um novo fornecedor no sistema. Os dados do fornecedor devem ser enviados no corpo da requisição, incluindo informações essenciais como: nome completo ou razão social, CPF ou CNPJ, inscrição estadual (se aplicável), endereço completo (logradouro, número, complemento, bairro, cidade, estado e CEP), informações de contato (telefone, celular, e-mail) e observações adicionais. O sistema validará os dados fornecidos e, em caso de sucesso, retornará os dados do fornecedor recém-cadastrado com seu ID único. É necessário que o usuário esteja autenticado com um token JWT válido para acessar esta rota.
 * @summary Cadastrar um novo fornecedor.
 * {@link /suppliers}
 */
export async function postSuppliers(
  data: PostSuppliersMutationRequestType,
  config: Partial<RequestConfig<PostSuppliersMutationRequestType>> & {
    client?: typeof client
  } = {}
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    PostSuppliersMutationResponseType,
    ResponseErrorConfig<PostSuppliers401Type | PostSuppliers409Type>,
    PostSuppliersMutationRequestType
  >({
    method: 'POST',
    url: getPostSuppliersUrl().toString(),
    data,
    ...requestConfig,
  })
  return res.data
}
