/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  PostProductsBrandsMutationRequestType,
  PostProductsBrandsMutationResponseType,
  PostProductsBrands401Type,
  PostProductsBrands409Type,
} from '../types/Produtos (Marcas)Types/PostProductsBrandsType.ts'

function getPostProductsBrandsUrl() {
  return `/products/brands` as const
}

/**
 * @description Esta rota requer autenticação via JWT (JSON Web Token) para garantir a segurança do acesso. Permite o cadastro de uma nova marca no sistema, possibilitando a inclusão de informações essenciais como nome e descrição detalhada. A marca, uma vez cadastrada, servirá como referência para categorização e organização do catálogo de produtos, podendo ser vinculada a múltiplos itens durante o processo de criação e atualização de produtos. O cadastro adequado das marcas é fundamental para manter a consistência e rastreabilidade dos produtos no sistema.
 * @summary Cadastra uma nova marca.
 * {@link /products/brands}
 */
export async function postProductsBrands(
  data: PostProductsBrandsMutationRequestType,
  config: Partial<RequestConfig<PostProductsBrandsMutationRequestType>> & {
    client?: typeof client
  } = {}
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    PostProductsBrandsMutationResponseType,
    ResponseErrorConfig<PostProductsBrands401Type | PostProductsBrands409Type>,
    PostProductsBrandsMutationRequestType
  >({
    method: 'POST',
    url: getPostProductsBrandsUrl().toString(),
    data,
    ...requestConfig,
  })
  return res.data
}
