/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  PostOrdersMutationRequestType,
  PostOrdersMutationResponseType,
  PostOrders400Type,
  PostOrders401Type,
  PostOrders404Type,
} from '../types/PedidosTypes/PostOrdersType'

function getPostOrdersUrl() {
  return '/orders' as const
}

/**
 * @description O pedido deve conter informações cliente, produtos selecionados (código, descrição), quantidades solicitadas por item, valores unitários e totais, forma de pagamento e observações adicionais. O sistema calculará automaticamente impostos e descontos aplicáveis. Para utilizar este recurso, é obrigatório o envio de um token JWT válido no cabeçalho da requisição para autenticação do usuário.
 * @summary Registra um novo pedido.
 * {@link /orders}
 */
export async function postOrders(
  data: PostOrdersMutationRequestType,
  config: Partial<RequestConfig<PostOrdersMutationRequestType>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    PostOrdersMutationResponseType,
    ResponseErrorConfig<PostOrders400Type | PostOrders401Type | PostOrders404Type>,
    PostOrdersMutationRequestType
  >({ method: 'POST', url: getPostOrdersUrl().toString(), data, ...requestConfig })
  return res.data
}