/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  PostProductsAttributesValuesMutationRequestType,
  PostProductsAttributesValuesMutationResponseType,
  PostProductsAttributesValues401Type,
  PostProductsAttributesValues409Type,
} from '../types/Produtos (Atributos)Types/PostProductsAttributesValuesType.ts'

function getPostProductsAttributesValuesUrl() {
  return `/products/attributes/values` as const
}

/**
 * @description O valor do atributo é um dado específico que pode ser associado a um nome de atributo previamente cadastrado. Por exemplo, para o atributo "Cor", podem ser cadastrados valores como "Vermelho", "Azul", "Verde", etc. É necessário ter um nome de atributo cadastrado antes de registrar seus valores correspondentes.
 * @summary Registra um novo valor de atributo de produto.
 * {@link /products/attributes/values}
 */
export async function postProductsAttributesValues(
  data: PostProductsAttributesValuesMutationRequestType,
  config: Partial<RequestConfig<PostProductsAttributesValuesMutationRequestType>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    PostProductsAttributesValuesMutationResponseType,
    ResponseErrorConfig<PostProductsAttributesValues401Type | PostProductsAttributesValues409Type>,
    PostProductsAttributesValuesMutationRequestType
  >({ method: 'POST', url: getPostProductsAttributesValuesUrl().toString(), data, ...requestConfig })
  return res.data
}