/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  PutEmployeesIdMutationRequestType,
  PutEmployeesIdMutationResponseType,
  PutEmployeesIdPathParamsType,
  PutEmployeesId401Type,
  PutEmployeesId404Type,
} from '../types/ColaboradoresTypes/PutEmployeesIdType'

function getPutEmployeesIdUrl(id: PutEmployeesIdPathParamsType['id']) {
  return `/employees/${id}` as const
}

/**
 * @description Requer autenticação via token JWT para garantir acesso seguro. Permite a atualização das informações de um colaborador específico, incluindo: nome completo, cargo, departamento, documentos pessoais, informações de contato e dados bancários. O ID do colaborador deve ser fornecido como parâmetro na URL. Todos os campos devem ser preenchidos conforme as especificações definidas no schema do corpo da requisição. Os dados são validados antes do processamento para garantir a integridade e consistência das informações. A rota verifica a existência do colaborador antes de realizar as alterações.
 * @summary Altera as informações de um colaborador específico.
 * {@link /employees/:id}
 */
export async function putEmployeesId(
  id: PutEmployeesIdPathParamsType['id'],
  data: PutEmployeesIdMutationRequestType,
  config: Partial<RequestConfig<PutEmployeesIdMutationRequestType>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    PutEmployeesIdMutationResponseType,
    ResponseErrorConfig<PutEmployeesId401Type | PutEmployeesId404Type>,
    PutEmployeesIdMutationRequestType
  >({ method: 'PUT', url: getPutEmployeesIdUrl(id).toString(), data, ...requestConfig })
  return res.data
}