/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/http/client'
import type { RequestConfig, ResponseErrorConfig } from '@/http/client'
import type {
  PutOrdersIdMutationRequestType,
  PutOrdersIdMutationResponseType,
  PutOrdersIdPathParamsType,
  PutOrdersId400Type,
  PutOrdersId401Type,
  PutOrdersId404Type,
} from '../types/orders/PutOrdersIdType'

function getPutOrdersIdUrl({ id }: { id: PutOrdersIdPathParamsType['id'] }) {
  return `http://localhost:3333/orders/${id}` as const
}

/**
 * @description Permite a modificação de informações de um pedido existente, como dados do cliente, itens, quantidades, valores e status. É necessário fornecer o ID do pedido na URL e os dados atualizados no corpo da requisição. O sistema recalculará automaticamente os valores totais e impostos aplicáveis. Requer autenticação através de um token JWT válido no cabeçalho da requisição.
 * @summary Altera as informações de um pedido existente.
 * {@link /orders/:id}
 */
export async function putOrdersId(
  { id, data }: { id: PutOrdersIdPathParamsType['id']; data: PutOrdersIdMutationRequestType },
  config: Partial<RequestConfig<PutOrdersIdMutationRequestType>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    PutOrdersIdMutationResponseType,
    ResponseErrorConfig<PutOrdersId400Type | PutOrdersId401Type | PutOrdersId404Type>,
    PutOrdersIdMutationRequestType
  >({ method: 'PUT', url: getPutOrdersIdUrl({ id }).toString(), data, ...requestConfig })
  return res.data
}