/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from './src/http/client.ts'
import type { RequestConfig, ResponseErrorConfig } from './src/http/client.ts'
import type {
  PutProductsAttributesValuesIdMutationRequest,
  PutProductsAttributesValuesIdMutationResponse,
  PutProductsAttributesValuesIdPathParams,
  PutProductsAttributesValuesId401,
  PutProductsAttributesValuesId404,
} from '../types/PutProductsAttributesValuesId.ts'

function getPutProductsAttributesValuesIdUrl({ id }: { id: PutProductsAttributesValuesIdPathParams['id'] }) {
  return `http://localhost:3333/products/attributes/values/${id}` as const
}

/**
 * @description Esta rota permite atualizar as informações de um valor de atributo de produto específico. É necessário fornecer o ID do valor do atributo como parâmetro na URL e os novos dados no corpo da requisição. A atualização pode incluir a modificação do valor do atributo e/ou a associação com um nome de atributo diferente. O sistema verifica a existência do valor do atributo e do nome do atributo associado, além de garantir que não haja duplicidade de valores para o mesmo nome de atributo antes de realizar a atualização.
 * @summary Altera um valor de atributo de produto específico.
 * {@link /products/attributes/values/:id}
 */
export async function putProductsAttributesValuesId(
  { id, data }: { id: PutProductsAttributesValuesIdPathParams['id']; data: PutProductsAttributesValuesIdMutationRequest },
  config: Partial<RequestConfig<PutProductsAttributesValuesIdMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    PutProductsAttributesValuesIdMutationResponse,
    ResponseErrorConfig<PutProductsAttributesValuesId401 | PutProductsAttributesValuesId404>,
    PutProductsAttributesValuesIdMutationRequest
  >({ method: 'PUT', url: getPutProductsAttributesValuesIdUrl({ id }).toString(), data, ...requestConfig })
  return res.data
}