/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Default Response
 */
export type GetShopeeAuthUrl200Type = {
  /**
   * @type string
   */
  url: string
}

/**
 * @description Usuário não autenticado.
 */
export type GetShopeeAuthUrl401Type = {
  /**
   * @type string
   */
  message: string
}

export type GetShopeeAuthUrlQueryResponseType = GetShopeeAuthUrl200Type

export type GetShopeeAuthUrlTypeQuery = {
  Response: GetShopeeAuthUrl200Type
  Errors: GetShopeeAuthUrl401Type
}