/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const postShopeeAuthToken200Enum = {
  null: 'null',
} as const

export type PostShopeeAuthToken200EnumType = (typeof postShopeeAuthToken200Enum)[keyof typeof postShopeeAuthToken200Enum]

/**
 * @description Shopee authenticated.
 */
export type PostShopeeAuthToken200Type = PostShopeeAuthToken200EnumType | null

/**
 * @description Shopee already exists.
 */
export type PostShopeeAuthToken400Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Usuário não autenticado.
 */
export type PostShopeeAuthToken401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Connection not found.
 */
export type PostShopeeAuthToken404Type = {
  /**
   * @type string
   */
  message: string
}

export type PostShopeeAuthTokenMutationRequestType = {
  /**
   * @type string
   */
  code: string
  /**
   * @type number
   */
  shopId: number
}

export type PostShopeeAuthTokenMutationResponseType = PostShopeeAuthToken200Type

export type PostShopeeAuthTokenTypeMutation = {
  Response: PostShopeeAuthToken200Type
  Request: PostShopeeAuthTokenMutationRequestType
  Errors: PostShopeeAuthToken400Type | PostShopeeAuthToken401Type | PostShopeeAuthToken404Type
}