/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Default Response
 */
export type PostShopeeDownloadShippingDocument200Type = unknown

export type PostShopeeDownloadShippingDocumentMutationResponseType = PostShopeeDownloadShippingDocument200Type

export type PostShopeeDownloadShippingDocumentTypeMutation = {
  Response: PostShopeeDownloadShippingDocument200Type
  Errors: any
}