/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteProductsCategoriesIdPathParamsType = {
  /**
   * @type string
   */
  id: string
}

export const deleteProductsCategoriesId200Enum = {
  null: 'null',
} as const

export type DeleteProductsCategoriesId200EnumType = (typeof deleteProductsCategoriesId200Enum)[keyof typeof deleteProductsCategoriesId200Enum]

/**
 * @description Categoria deletada com sucesso.
 */
export type DeleteProductsCategoriesId200Type = DeleteProductsCategoriesId200EnumType | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteProductsCategoriesId401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Categoria não encontrado.
 */
export type DeleteProductsCategoriesId404Type = {
  /**
   * @type string
   */
  message: string
}

export type DeleteProductsCategoriesIdMutationResponseType = DeleteProductsCategoriesId200Type

export type DeleteProductsCategoriesIdTypeMutation = {
  Response: DeleteProductsCategoriesId200Type
  PathParams: DeleteProductsCategoriesIdPathParamsType
  Errors: DeleteProductsCategoriesId401Type | DeleteProductsCategoriesId404Type
}