/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Categorias de produtos obtidas com sucesso.
 */
export type GetProductsCategories200Type = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  name: string
}[]

/**
 * @description Usuário não autenticado.
 */
export type GetProductsCategories401Type = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsCategoriesQueryResponseType =
  GetProductsCategories200Type

export type GetProductsCategoriesTypeQuery = {
  Response: GetProductsCategories200Type
  Errors: GetProductsCategories401Type
}
