/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const postProductsCategories201Enum = {
  null: 'null',
} as const

export type PostProductsCategories201EnumType =
  (typeof postProductsCategories201Enum)[keyof typeof postProductsCategories201Enum]

/**
 * @description Categoria cadastrado com sucesso.
 */
export type PostProductsCategories201Type =
  PostProductsCategories201EnumType | null

/**
 * @description Usuário não autenticado.
 */
export type PostProductsCategories401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Categoria já cadastrado.
 */
export type PostProductsCategories409Type = {
  /**
   * @type string
   */
  message: string
}

export type PostProductsCategoriesMutationRequestType = {
  /**
   * @type string
   */
  name: string
}

export type PostProductsCategoriesMutationResponseType =
  PostProductsCategories201Type

export type PostProductsCategoriesTypeMutation = {
  Response: PostProductsCategories201Type
  Request: PostProductsCategoriesMutationRequestType
  Errors: PostProductsCategories401Type | PostProductsCategories409Type
}
