/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteProductsVariationsIdPathParamsType = {
  /**
   * @type string
   */
  id: string
}

export const deleteProductsVariationsId200Enum = {
  null: 'null',
} as const

export type DeleteProductsVariationsId200EnumType =
  (typeof deleteProductsVariationsId200Enum)[keyof typeof deleteProductsVariationsId200Enum]

/**
 * @description Variação de produto deletado com sucesso.
 */
export type DeleteProductsVariationsId200Type =
  DeleteProductsVariationsId200EnumType | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteProductsVariationsId401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Variação de produto não encontrado.
 */
export type DeleteProductsVariationsId404Type = {
  /**
   * @type string
   */
  message: string
}

export type DeleteProductsVariationsIdMutationResponseType =
  DeleteProductsVariationsId200Type

export type DeleteProductsVariationsIdTypeMutation = {
  Response: DeleteProductsVariationsId200Type
  PathParams: DeleteProductsVariationsIdPathParamsType
  Errors: DeleteProductsVariationsId401Type | DeleteProductsVariationsId404Type
}
