/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const getProductsVariationsQueryParamsOrderByEnum = {
  desc: 'desc',
  asc: 'asc',
} as const

export type GetProductsVariationsQueryParamsOrderByEnumType =
  (typeof getProductsVariationsQueryParamsOrderByEnum)[keyof typeof getProductsVariationsQueryParamsOrderByEnum]

export type GetProductsVariationsQueryParamsType = {
  /**
   * @default 10
   * @type number | undefined
   */
  perPage?: number
  /**
   * @default 0
   * @type number | undefined
   */
  pageIndex?: number
  /**
   * @default "desc"
   * @type string | undefined
   */
  orderBy?: GetProductsVariationsQueryParamsOrderByEnumType
  /**
   * @type string | undefined
   */
  productId?: string
  /**
   * @type string | undefined
   */
  productVariationName?: string
}

/**
 * @description Variações de produtos obtidos com sucesso.
 */
export type GetProductsVariations200Type = {
  /**
   * @type number
   */
  totalCount: number
  /**
   * @type number
   */
  pageCount: number
  /**
   * @type array
   */
  productVariations: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    barcode: string | null
    /**
     * @minLength 1
     * @type string
     */
    name: string
    /**
     * @type number
     */
    average_cost: number
    /**
     * @type number
     */
    cost_price: number
    /**
     * @type number
     */
    selling_price: number
    /**
     * @type string
     */
    product_storage_location: string | null
    /**
     * @type number
     */
    current_stock: number
    /**
     * @type number
     */
    minimum_stock_level: number
    /**
     * @type number
     */
    products_in_review: number
    /**
     * @type boolean | undefined
     */
    track_inventory?: boolean
    /**
     * @type boolean | undefined
     */
    is_available?: boolean
    /**
     * @type string, date-time
     */
    created_at: string
    /**
     * @type string
     */
    product_id: string
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetProductsVariations401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Variações de produtos não encontrado.
 */
export type GetProductsVariations404Type = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsVariationsQueryResponseType =
  GetProductsVariations200Type

export type GetProductsVariationsTypeQuery = {
  Response: GetProductsVariations200Type
  QueryParams: GetProductsVariationsQueryParamsType
  Errors: GetProductsVariations401Type | GetProductsVariations404Type
}
