/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from '@kubb/plugin-zod/utils'
import { z } from 'zod'
import type { FileUploadType } from '../types/FileUploadType.ts'

export const fileUploadSchema = z.object({
  file: z
    .instanceof(File)
    .describe('Arquivo de imagem a ser enviado')
    .optional(),
}) as unknown as ToZod<FileUploadType>
