/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const postSuppliers201Enum = {
  null: 'null',
} as const

export type PostSuppliers201EnumType = (typeof postSuppliers201Enum)[keyof typeof postSuppliers201Enum]

/**
 * @description Fornecedor cadastrado com sucesso.
 */
export type PostSuppliers201Type = PostSuppliers201EnumType | null

/**
 * @description Usuário não autenticado.
 */
export type PostSuppliers401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Fornecedor já cadastrado.
 */
export type PostSuppliers409Type = {
  /**
   * @type string
   */
  message: string
}

export const postSuppliersMutationRequestDocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type PostSuppliersMutationRequestDocumentTypeEnumType =
  (typeof postSuppliersMutationRequestDocumentTypeEnum)[keyof typeof postSuppliersMutationRequestDocumentTypeEnum]

export type PostSuppliersMutationRequestType = {
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @minLength 1
   * @type string
   */
  phone: string
  /**
   * @type string | undefined
   */
  phone_2?: string
  /**
   * @type string
   */
  document_type: PostSuppliersMutationRequestDocumentTypeEnumType
  /**
   * @minLength 1
   * @type string
   */
  document: string
  /**
   * @type string | undefined
   */
  document_2?: string
  /**
   * @minLength 1
   * @type string, email
   */
  email: string
  /**
   * @type string | undefined
   */
  state_registration?: string
  /**
   * @type boolean | undefined
   */
  tax_free?: boolean
  /**
   * @minLength 1
   * @type string
   */
  recipient_name: string
  /**
   * @minLength 1
   * @type string
   */
  recipient_phone: string
  /**
   * @minLength 1
   * @type string
   */
  cep: string
  /**
   * @minLength 1
   * @type string
   */
  street: string
  /**
   * @minLength 1
   * @type string
   */
  number: string
  /**
   * @type string | undefined
   */
  complement?: string
  /**
   * @minLength 1
   * @type string
   */
  neighborhood: string
  /**
   * @minLength 1
   * @type string
   */
  city: string
  /**
   * @minLength 1
   * @type string
   */
  state: string
}

export type PostSuppliersMutationResponseType = PostSuppliers201Type

export type PostSuppliersTypeMutation = {
  Response: PostSuppliers201Type
  Request: PostSuppliersMutationRequestType
  Errors: PostSuppliers401Type | PostSuppliers409Type
}