/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PutSuppliersIdPathParamsType = {
  /**
   * @type string
   */
  id: string
}

export const putSuppliersId200Enum = {
  null: 'null',
} as const

export type PutSuppliersId200EnumType = (typeof putSuppliersId200Enum)[keyof typeof putSuppliersId200Enum]

/**
 * @description Fornecedor atualizado com sucesso.
 */
export type PutSuppliersId200Type = PutSuppliersId200EnumType | null

/**
 * @description Usuário não autenticado.
 */
export type PutSuppliersId401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Fornecedor não encontrado.
 */
export type PutSuppliersId404Type = {
  /**
   * @type string
   */
  message: string
}

export const putSuppliersIdMutationRequestDocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type PutSuppliersIdMutationRequestDocumentTypeEnumType =
  (typeof putSuppliersIdMutationRequestDocumentTypeEnum)[keyof typeof putSuppliersIdMutationRequestDocumentTypeEnum]

export type PutSuppliersIdMutationRequestType = {
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @minLength 1
   * @type string
   */
  phone: string
  /**
   * @type string | undefined
   */
  phone_2?: string
  /**
   * @type string
   */
  document_type: PutSuppliersIdMutationRequestDocumentTypeEnumType
  /**
   * @minLength 1
   * @type string
   */
  document: string
  /**
   * @type string | undefined
   */
  document_2?: string
  /**
   * @minLength 1
   * @type string, email
   */
  email: string
  /**
   * @type string | undefined
   */
  state_registration?: string
  /**
   * @type boolean | undefined
   */
  tax_free?: boolean
  /**
   * @minLength 1
   * @pattern ^[cC][^\s-]{8,}$
   * @type string
   */
  address_id: string
  /**
   * @minLength 1
   * @type string
   */
  recipient_name: string
  /**
   * @minLength 1
   * @type string
   */
  recipient_phone: string
  /**
   * @minLength 1
   * @type string
   */
  cep: string
  /**
   * @minLength 1
   * @type string
   */
  street: string
  /**
   * @minLength 1
   * @type string
   */
  number: string
  /**
   * @type string | undefined
   */
  complement?: string
  /**
   * @minLength 1
   * @type string
   */
  neighborhood: string
  /**
   * @minLength 1
   * @type string
   */
  city: string
  /**
   * @minLength 1
   * @type string
   */
  state: string
}

export type PutSuppliersIdMutationResponseType = PutSuppliersId200Type

export type PutSuppliersIdTypeMutation = {
  Response: PutSuppliersId200Type
  Request: PutSuppliersIdMutationRequestType
  PathParams: PutSuppliersIdPathParamsType
  Errors: PutSuppliersId401Type | PutSuppliersId404Type
}