/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from '@kubb/plugin-zod/utils'
import { z } from 'zod'
import type {
  GetShopeeAuthUrl200Type,
  GetShopeeAuthUrl401Type,
  GetShopeeAuthUrlQueryResponseType,
} from '../../types/Shopee APITypes/GetShopeeAuthUrlType'

/**
 * @description Default Response
 */
export const getShopeeAuthUrl200Schema = z.object({
  url: z.string(),
}) as unknown as ToZod<GetShopeeAuthUrl200Type>

/**
 * @description Usuário não autenticado.
 */
export const getShopeeAuthUrl401Schema = z
  .object({
    message: z.string(),
  })
  .describe(
    'Usuário não autenticado.'
  ) as unknown as ToZod<GetShopeeAuthUrl401Type>

export const getShopeeAuthUrlQueryResponseSchema = z.lazy(
  () => getShopeeAuthUrl200Schema
) as unknown as ToZod<GetShopeeAuthUrlQueryResponseType>
