/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from '@kubb/plugin-zod/utils'
import type {
  PostShopeeAuthToken200Type,
  PostShopeeAuthToken400Type,
  PostShopeeAuthToken401Type,
  PostShopeeAuthToken404Type,
  PostShopeeAuthTokenMutationRequestType,
  PostShopeeAuthTokenMutationResponseType,
} from '../../types/shopee/PostShopeeAuthTokenType'
import { z } from 'zod'

/**
 * @description Shopee authenticated.
 */
export const postShopeeAuthToken200Schema = z.enum(['null']).describe('Shopee authenticated.').nullable() as unknown as ToZod<PostShopeeAuthToken200Type>

/**
 * @description Shopee already exists.
 */
export const postShopeeAuthToken400Schema = z
  .object({
    message: z.string(),
  })
  .describe('Shopee already exists.') as unknown as ToZod<PostShopeeAuthToken400Type>

/**
 * @description Usuário não autenticado.
 */
export const postShopeeAuthToken401Schema = z
  .object({
    message: z.string(),
  })
  .describe('Usuário não autenticado.') as unknown as ToZod<PostShopeeAuthToken401Type>

/**
 * @description Connection not found.
 */
export const postShopeeAuthToken404Schema = z
  .object({
    message: z.string(),
  })
  .describe('Connection not found.') as unknown as ToZod<PostShopeeAuthToken404Type>

export const postShopeeAuthTokenMutationRequestSchema = z.object({
  code: z.string(),
  shopId: z.number(),
}) as unknown as ToZod<PostShopeeAuthTokenMutationRequestType>

export const postShopeeAuthTokenMutationResponseSchema = z.lazy(() => postShopeeAuthToken200Schema) as unknown as ToZod<PostShopeeAuthTokenMutationResponseType>