/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const getCustomersQueryParamsOrderByEnum = {
  desc: 'desc',
  asc: 'asc',
} as const

export type GetCustomersQueryParamsOrderByEnumType = (typeof getCustomersQueryParamsOrderByEnum)[keyof typeof getCustomersQueryParamsOrderByEnum]

export type GetCustomersQueryParamsType = {
  /**
   * @default 10
   * @type number | undefined
   */
  perPage?: number
  /**
   * @minLength 1
   * @default 1
   * @type number | undefined
   */
  pageIndex?: number
  /**
   * @default "desc"
   * @type string | undefined
   */
  orderBy?: GetCustomersQueryParamsOrderByEnumType
  /**
   * @type string | undefined
   */
  customerName?: string
  /**
   * @type string | undefined
   */
  customerDocument?: string
}

export const customersDocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type CustomersDocumentTypeEnumType = (typeof customersDocumentTypeEnum)[keyof typeof customersDocumentTypeEnum]

/**
 * @description Clientes obtidos com sucesso.
 */
export type GetCustomers200Type = {
  /**
   * @type number
   */
  totalCount: number
  /**
   * @type number
   */
  pageCount: number
  /**
   * @type array
   */
  customers: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    name: string
    /**
     * @type string
     */
    document_type: CustomersDocumentTypeEnumType
    /**
     * @type string
     */
    document: string
    /**
     * @type string
     */
    user_id: string
    /**
     * @type number
     */
    entry_number: number
    /**
     * @type string
     */
    person_id: string
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetCustomers401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Cliente não encontrado.
 */
export type GetCustomers404Type = {
  /**
   * @type string
   */
  message: string
}

export type GetCustomersQueryResponseType = GetCustomers200Type

export type GetCustomersTypeQuery = {
  Response: GetCustomers200Type
  QueryParams: GetCustomersQueryParamsType
  Errors: GetCustomers401Type | GetCustomers404Type
}