/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from '@kubb/plugin-zod/utils'
import type {
  PostEmployees201Type,
  PostEmployees401Type,
  PostEmployees409Type,
  PostEmployeesMutationRequestType,
  PostEmployeesMutationResponseType,
} from '../../types/ColaboradoresTypes/PostEmployeesType.ts'
import { z } from 'zod'

/**
 * @description Colaborador cadastrado com sucesso.
 */
export const postEmployees201Schema = z
  .enum(['null'])
  .describe('Colaborador cadastrado com sucesso.')
  .nullable() as unknown as ToZod<PostEmployees201Type>

/**
 * @description Usuário não autenticado.
 */
export const postEmployees401Schema = z
  .object({
    message: z.string(),
  })
  .describe(
    'Usuário não autenticado.'
  ) as unknown as ToZod<PostEmployees401Type>

/**
 * @description Colaborador já cadastrado.
 */
export const postEmployees409Schema = z
  .object({
    message: z.string(),
  })
  .describe(
    'Colaborador já cadastrado.'
  ) as unknown as ToZod<PostEmployees409Type>

export const postEmployeesMutationRequestSchema = z.object({
  name: z.string().min(1),
  phone: z.string().min(1),
  phone_2: z.string().optional(),
  document_type: z.enum(['PERSON', 'COMPANY']),
  document: z.string().min(1),
  document_2: z.string().optional(),
  email: z.string().email().min(1),
  state_registration: z.string().optional(),
  tax_free: z.boolean().optional(),
  gender: z.enum(['MALE', 'FEMALE']).optional(),
  birth_date: z.string().datetime({ offset: true }).optional(),
  recipient_name: z.string().min(1),
  recipient_phone: z.string().min(1),
  cep: z.string().min(1),
  street: z.string().min(1),
  number: z.string().min(1),
  complement: z.string().optional(),
  neighborhood: z.string().min(1),
  city: z.string().min(1),
  state: z.string().min(1),
}) as unknown as ToZod<PostEmployeesMutationRequestType>

export const postEmployeesMutationResponseSchema = z.lazy(
  () => postEmployees201Schema
) as unknown as ToZod<PostEmployeesMutationResponseType>
