/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteProductsIdPathParamsType = {
  /**
   * @type string
   */
  id: string
}

export const deleteProductsId200Enum = {
  null: 'null',
} as const

export type DeleteProductsId200EnumType =
  (typeof deleteProductsId200Enum)[keyof typeof deleteProductsId200Enum]

/**
 * @description Produto deletado com sucesso.
 */
export type DeleteProductsId200Type = DeleteProductsId200EnumType | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteProductsId401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Produto não encontrado.
 */
export type DeleteProductsId404Type = {
  /**
   * @type string
   */
  message: string
}

export type DeleteProductsIdMutationResponseType = DeleteProductsId200Type

export type DeleteProductsIdTypeMutation = {
  Response: DeleteProductsId200Type
  PathParams: DeleteProductsIdPathParamsType
  Errors: DeleteProductsId401Type | DeleteProductsId404Type
}
