/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Produto cadastrado com sucesso.
 */
export type PostProductsUpload201Type = {
  /**
   * @type string
   */
  fileUrl: string
}

/**
 * @description Imagem inválida.
 */
export type PostProductsUpload400Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Usuário não autenticado.
 */
export type PostProductsUpload401Type = {
  /**
   * @type string
   */
  message: string
}

export type PostProductsUploadMutationRequestType = {
  file?: unknown
}

export type PostProductsUploadMutationResponseType = PostProductsUpload201Type

export type PostProductsUploadTypeMutation = {
  Response: PostProductsUpload201Type
  Request: PostProductsUploadMutationRequestType
  Errors: PostProductsUpload400Type | PostProductsUpload401Type
}