/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const postProducts201Enum = {
  null: 'null',
} as const

export type PostProducts201EnumType =
  (typeof postProducts201Enum)[keyof typeof postProducts201Enum]

/**
 * @description Produto cadastrado com sucesso.
 */
export type PostProducts201Type = PostProducts201EnumType | null

/**
 * @description Usuário não autenticado.
 */
export type PostProducts401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Fornecedor, marca, categoria ou unidade comercial não encontrado.
 */
export type PostProducts404Type = {
  /**
   * @type string
   */
  message: string
}

export type PostProductsMutationRequestType = {
  /**
   * @type string | undefined
   */
  supplier_id?: string
  /**
   * @type string | undefined
   */
  product_measurement_unit_id?: string
  /**
   * @type string
   */
  product_brand_id: string
  /**
   * @type array | undefined
   */
  product_category_ids?: {
    /**
     * @type string
     */
    id: string
  }[]
  /**
   * @minLength 1
   * @type string
   */
  reference_code: string
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @type string | undefined
   */
  model?: string
  /**
   * @type string | undefined
   */
  description?: string
  /**
   * @type integer | undefined
   */
  ncm?: number
  /**
   * @type integer | undefined
   */
  cfop?: number
  /**
   * @type string | undefined
   */
  cest?: string
  /**
   * @type string | undefined
   */
  merchandise_origin?: string
}

export type PostProductsMutationResponseType = PostProducts201Type

export type PostProductsTypeMutation = {
  Response: PostProducts201Type
  Request: PostProductsMutationRequestType
  Errors: PostProducts401Type | PostProducts404Type
}
