/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PutProductsIdPathParamsType = {
  /**
   * @type string
   */
  id: string
}

export const putProductsId200Enum = {
  null: 'null',
} as const

export type PutProductsId200EnumType =
  (typeof putProductsId200Enum)[keyof typeof putProductsId200Enum]

/**
 * @description Produto atualizado com sucesso.
 */
export type PutProductsId200Type = PutProductsId200EnumType | null

/**
 * @description Usuário não autenticado.
 */
export type PutProductsId401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Produto, marca ou fornecedor não encontrado.
 */
export type PutProductsId404Type = {
  /**
   * @type string
   */
  message: string
}

export type PutProductsIdMutationRequestType = {
  /**
   * @type string | undefined
   */
  supplier_id?: string
  /**
   * @type string | undefined
   */
  product_measurement_unit_id?: string
  /**
   * @type string | undefined
   */
  product_brand_id?: string
  /**
   * @type array | undefined
   */
  product_category_ids?: {
    /**
     * @type string
     */
    id: string
  }[]
  /**
   * @minLength 1
   * @type string
   */
  reference_code: string
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @type string | undefined
   */
  model?: string
  /**
   * @type string | undefined
   */
  description?: string
  /**
   * @type integer | undefined
   */
  ncm?: number
  /**
   * @type integer | undefined
   */
  cfop?: number
  /**
   * @type string | undefined
   */
  cest?: string
  /**
   * @type string | undefined
   */
  merchandise_origin?: string
}

export type PutProductsIdMutationResponseType = PutProductsId200Type

export type PutProductsIdTypeMutation = {
  Response: PutProductsId200Type
  Request: PutProductsIdMutationRequestType
  PathParams: PutProductsIdPathParamsType
  Errors: PutProductsId401Type | PutProductsId404Type
}
