/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from '@kubb/plugin-zod/utils'
import type {
  DeleteOrdersIdPathParamsType,
  DeleteOrdersId200Type,
  DeleteOrdersId401Type,
  DeleteOrdersId404Type,
  DeleteOrdersIdMutationResponseType,
} from '../../types/orders/DeleteOrdersIdType'
import { z } from 'zod'

export const deleteOrdersIdPathParamsSchema = z.object({
  id: z.string(),
}) as unknown as ToZod<DeleteOrdersIdPathParamsType>

/**
 * @description Pedido deletado com sucesso.
 */
export const deleteOrdersId200Schema = z.enum(['null']).describe('Pedido deletado com sucesso.').nullable() as unknown as ToZod<DeleteOrdersId200Type>

/**
 * @description Usuário não autenticado.
 */
export const deleteOrdersId401Schema = z
  .object({
    message: z.string(),
  })
  .describe('Usuário não autenticado.') as unknown as ToZod<DeleteOrdersId401Type>

/**
 * @description Pedido não encontrado.
 */
export const deleteOrdersId404Schema = z
  .object({
    message: z.string(),
  })
  .describe('Pedido não encontrado.') as unknown as ToZod<DeleteOrdersId404Type>

export const deleteOrdersIdMutationResponseSchema = z.lazy(() => deleteOrdersId200Schema) as unknown as ToZod<DeleteOrdersIdMutationResponseType>