/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from '@kubb/plugin-zod/utils'
import type {
  PutOrdersIdPathParamsType,
  PutOrdersId200Type,
  PutOrdersId400Type,
  PutOrdersId401Type,
  PutOrdersId404Type,
  PutOrdersIdMutationRequestType,
  PutOrdersIdMutationResponseType,
} from '../../types/PedidosTypes/PutOrdersIdType.ts'
import { z } from 'zod'

export const putOrdersIdPathParamsSchema = z.object({
  id: z.string(),
}) as unknown as ToZod<PutOrdersIdPathParamsType>

/**
 * @description Pedido atualizado com sucesso.
 */
export const putOrdersId200Schema = z.enum(['null']).describe('Pedido atualizado com sucesso.').nullable() as unknown as ToZod<PutOrdersId200Type>

/**
 * @description Dados inválidos.
 */
export const putOrdersId400Schema = z
  .object({
    message: z.string(),
  })
  .describe('Dados inválidos.') as unknown as ToZod<PutOrdersId400Type>

/**
 * @description Usuário não autenticado.
 */
export const putOrdersId401Schema = z
  .object({
    message: z.string(),
  })
  .describe('Usuário não autenticado.') as unknown as ToZod<PutOrdersId401Type>

/**
 * @description Pedido não encontrado.
 */
export const putOrdersId404Schema = z
  .object({
    message: z.string(),
  })
  .describe('Pedido não encontrado.') as unknown as ToZod<PutOrdersId404Type>

export const putOrdersIdMutationRequestSchema = z.object({
  customer_id: z.string().min(1),
  address_id: z.string().min(1),
  status: z.enum(['PROCESSED', 'CANCELLED']).default('PROCESSED'),
  shipping_carrier: z.enum(['CORREIOS', 'JADLOG']).default('CORREIOS'),
  payment_method: z.enum(['CREDIT_CARD', 'DEBIT_CARD', 'PIX']),
  shipping_cost: z.number().min(0).default(0),
  items: z
    .array(
      z.object({
        product_variation_id: z.string().min(1),
        quantity: z.number().min(1),
        discount: z.number().min(0),
      }),
    )
    .min(1),
  return_previous_items_to_stock: z.boolean().default(true).describe('Retornar itens do pedido anterior ao estoque'),
  remove_current_items_from_stock: z.boolean().default(true).describe('Remover itens do novo pedido do estoque'),
}) as unknown as ToZod<PutOrdersIdMutationRequestType>

export const putOrdersIdMutationResponseSchema = z.lazy(() => putOrdersId200Schema) as unknown as ToZod<PutOrdersIdMutationResponseType>