/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteSuppliersIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const deleteSuppliersId200Enum = {
  null: 'null',
} as const

export type DeleteSuppliersId200Enum = (typeof deleteSuppliersId200Enum)[keyof typeof deleteSuppliersId200Enum]

/**
 * @description Fornecedor deletado com sucesso.
 */
export type DeleteSuppliersId200 = DeleteSuppliersId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteSuppliersId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Fornecedor não encontrado.
 */
export type DeleteSuppliersId404 = {
  /**
   * @type string
   */
  message: string
}

export type DeleteSuppliersIdMutationResponse = DeleteSuppliersId200

export type DeleteSuppliersIdMutation = {
  Response: DeleteSuppliersId200
  PathParams: DeleteSuppliersIdPathParams
  Errors: DeleteSuppliersId401 | DeleteSuppliersId404
}