/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteProductsCategoriesIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const deleteProductsCategoriesId200Enum = {
  null: 'null',
} as const

export type DeleteProductsCategoriesId200Enum = (typeof deleteProductsCategoriesId200Enum)[keyof typeof deleteProductsCategoriesId200Enum]

/**
 * @description Categoria deletada com sucesso.
 */
export type DeleteProductsCategoriesId200 = DeleteProductsCategoriesId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteProductsCategoriesId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Categoria não encontrado.
 */
export type DeleteProductsCategoriesId404 = {
  /**
   * @type string
   */
  message: string
}

export type DeleteProductsCategoriesIdMutationResponse = DeleteProductsCategoriesId200

export type DeleteProductsCategoriesIdMutation = {
  Response: DeleteProductsCategoriesId200
  PathParams: DeleteProductsCategoriesIdPathParams
  Errors: DeleteProductsCategoriesId401 | DeleteProductsCategoriesId404
}