/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteCustomersIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const deleteCustomersId200Enum = {
  null: 'null',
} as const

export type DeleteCustomersId200Enum = (typeof deleteCustomersId200Enum)[keyof typeof deleteCustomersId200Enum]

/**
 * @description Cliente deletado com sucesso.
 */
export type DeleteCustomersId200 = DeleteCustomersId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteCustomersId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Cliente não encontrado.
 */
export type DeleteCustomersId404 = {
  /**
   * @type string
   */
  message: string
}

export type DeleteCustomersIdMutationResponse = DeleteCustomersId200

export type DeleteCustomersIdMutation = {
  Response: DeleteCustomersId200
  PathParams: DeleteCustomersIdPathParams
  Errors: DeleteCustomersId401 | DeleteCustomersId404
}