/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteProductsAttributesNamesIdPathParamsType = {
  /**
   * @type string
   */
  id: string
}

export const deleteProductsAttributesNamesId200Enum = {
  null: 'null',
} as const

export type DeleteProductsAttributesNamesId200EnumType = (typeof deleteProductsAttributesNamesId200Enum)[keyof typeof deleteProductsAttributesNamesId200Enum]

/**
 * @description Nome de atributo do produto deletado com sucesso.
 */
export type DeleteProductsAttributesNamesId200Type = DeleteProductsAttributesNamesId200EnumType | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteProductsAttributesNamesId401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Nome de atributo do produto não encontrado.
 */
export type DeleteProductsAttributesNamesId404Type = {
  /**
   * @type string
   */
  message: string
}

export type DeleteProductsAttributesNamesIdMutationResponseType = DeleteProductsAttributesNamesId200Type

export type DeleteProductsAttributesNamesIdTypeMutation = {
  Response: DeleteProductsAttributesNamesId200Type
  PathParams: DeleteProductsAttributesNamesIdPathParamsType
  Errors: DeleteProductsAttributesNamesId401Type | DeleteProductsAttributesNamesId404Type
}