/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteProductsVariationsIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const deleteProductsVariationsId200Enum = {
  null: 'null',
} as const

export type DeleteProductsVariationsId200Enum = (typeof deleteProductsVariationsId200Enum)[keyof typeof deleteProductsVariationsId200Enum]

/**
 * @description Variação de produto deletado com sucesso.
 */
export type DeleteProductsVariationsId200 = DeleteProductsVariationsId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteProductsVariationsId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Variação de produto não encontrado.
 */
export type DeleteProductsVariationsId404 = {
  /**
   * @type string
   */
  message: string
}

export type DeleteProductsVariationsIdMutationResponse = DeleteProductsVariationsId200

export type DeleteProductsVariationsIdMutation = {
  Response: DeleteProductsVariationsId200
  PathParams: DeleteProductsVariationsIdPathParams
  Errors: DeleteProductsVariationsId401 | DeleteProductsVariationsId404
}