/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteProductsIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const deleteProductsId200Enum = {
  null: 'null',
} as const

export type DeleteProductsId200Enum = (typeof deleteProductsId200Enum)[keyof typeof deleteProductsId200Enum]

/**
 * @description Produto deletado com sucesso.
 */
export type DeleteProductsId200 = DeleteProductsId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteProductsId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Produto não encontrado.
 */
export type DeleteProductsId404 = {
  /**
   * @type string
   */
  message: string
}

export type DeleteProductsIdMutationResponse = DeleteProductsId200

export type DeleteProductsIdMutation = {
  Response: DeleteProductsId200
  PathParams: DeleteProductsIdPathParams
  Errors: DeleteProductsId401 | DeleteProductsId404
}