/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteProductsBrandsIdPathParamsType = {
  /**
   * @type string
   */
  id: string
}

export const deleteProductsBrandsId200Enum = {
  null: 'null',
} as const

export type DeleteProductsBrandsId200EnumType = (typeof deleteProductsBrandsId200Enum)[keyof typeof deleteProductsBrandsId200Enum]

/**
 * @description Marca deletada com sucesso.
 */
export type DeleteProductsBrandsId200Type = DeleteProductsBrandsId200EnumType | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteProductsBrandsId401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Marca não encontrado.
 */
export type DeleteProductsBrandsId404Type = {
  /**
   * @type string
   */
  message: string
}

export type DeleteProductsBrandsIdMutationResponseType = DeleteProductsBrandsId200Type

export type DeleteProductsBrandsIdTypeMutation = {
  Response: DeleteProductsBrandsId200Type
  PathParams: DeleteProductsBrandsIdPathParamsType
  Errors: DeleteProductsBrandsId401Type | DeleteProductsBrandsId404Type
}