/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteEmployeesIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const deleteEmployeesId200Enum = {
  null: 'null',
} as const

export type DeleteEmployeesId200Enum = (typeof deleteEmployeesId200Enum)[keyof typeof deleteEmployeesId200Enum]

/**
 * @description Colaborador deletado com sucesso.
 */
export type DeleteEmployeesId200 = DeleteEmployeesId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteEmployeesId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Colaborador não encontrado.
 */
export type DeleteEmployeesId404 = {
  /**
   * @type string
   */
  message: string
}

export type DeleteEmployeesIdMutationResponse = DeleteEmployeesId200

export type DeleteEmployeesIdMutation = {
  Response: DeleteEmployeesId200
  PathParams: DeleteEmployeesIdPathParams
  Errors: DeleteEmployeesId401 | DeleteEmployeesId404
}