/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteProductsBrandsIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const deleteProductsBrandsId200Enum = {
  null: 'null',
} as const

export type DeleteProductsBrandsId200Enum = (typeof deleteProductsBrandsId200Enum)[keyof typeof deleteProductsBrandsId200Enum]

/**
 * @description Marca deletada com sucesso.
 */
export type DeleteProductsBrandsId200 = DeleteProductsBrandsId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type DeleteProductsBrandsId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Marca não encontrado.
 */
export type DeleteProductsBrandsId404 = {
  /**
   * @type string
   */
  message: string
}

export type DeleteProductsBrandsIdMutationResponse = DeleteProductsBrandsId200

export type DeleteProductsBrandsIdMutation = {
  Response: DeleteProductsBrandsId200
  PathParams: DeleteProductsBrandsIdPathParams
  Errors: DeleteProductsBrandsId401 | DeleteProductsBrandsId404
}