/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type FileUploadType = {
  /**
   * @description Arquivo de imagem a ser enviado
   * @type string | undefined, binary
   */
  file?: Blob
}
