/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const getCustomersQueryParamsOrderByEnum = {
  desc: 'desc',
  asc: 'asc',
} as const

export type GetCustomersQueryParamsOrderByEnum = (typeof getCustomersQueryParamsOrderByEnum)[keyof typeof getCustomersQueryParamsOrderByEnum]

export type GetCustomersQueryParams = {
  /**
   * @default 10
   * @type number | undefined
   */
  perPage?: number
  /**
   * @default 0
   * @type number | undefined
   */
  pageIndex?: number
  /**
   * @default "desc"
   * @type string | undefined
   */
  orderBy?: GetCustomersQueryParamsOrderByEnum
  /**
   * @type string | undefined
   */
  customerName?: string
  /**
   * @type string | undefined
   */
  customerDocument?: string
}

export const customersDocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type CustomersDocumentTypeEnum = (typeof customersDocumentTypeEnum)[keyof typeof customersDocumentTypeEnum]

/**
 * @description Clientes obtidos com sucesso.
 */
export type GetCustomers200 = {
  /**
   * @type number
   */
  totalCount: number
  /**
   * @type number
   */
  pageCount: number
  /**
   * @type array
   */
  customers: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    name: string
    /**
     * @type string
     */
    document_type: CustomersDocumentTypeEnum
    /**
     * @type string
     */
    document: string
    /**
     * @type string
     */
    user_id: string
    /**
     * @type number
     */
    entry_number: number
    /**
     * @type string
     */
    person_id: string
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetCustomers401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Cliente não encontrado.
 */
export type GetCustomers404 = {
  /**
   * @type string
   */
  message: string
}

export type GetCustomersQueryResponse = GetCustomers200

export type GetCustomersQuery = {
  Response: GetCustomers200
  QueryParams: GetCustomersQueryParams
  Errors: GetCustomers401 | GetCustomers404
}