/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const getEmployeesQueryParamsOrderByEnum = {
  desc: 'desc',
  asc: 'asc',
} as const

export type GetEmployeesQueryParamsOrderByEnumType = (typeof getEmployeesQueryParamsOrderByEnum)[keyof typeof getEmployeesQueryParamsOrderByEnum]

export type GetEmployeesQueryParamsType = {
  /**
   * @default 10
   * @type number | undefined
   */
  perPage?: number
  /**
   * @default 0
   * @type number | undefined
   */
  pageIndex?: number
  /**
   * @default "desc"
   * @type string | undefined
   */
  orderBy?: GetEmployeesQueryParamsOrderByEnumType
  /**
   * @type string | undefined
   */
  employeeName?: string
  /**
   * @type string | undefined
   */
  employeeDocument?: string
}

export const employeesDocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type EmployeesDocumentTypeEnumType = (typeof employeesDocumentTypeEnum)[keyof typeof employeesDocumentTypeEnum]

/**
 * @description Colaboradores obtidos com sucesso.
 */
export type GetEmployees200Type = {
  /**
   * @type number
   */
  totalCount: number
  /**
   * @type number
   */
  pageCount: number
  /**
   * @type array
   */
  employees: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    name: string
    /**
     * @type string
     */
    document_type: EmployeesDocumentTypeEnumType
    /**
     * @type string
     */
    document: string
    /**
     * @type string
     */
    user_id: string
    /**
     * @type number
     */
    entry_number: number
    /**
     * @type string
     */
    person_id: string
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetEmployees401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Colaborador não encontrado.
 */
export type GetEmployees404Type = {
  /**
   * @type string
   */
  message: string
}

export type GetEmployeesQueryResponseType = GetEmployees200Type

export type GetEmployeesTypeQuery = {
  Response: GetEmployees200Type
  QueryParams: GetEmployeesQueryParamsType
  Errors: GetEmployees401Type | GetEmployees404Type
}