/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetEmployeesIdPathParamsType = {
  /**
   * @type string
   */
  id: string
}

export const getEmployeesId200DocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type GetEmployeesId200DocumentTypeEnumType = (typeof getEmployeesId200DocumentTypeEnum)[keyof typeof getEmployeesId200DocumentTypeEnum]

export const getEmployeesId200GenderEnum = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const

export type GetEmployeesId200GenderEnumType = (typeof getEmployeesId200GenderEnum)[keyof typeof getEmployeesId200GenderEnum]

export const addressesPlatformEnum3 = {
  SHOPEE: 'SHOPEE',
  MERCADO_LIVRE: 'MERCADO_LIVRE',
  TRAY: 'TRAY',
  LOCAL: 'LOCAL',
} as const

export type AddressesPlatformEnum3Type = (typeof addressesPlatformEnum3)[keyof typeof addressesPlatformEnum3]

/**
 * @description Colaborador obtido com sucesso.
 */
export type GetEmployeesId200Type = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  phone: string
  /**
   * @type string
   */
  phone_2: string | null
  /**
   * @type string
   */
  document_type: GetEmployeesId200DocumentTypeEnumType
  /**
   * @type string
   */
  document: string
  /**
   * @type string
   */
  document_2: string | null
  /**
   * @type string, email
   */
  email: string | null
  /**
   * @type string
   */
  state_registration: string | null
  /**
   * @type boolean
   */
  tax_free: boolean
  /**
   * @type string, date-time
   */
  created_at: string
  /**
   * @type string, date-time
   */
  updated_at: string
  /**
   * @type string
   */
  user_id: string
  /**
   * @type number
   */
  entry_number: number
  /**
   * @type string
   */
  gender: GetEmployeesId200GenderEnumType | null
  /**
   * @type string, date-time
   */
  birth_date: string | null
  /**
   * @type string
   */
  person_id: string
  /**
   * @type array
   */
  addresses: {
    /**
     * @type string
     */
    number: string
    /**
     * @type string
     */
    id: string
    /**
     * @type string, date-time
     */
    created_at: string
    /**
     * @type string, date-time
     */
    updated_at: string
    /**
     * @type string
     */
    recipient_name: string
    /**
     * @type string
     */
    recipient_phone: string
    /**
     * @type string
     */
    cep: string
    /**
     * @type string
     */
    street: string
    /**
     * @type string
     */
    complement: string | null
    /**
     * @type string
     */
    neighborhood: string
    /**
     * @type string
     */
    city: string
    /**
     * @type string
     */
    state: string
    /**
     * @type string
     */
    platform: AddressesPlatformEnum3Type
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetEmployeesId401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Colaborador não encontrado.
 */
export type GetEmployeesId404Type = {
  /**
   * @type string
   */
  message: string
}

export type GetEmployeesIdQueryResponseType = GetEmployeesId200Type

export type GetEmployeesIdTypeQuery = {
  Response: GetEmployeesId200Type
  PathParams: GetEmployeesIdPathParamsType
  Errors: GetEmployeesId401Type | GetEmployeesId404Type
}