/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetEmployeesIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const getEmployeesId200DocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type GetEmployeesId200DocumentTypeEnum = (typeof getEmployeesId200DocumentTypeEnum)[keyof typeof getEmployeesId200DocumentTypeEnum]

export const getEmployeesId200GenderEnum = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const

export type GetEmployeesId200GenderEnum = (typeof getEmployeesId200GenderEnum)[keyof typeof getEmployeesId200GenderEnum]

export const addressesPlatformEnum3 = {
  SHOPEE: 'SHOPEE',
  MERCADO_LIVRE: 'MERCADO_LIVRE',
  TRAY: 'TRAY',
  LOCAL: 'LOCAL',
} as const

export type AddressesPlatformEnum3 = (typeof addressesPlatformEnum3)[keyof typeof addressesPlatformEnum3]

/**
 * @description Colaborador obtido com sucesso.
 */
export type GetEmployeesId200 = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  phone: string
  /**
   * @type string
   */
  phone_2: string | null
  /**
   * @type string
   */
  document_type: GetEmployeesId200DocumentTypeEnum
  /**
   * @type string
   */
  document: string
  /**
   * @type string
   */
  document_2: string | null
  /**
   * @type string, email
   */
  email: string | null
  /**
   * @type string
   */
  state_registration: string | null
  /**
   * @type boolean
   */
  tax_free: boolean
  /**
   * @type string, date-time
   */
  created_at: string
  /**
   * @type string, date-time
   */
  updated_at: string
  /**
   * @type string
   */
  user_id: string
  /**
   * @type number
   */
  entry_number: number
  /**
   * @type string
   */
  gender: GetEmployeesId200GenderEnum | null
  /**
   * @type string, date-time
   */
  birth_date: string | null
  /**
   * @type string
   */
  person_id: string
  /**
   * @type array
   */
  addresses: {
    /**
     * @type string
     */
    number: string
    /**
     * @type string
     */
    id: string
    /**
     * @type string, date-time
     */
    created_at: string
    /**
     * @type string, date-time
     */
    updated_at: string
    /**
     * @type string
     */
    recipient_name: string
    /**
     * @type string
     */
    recipient_phone: string
    /**
     * @type string
     */
    cep: string
    /**
     * @type string
     */
    street: string
    /**
     * @type string
     */
    complement: string | null
    /**
     * @type string
     */
    neighborhood: string
    /**
     * @type string
     */
    city: string
    /**
     * @type string
     */
    state: string
    /**
     * @type string
     */
    platform: AddressesPlatformEnum3
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetEmployeesId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Colaborador não encontrado.
 */
export type GetEmployeesId404 = {
  /**
   * @type string
   */
  message: string
}

export type GetEmployeesIdQueryResponse = GetEmployeesId200

export type GetEmployeesIdQuery = {
  Response: GetEmployeesId200
  PathParams: GetEmployeesIdPathParams
  Errors: GetEmployeesId401 | GetEmployeesId404
}