/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const getEmployeesQueryParamsOrderByEnum = {
  desc: 'desc',
  asc: 'asc',
} as const

export type GetEmployeesQueryParamsOrderByEnum = (typeof getEmployeesQueryParamsOrderByEnum)[keyof typeof getEmployeesQueryParamsOrderByEnum]

export type GetEmployeesQueryParams = {
  /**
   * @default 10
   * @type number | undefined
   */
  perPage?: number
  /**
   * @default 0
   * @type number | undefined
   */
  pageIndex?: number
  /**
   * @default "desc"
   * @type string | undefined
   */
  orderBy?: GetEmployeesQueryParamsOrderByEnum
  /**
   * @type string | undefined
   */
  employeeName?: string
  /**
   * @type string | undefined
   */
  employeeDocument?: string
}

export const employeesDocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type EmployeesDocumentTypeEnum = (typeof employeesDocumentTypeEnum)[keyof typeof employeesDocumentTypeEnum]

/**
 * @description Colaboradores obtidos com sucesso.
 */
export type GetEmployees200 = {
  /**
   * @type number
   */
  totalCount: number
  /**
   * @type number
   */
  pageCount: number
  /**
   * @type array
   */
  employees: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    name: string
    /**
     * @type string
     */
    document_type: EmployeesDocumentTypeEnum
    /**
     * @type string
     */
    document: string
    /**
     * @type string
     */
    user_id: string
    /**
     * @type number
     */
    entry_number: number
    /**
     * @type string
     */
    person_id: string
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetEmployees401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Colaborador não encontrado.
 */
export type GetEmployees404 = {
  /**
   * @type string
   */
  message: string
}

export type GetEmployeesQueryResponse = GetEmployees200

export type GetEmployeesQuery = {
  Response: GetEmployees200
  QueryParams: GetEmployeesQueryParams
  Errors: GetEmployees401 | GetEmployees404
}