/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const getOrdersQueryParamsOrderByEnum = {
  asc: 'asc',
  desc: 'desc',
} as const

export type GetOrdersQueryParamsOrderByEnum = (typeof getOrdersQueryParamsOrderByEnum)[keyof typeof getOrdersQueryParamsOrderByEnum]

export const getOrdersQueryParamsStatusEnum = {
  PROCESSED: 'PROCESSED',
  CANCELLED: 'CANCELLED',
} as const

export type GetOrdersQueryParamsStatusEnum = (typeof getOrdersQueryParamsStatusEnum)[keyof typeof getOrdersQueryParamsStatusEnum]

export type GetOrdersQueryParams = {
  /**
   * @default "10"
   * @type string | undefined
   */
  perPage?: string
  /**
   * @default "0"
   * @type string | undefined
   */
  pageIndex?: string
  /**
   * @default "desc"
   * @type string | undefined
   */
  orderBy?: GetOrdersQueryParamsOrderByEnum
  /**
   * @type string | undefined
   */
  status?: GetOrdersQueryParamsStatusEnum
  /**
   * @type string | undefined
   */
  orderId?: string
  /**
   * @type string | undefined
   */
  platformOrderId?: string
  /**
   * @type string | undefined, date-time
   */
  timeFrom?: string
  /**
   * @type string | undefined, date-time
   */
  timeTo?: string
}

/**
 * @description Default Response
 */
export type GetOrders200 = {
  /**
   * @type number
   */
  totalCount: number
  /**
   * @type number
   */
  pageCount: number
  /**
   * @type array
   */
  orders: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    status: string
    /**
     * @type string
     */
    shipping_carrier: string
    /**
     * @type string, date-time
     */
    order_placed_at: string
    /**
     * @type string, date-time
     */
    created_at: string
    /**
     * @type string, date-time
     */
    updated_at: string
  }[]
}

export type GetOrdersQueryResponse = GetOrders200

export type GetOrdersQuery = {
  Response: GetOrders200
  QueryParams: GetOrdersQueryParams
  Errors: any
}