/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetProductsIdPathParams = {
  /**
   * @type string
   */
  id: string
}

/**
 * @description Produto obtido com sucesso.
 */
export type GetProductsId200 = {
  /**
   * @type string
   */
  id: string
  /**
   * @minLength 1
   * @type string
   */
  reference_code: string
  /**
   * @minLength 1
   * @type string
   */
  product_sku: string
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @type string
   */
  model: string | null
  /**
   * @type string
   */
  description: string | null
  /**
   * @type integer
   */
  ncm: number | null
  /**
   * @type integer
   */
  cfop: number | null
  /**
   * @type string
   */
  cest: string | null
  /**
   * @type string
   */
  merchandise_origin: string | null
  /**
   * @type string, date-time
   */
  created_at: string
  /**
   * @type string, date-time
   */
  updated_at: string
  /**
   * @type object
   */
  product_measurement_unit: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    name: string
    /**
     * @type string
     */
    acronym: string
  } | null
  /**
   * @type object
   */
  product_brand: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    name: string
    /**
     * @type string
     */
    reference_code: string
    /**
     * @type string, date-time
     */
    created_at: string
  } | null
  /**
   * @type array
   */
  product_categories: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    name: string
    /**
     * @type string, date-time
     */
    created_at: string
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetProductsId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Produto não encontrado.
 */
export type GetProductsId404 = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsIdQueryResponse = GetProductsId200

export type GetProductsIdQuery = {
  Response: GetProductsId200
  PathParams: GetProductsIdPathParams
  Errors: GetProductsId401 | GetProductsId404
}