/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetProductsVariationsIdPathParamsType = {
  /**
   * @type string
   */
  id: string
}

/**
 * @description Variação de produto obtido com sucesso.
 */
export type GetProductsVariationsId200Type = {
  /**
   * @type string
   */
  product_id: string
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  barcode: string | null
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @type number
   */
  average_cost: number
  /**
   * @type number
   */
  cost_price: number
  /**
   * @type number
   */
  selling_price: number
  /**
   * @type string
   */
  product_storage_location: string | null
  /**
   * @type number
   */
  current_stock: number
  /**
   * @type number
   */
  minimum_stock_level: number
  /**
   * @type number
   */
  products_in_review: number
  /**
   * @type boolean | undefined
   */
  track_inventory?: boolean
  /**
   * @type boolean | undefined
   */
  is_available?: boolean
  /**
   * @type array
   */
  product_attribute_names: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    name: string
    /**
     * @type array
     */
    product_attribute_values: {
      /**
       * @type string
       */
      id: string
      /**
       * @type string
       */
      value: string
    }[]
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetProductsVariationsId401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Variação de produto não encontrado.
 */
export type GetProductsVariationsId404Type = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsVariationsIdQueryResponseType = GetProductsVariationsId200Type

export type GetProductsVariationsIdTypeQuery = {
  Response: GetProductsVariationsId200Type
  PathParams: GetProductsVariationsIdPathParamsType
  Errors: GetProductsVariationsId401Type | GetProductsVariationsId404Type
}