/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const getProductsAttributesNamesQueryParamsOrderByEnum = {
  desc: 'desc',
  asc: 'asc',
} as const

export type GetProductsAttributesNamesQueryParamsOrderByEnum =
  (typeof getProductsAttributesNamesQueryParamsOrderByEnum)[keyof typeof getProductsAttributesNamesQueryParamsOrderByEnum]

export type GetProductsAttributesNamesQueryParams = {
  /**
   * @default 10
   * @type number | undefined
   */
  perPage?: number
  /**
   * @default 0
   * @type number | undefined
   */
  pageIndex?: number
  /**
   * @default "desc"
   * @type string | undefined
   */
  orderBy?: GetProductsAttributesNamesQueryParamsOrderByEnum
  /**
   * @type string | undefined
   */
  attributeName?: string
}

/**
 * @description Nomes dos atributos dos produtos obtidos com sucesso.
 */
export type GetProductsAttributesNames200 = {
  /**
   * @type number
   */
  totalCount: number
  /**
   * @type number
   */
  pageCount: number
  /**
   * @type array
   */
  productAttributeNames: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    name: string
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetProductsAttributesNames401 = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsAttributesNamesQueryResponse = GetProductsAttributesNames200

export type GetProductsAttributesNamesQuery = {
  Response: GetProductsAttributesNames200
  QueryParams: GetProductsAttributesNamesQueryParams
  Errors: GetProductsAttributesNames401
}