/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Unidades de medida de produtos obtidas com sucesso.
 */
export type GetProductsMeasurementUnits200 = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  acronym: string
}[]

/**
 * @description Usuário não autenticado.
 */
export type GetProductsMeasurementUnits401 = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsMeasurementUnitsQueryResponse = GetProductsMeasurementUnits200

export type GetProductsMeasurementUnitsQuery = {
  Response: GetProductsMeasurementUnits200
  Errors: GetProductsMeasurementUnits401
}