/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Categorias de produtos obtidas com sucesso.
 */
export type GetProductsCategories200 = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  name: string
}[]

/**
 * @description Usuário não autenticado.
 */
export type GetProductsCategories401 = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsCategoriesQueryResponse = GetProductsCategories200

export type GetProductsCategoriesQuery = {
  Response: GetProductsCategories200
  Errors: GetProductsCategories401
}