/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const getProductsAttributesValuesQueryParamsOrderByEnum = {
  desc: 'desc',
  asc: 'asc',
} as const

export type GetProductsAttributesValuesQueryParamsOrderByEnum =
  (typeof getProductsAttributesValuesQueryParamsOrderByEnum)[keyof typeof getProductsAttributesValuesQueryParamsOrderByEnum]

export type GetProductsAttributesValuesQueryParams = {
  /**
   * @type string
   */
  productAttributeNameId: string
  /**
   * @default 10
   * @type number | undefined
   */
  perPage?: number
  /**
   * @default 0
   * @type number | undefined
   */
  pageIndex?: number
  /**
   * @default "desc"
   * @type string | undefined
   */
  orderBy?: GetProductsAttributesValuesQueryParamsOrderByEnum
  /**
   * @type string | undefined
   */
  attributeValue?: string
}

/**
 * @description Valores dos atributos dos produtos obtidos com sucesso.
 */
export type GetProductsAttributesValues200 = {
  /**
   * @type number
   */
  totalCount: number
  /**
   * @type number
   */
  pageCount: number
  /**
   * @type array
   */
  productAttributeValues: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    value: string
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetProductsAttributesValues401 = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsAttributesValuesQueryResponse = GetProductsAttributesValues200

export type GetProductsAttributesValuesQuery = {
  Response: GetProductsAttributesValues200
  QueryParams: GetProductsAttributesValuesQueryParams
  Errors: GetProductsAttributesValues401
}