/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetProductsAttributesNamesIdPathParams = {
  /**
   * @type string
   */
  id: string
}

/**
 * @description Nome de atributo do produto obtido com sucesso.
 */
export type GetProductsAttributesNamesId200 = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  name: string
  /**
   * @type string, date-time
   */
  created_at: string
}

/**
 * @description Usuário não autenticado.
 */
export type GetProductsAttributesNamesId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Nome de atributo do produto não encontrado.
 */
export type GetProductsAttributesNamesId404 = {
  /**
   * @type string
   */
  message: string
}

export type GetProductsAttributesNamesIdQueryResponse = GetProductsAttributesNamesId200

export type GetProductsAttributesNamesIdQuery = {
  Response: GetProductsAttributesNamesId200
  PathParams: GetProductsAttributesNamesIdPathParams
  Errors: GetProductsAttributesNamesId401 | GetProductsAttributesNamesId404
}