/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Default Response
 */
export type GetShopeeAuthUrl200 = {
  /**
   * @type string
   */
  url: string
}

/**
 * @description Usuário não autenticado.
 */
export type GetShopeeAuthUrl401 = {
  /**
   * @type string
   */
  message: string
}

export type GetShopeeAuthUrlQueryResponse = GetShopeeAuthUrl200

export type GetShopeeAuthUrlQuery = {
  Response: GetShopeeAuthUrl200
  Errors: GetShopeeAuthUrl401
}