/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const getSuppliersQueryParamsOrderByEnum = {
  desc: 'desc',
  asc: 'asc',
} as const

export type GetSuppliersQueryParamsOrderByEnum = (typeof getSuppliersQueryParamsOrderByEnum)[keyof typeof getSuppliersQueryParamsOrderByEnum]

export type GetSuppliersQueryParams = {
  /**
   * @default 10
   * @type number | undefined
   */
  perPage?: number
  /**
   * @default 0
   * @type number | undefined
   */
  pageIndex?: number
  /**
   * @default "desc"
   * @type string | undefined
   */
  orderBy?: GetSuppliersQueryParamsOrderByEnum
  /**
   * @type string | undefined
   */
  supplierName?: string
  /**
   * @type string | undefined
   */
  supplierDocument?: string
}

export const suppliersDocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type SuppliersDocumentTypeEnum = (typeof suppliersDocumentTypeEnum)[keyof typeof suppliersDocumentTypeEnum]

/**
 * @description Fornecedores obtidos com sucesso.
 */
export type GetSuppliers200 = {
  /**
   * @type number
   */
  totalCount: number
  /**
   * @type number
   */
  pageCount: number
  /**
   * @type array
   */
  suppliers: {
    /**
     * @type string
     */
    id: string
    /**
     * @type string
     */
    name: string
    /**
     * @type string
     */
    document_type: SuppliersDocumentTypeEnum
    /**
     * @type string
     */
    document: string
    /**
     * @type string
     */
    user_id: string
    /**
     * @type number
     */
    entry_number: number
    /**
     * @type string
     */
    person_id: string
  }[]
}

/**
 * @description Usuário não autenticado.
 */
export type GetSuppliers401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Fornecedor não encontrado.
 */
export type GetSuppliers404 = {
  /**
   * @type string
   */
  message: string
}

export type GetSuppliersQueryResponse = GetSuppliers200

export type GetSuppliersQuery = {
  Response: GetSuppliers200
  QueryParams: GetSuppliersQueryParams
  Errors: GetSuppliers401 | GetSuppliers404
}