/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const getUsersProfile200RoleEnum = {
  MEMBER: 'MEMBER',
  ADMIN: 'ADMIN',
} as const

export type GetUsersProfile200RoleEnum = (typeof getUsersProfile200RoleEnum)[keyof typeof getUsersProfile200RoleEnum]

/**
 * @description Informações do perfil do usuário obtidas com sucesso.
 */
export type GetUsersProfile200 = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  name: string
  /**
   * @type string, email
   */
  email: string
  /**
   * @type string
   */
  role: GetUsersProfile200RoleEnum
}

/**
 * @description Usuário não autenticado.
 */
export type GetUsersProfile401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Usuário não encontrado.
 */
export type GetUsersProfile404 = {
  /**
   * @type string
   */
  message: string
}

export type GetUsersProfileQueryResponse = GetUsersProfile200

export type GetUsersProfileQuery = {
  Response: GetUsersProfile200
  Errors: GetUsersProfile401 | GetUsersProfile404
}