/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const postProductsCategories201Enum = {
  null: 'null',
} as const

export type PostProductsCategories201Enum = (typeof postProductsCategories201Enum)[keyof typeof postProductsCategories201Enum]

/**
 * @description Categoria cadastrado com sucesso.
 */
export type PostProductsCategories201 = PostProductsCategories201Enum | null

/**
 * @description Usuário não autenticado.
 */
export type PostProductsCategories401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Categoria já cadastrado.
 */
export type PostProductsCategories409 = {
  /**
   * @type string
   */
  message: string
}

export type PostProductsCategoriesMutationRequest = {
  /**
   * @type string
   */
  name: string
}

export type PostProductsCategoriesMutationResponse = PostProductsCategories201

export type PostProductsCategoriesMutation = {
  Response: PostProductsCategories201
  Request: PostProductsCategoriesMutationRequest
  Errors: PostProductsCategories401 | PostProductsCategories409
}