/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const postProductsAttributesNames201Enum = {
  null: 'null',
} as const

export type PostProductsAttributesNames201EnumType = (typeof postProductsAttributesNames201Enum)[keyof typeof postProductsAttributesNames201Enum]

/**
 * @description Nome do atributo do produto cadastrado com sucesso.
 */
export type PostProductsAttributesNames201Type = PostProductsAttributesNames201EnumType | null

/**
 * @description Usuário não autenticado.
 */
export type PostProductsAttributesNames401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Nome do atributo do produto já cadastrado.
 */
export type PostProductsAttributesNames409Type = {
  /**
   * @type string
   */
  message: string
}

export type PostProductsAttributesNamesMutationRequestType = {
  /**
   * @type string
   */
  name: string
}

export type PostProductsAttributesNamesMutationResponseType = PostProductsAttributesNames201Type

export type PostProductsAttributesNamesTypeMutation = {
  Response: PostProductsAttributesNames201Type
  Request: PostProductsAttributesNamesMutationRequestType
  Errors: PostProductsAttributesNames401Type | PostProductsAttributesNames409Type
}