/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const postProductsAttributesNames201Enum = {
  null: 'null',
} as const

export type PostProductsAttributesNames201Enum = (typeof postProductsAttributesNames201Enum)[keyof typeof postProductsAttributesNames201Enum]

/**
 * @description Nome do atributo do produto cadastrado com sucesso.
 */
export type PostProductsAttributesNames201 = PostProductsAttributesNames201Enum | null

/**
 * @description Usuário não autenticado.
 */
export type PostProductsAttributesNames401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Nome do atributo do produto já cadastrado.
 */
export type PostProductsAttributesNames409 = {
  /**
   * @type string
   */
  message: string
}

export type PostProductsAttributesNamesMutationRequest = {
  /**
   * @type string
   */
  name: string
}

export type PostProductsAttributesNamesMutationResponse = PostProductsAttributesNames201

export type PostProductsAttributesNamesMutation = {
  Response: PostProductsAttributesNames201
  Request: PostProductsAttributesNamesMutationRequest
  Errors: PostProductsAttributesNames401 | PostProductsAttributesNames409
}