/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostShopeeOrderImportQueryParams = {
  /**
   * @type string
   */
  orderPeriodStartDate: string
  /**
   * @type string
   */
  orderPeriodEndDate: string
}

export const postShopeeOrderImport200Enum = {
  null: 'null',
} as const

export type PostShopeeOrderImport200Enum = (typeof postShopeeOrderImport200Enum)[keyof typeof postShopeeOrderImport200Enum]

/**
 * @description Pedidos importados com sucesso.
 */
export type PostShopeeOrderImport200 = PostShopeeOrderImport200Enum | null

/**
 * @description Erro ao importar pedidos.
 */
export type PostShopeeOrderImport400 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Usuário não autenticado.
 */
export type PostShopeeOrderImport401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Connection not found.
 */
export type PostShopeeOrderImport404 = {
  /**
   * @type string
   */
  message: string
}

export type PostShopeeOrderImportMutationResponse = PostShopeeOrderImport200

export type PostShopeeOrderImportMutation = {
  Response: PostShopeeOrderImport200
  QueryParams: PostShopeeOrderImportQueryParams
  Errors: PostShopeeOrderImport400 | PostShopeeOrderImport401 | PostShopeeOrderImport404
}