/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const postUsers201Enum = {
  null: 'null',
} as const

export type PostUsers201Enum = (typeof postUsers201Enum)[keyof typeof postUsers201Enum]

/**
 * @description Usuário cadastrado com sucesso.
 */
export type PostUsers201 = PostUsers201Enum | null

/**
 * @description Este email já está cadastrado em nossa base de dados.
 */
export type PostUsers409 = {
  /**
   * @type string
   */
  message: string
}

export type PostUsersMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @minLength 1
   * @type string, email
   */
  email: string
  /**
   * @minLength 6
   * @type string
   */
  password: string
}

export type PostUsersMutationResponse = PostUsers201

export type PostUsersMutation = {
  Response: PostUsers201
  Request: PostUsersMutationRequest
  Errors: PostUsers409
}