/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const postProductsAttributesValues201Enum = {
  null: 'null',
} as const

export type PostProductsAttributesValues201Enum = (typeof postProductsAttributesValues201Enum)[keyof typeof postProductsAttributesValues201Enum]

/**
 * @description Valor do atributo do produto cadastrado com sucesso.
 */
export type PostProductsAttributesValues201 = PostProductsAttributesValues201Enum | null

/**
 * @description Usuário não autenticado.
 */
export type PostProductsAttributesValues401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Valor do atributo do produto já cadastrado.
 */
export type PostProductsAttributesValues409 = {
  /**
   * @type string
   */
  message: string
}

export type PostProductsAttributesValuesMutationRequest = {
  /**
   * @type string
   */
  product_attribute_name_id: string
  /**
   * @type string
   */
  value: string
}

export type PostProductsAttributesValuesMutationResponse = PostProductsAttributesValues201

export type PostProductsAttributesValuesMutation = {
  Response: PostProductsAttributesValues201
  Request: PostProductsAttributesValuesMutationRequest
  Errors: PostProductsAttributesValues401 | PostProductsAttributesValues409
}