/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const postEmployees201Enum = {
  null: 'null',
} as const

export type PostEmployees201Enum = (typeof postEmployees201Enum)[keyof typeof postEmployees201Enum]

/**
 * @description Colaborador cadastrado com sucesso.
 */
export type PostEmployees201 = PostEmployees201Enum | null

/**
 * @description Usuário não autenticado.
 */
export type PostEmployees401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Colaborador já cadastrado.
 */
export type PostEmployees409 = {
  /**
   * @type string
   */
  message: string
}

export const postEmployeesMutationRequestDocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type PostEmployeesMutationRequestDocumentTypeEnum =
  (typeof postEmployeesMutationRequestDocumentTypeEnum)[keyof typeof postEmployeesMutationRequestDocumentTypeEnum]

export const postEmployeesMutationRequestGenderEnum = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const

export type PostEmployeesMutationRequestGenderEnum = (typeof postEmployeesMutationRequestGenderEnum)[keyof typeof postEmployeesMutationRequestGenderEnum]

export type PostEmployeesMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @minLength 1
   * @type string
   */
  phone: string
  /**
   * @type string | undefined
   */
  phone_2?: string
  /**
   * @type string
   */
  document_type: PostEmployeesMutationRequestDocumentTypeEnum
  /**
   * @minLength 1
   * @type string
   */
  document: string
  /**
   * @type string | undefined
   */
  document_2?: string
  /**
   * @minLength 1
   * @type string, email
   */
  email: string
  /**
   * @type string | undefined
   */
  state_registration?: string
  /**
   * @type boolean | undefined
   */
  tax_free?: boolean
  /**
   * @type string | undefined
   */
  gender?: PostEmployeesMutationRequestGenderEnum
  /**
   * @type string | undefined, date-time
   */
  birth_date?: string
  /**
   * @minLength 1
   * @type string
   */
  recipient_name: string
  /**
   * @minLength 1
   * @type string
   */
  recipient_phone: string
  /**
   * @minLength 1
   * @type string
   */
  cep: string
  /**
   * @minLength 1
   * @type string
   */
  street: string
  /**
   * @minLength 1
   * @type string
   */
  number: string
  /**
   * @type string | undefined
   */
  complement?: string
  /**
   * @minLength 1
   * @type string
   */
  neighborhood: string
  /**
   * @minLength 1
   * @type string
   */
  city: string
  /**
   * @minLength 1
   * @type string
   */
  state: string
}

export type PostEmployeesMutationResponse = PostEmployees201

export type PostEmployeesMutation = {
  Response: PostEmployees201
  Request: PostEmployeesMutationRequest
  Errors: PostEmployees401 | PostEmployees409
}