/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const postOrders201Enum = {
  null: 'null',
} as const

export type PostOrders201Enum = (typeof postOrders201Enum)[keyof typeof postOrders201Enum]

/**
 * @description Pedido criado com sucesso.
 */
export type PostOrders201 = PostOrders201Enum | null

/**
 * @description Dados inválidos.
 */
export type PostOrders400 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Usuário não autenticado.
 */
export type PostOrders401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Cliente ou Endereço não encontrado.
 */
export type PostOrders404 = {
  /**
   * @type string
   */
  message: string
}

export const postOrdersMutationRequestStatusEnum = {
  PROCESSED: 'PROCESSED',
  CANCELLED: 'CANCELLED',
} as const

export type PostOrdersMutationRequestStatusEnum = (typeof postOrdersMutationRequestStatusEnum)[keyof typeof postOrdersMutationRequestStatusEnum]

export const postOrdersMutationRequestShippingCarrierEnum = {
  CORREIOS: 'CORREIOS',
  JADLOG: 'JADLOG',
} as const

export type PostOrdersMutationRequestShippingCarrierEnum =
  (typeof postOrdersMutationRequestShippingCarrierEnum)[keyof typeof postOrdersMutationRequestShippingCarrierEnum]

export const postOrdersMutationRequestPaymentMethodEnum = {
  CREDIT_CARD: 'CREDIT_CARD',
  DEBIT_CARD: 'DEBIT_CARD',
  PIX: 'PIX',
} as const

export type PostOrdersMutationRequestPaymentMethodEnum =
  (typeof postOrdersMutationRequestPaymentMethodEnum)[keyof typeof postOrdersMutationRequestPaymentMethodEnum]

export type PostOrdersMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  customer_id: string
  /**
   * @minLength 1
   * @type string
   */
  address_id: string
  /**
   * @default "PROCESSED"
   * @type string | undefined
   */
  status?: PostOrdersMutationRequestStatusEnum
  /**
   * @default "CORREIOS"
   * @type string | undefined
   */
  shipping_carrier?: PostOrdersMutationRequestShippingCarrierEnum
  /**
   * @type string
   */
  payment_method: PostOrdersMutationRequestPaymentMethodEnum
  /**
   * @minLength 0
   * @default 0
   * @type number | undefined
   */
  shipping_cost?: number
  /**
   * @type array
   */
  items: {
    /**
     * @minLength 1
     * @type string
     */
    product_variation_id: string
    /**
     * @minLength 1
     * @type number
     */
    quantity: number
    /**
     * @minLength 0
     * @type number
     */
    discount: number
  }[]
}

export type PostOrdersMutationResponse = PostOrders201

export type PostOrdersMutation = {
  Response: PostOrders201
  Request: PostOrdersMutationRequest
  Errors: PostOrders400 | PostOrders401 | PostOrders404
}