/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Usuário autenticado com sucesso.
 */
export type PostSessionsPassword200 = {
  /**
   * @type string
   */
  access_token: string
  /**
   * @type string
   */
  refresh_token: string
}

/**
 * @description E-mail ou senha incorretos.
 */
export type PostSessionsPassword400 = {
  /**
   * @type string
   */
  message: string
}

export type PostSessionsPasswordMutationRequest = {
  /**
   * @minLength 1
   * @type string, email
   */
  email: string
  /**
   * @minLength 6
   * @type string
   */
  password: string
}

export type PostSessionsPasswordMutationResponse = PostSessionsPassword200

export type PostSessionsPasswordMutation = {
  Response: PostSessionsPassword200
  Request: PostSessionsPasswordMutationRequest
  Errors: PostSessionsPassword400
}