/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PutCustomersIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const putCustomersId200Enum = {
  null: 'null',
} as const

export type PutCustomersId200Enum = (typeof putCustomersId200Enum)[keyof typeof putCustomersId200Enum]

/**
 * @description Cliente atualizado com sucesso.
 */
export type PutCustomersId200 = PutCustomersId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type PutCustomersId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Cliente não encontrado.
 */
export type PutCustomersId404 = {
  /**
   * @type string
   */
  message: string
}

export const putCustomersIdMutationRequestDocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type PutCustomersIdMutationRequestDocumentTypeEnum =
  (typeof putCustomersIdMutationRequestDocumentTypeEnum)[keyof typeof putCustomersIdMutationRequestDocumentTypeEnum]

export const putCustomersIdMutationRequestGenderEnum = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const

export type PutCustomersIdMutationRequestGenderEnum = (typeof putCustomersIdMutationRequestGenderEnum)[keyof typeof putCustomersIdMutationRequestGenderEnum]

export type PutCustomersIdMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @minLength 1
   * @type string
   */
  phone: string
  /**
   * @type string | undefined
   */
  phone_2?: string
  /**
   * @type string
   */
  document_type: PutCustomersIdMutationRequestDocumentTypeEnum
  /**
   * @minLength 1
   * @type string
   */
  document: string
  /**
   * @type string | undefined
   */
  document_2?: string
  /**
   * @minLength 1
   * @type string, email
   */
  email: string
  /**
   * @type string | undefined
   */
  state_registration?: string
  /**
   * @type boolean | undefined
   */
  tax_free?: boolean
  /**
   * @type string | undefined
   */
  gender?: PutCustomersIdMutationRequestGenderEnum
  /**
   * @type string | undefined, date-time
   */
  birth_date?: string
  /**
   * @type boolean | undefined
   */
  problematic?: boolean
  /**
   * @minLength 1
   * @pattern ^[cC][^\s-]{8,}$
   * @type string
   */
  address_id: string
  /**
   * @minLength 1
   * @type string
   */
  recipient_name: string
  /**
   * @minLength 1
   * @type string
   */
  recipient_phone: string
  /**
   * @minLength 1
   * @type string
   */
  cep: string
  /**
   * @minLength 1
   * @type string
   */
  street: string
  /**
   * @minLength 1
   * @type string
   */
  number: string
  /**
   * @type string | undefined
   */
  complement?: string
  /**
   * @minLength 1
   * @type string
   */
  neighborhood: string
  /**
   * @minLength 1
   * @type string
   */
  city: string
  /**
   * @minLength 1
   * @type string
   */
  state: string
}

export type PutCustomersIdMutationResponse = PutCustomersId200

export type PutCustomersIdMutation = {
  Response: PutCustomersId200
  Request: PutCustomersIdMutationRequest
  PathParams: PutCustomersIdPathParams
  Errors: PutCustomersId401 | PutCustomersId404
}