/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PutOrdersIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const putOrdersId200Enum = {
  null: 'null',
} as const

export type PutOrdersId200Enum = (typeof putOrdersId200Enum)[keyof typeof putOrdersId200Enum]

/**
 * @description Pedido atualizado com sucesso.
 */
export type PutOrdersId200 = PutOrdersId200Enum | null

/**
 * @description Dados inválidos.
 */
export type PutOrdersId400 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Usuário não autenticado.
 */
export type PutOrdersId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Pedido não encontrado.
 */
export type PutOrdersId404 = {
  /**
   * @type string
   */
  message: string
}

export const putOrdersIdMutationRequestStatusEnum = {
  PROCESSED: 'PROCESSED',
  CANCELLED: 'CANCELLED',
} as const

export type PutOrdersIdMutationRequestStatusEnum = (typeof putOrdersIdMutationRequestStatusEnum)[keyof typeof putOrdersIdMutationRequestStatusEnum]

export const putOrdersIdMutationRequestShippingCarrierEnum = {
  CORREIOS: 'CORREIOS',
  JADLOG: 'JADLOG',
} as const

export type PutOrdersIdMutationRequestShippingCarrierEnum =
  (typeof putOrdersIdMutationRequestShippingCarrierEnum)[keyof typeof putOrdersIdMutationRequestShippingCarrierEnum]

export const putOrdersIdMutationRequestPaymentMethodEnum = {
  CREDIT_CARD: 'CREDIT_CARD',
  DEBIT_CARD: 'DEBIT_CARD',
  PIX: 'PIX',
} as const

export type PutOrdersIdMutationRequestPaymentMethodEnum =
  (typeof putOrdersIdMutationRequestPaymentMethodEnum)[keyof typeof putOrdersIdMutationRequestPaymentMethodEnum]

export type PutOrdersIdMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  customer_id: string
  /**
   * @minLength 1
   * @type string
   */
  address_id: string
  /**
   * @default "PROCESSED"
   * @type string | undefined
   */
  status?: PutOrdersIdMutationRequestStatusEnum
  /**
   * @default "CORREIOS"
   * @type string | undefined
   */
  shipping_carrier?: PutOrdersIdMutationRequestShippingCarrierEnum
  /**
   * @type string
   */
  payment_method: PutOrdersIdMutationRequestPaymentMethodEnum
  /**
   * @minLength 0
   * @default 0
   * @type number | undefined
   */
  shipping_cost?: number
  /**
   * @type array
   */
  items: {
    /**
     * @minLength 1
     * @type string
     */
    product_variation_id: string
    /**
     * @minLength 1
     * @type number
     */
    quantity: number
    /**
     * @minLength 0
     * @type number
     */
    discount: number
  }[]
  /**
   * @description Retornar itens do pedido anterior ao estoque
   * @default true
   * @type boolean | undefined
   */
  return_previous_items_to_stock?: boolean
  /**
   * @description Remover itens do novo pedido do estoque
   * @default true
   * @type boolean | undefined
   */
  remove_current_items_from_stock?: boolean
}

export type PutOrdersIdMutationResponse = PutOrdersId200

export type PutOrdersIdMutation = {
  Response: PutOrdersId200
  Request: PutOrdersIdMutationRequest
  PathParams: PutOrdersIdPathParams
  Errors: PutOrdersId400 | PutOrdersId401 | PutOrdersId404
}