/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PutProductsIdPathParams = {
  /**
   * @type string
   */
  id: string
}

export const putProductsId200Enum = {
  null: 'null',
} as const

export type PutProductsId200Enum = (typeof putProductsId200Enum)[keyof typeof putProductsId200Enum]

/**
 * @description Produto atualizado com sucesso.
 */
export type PutProductsId200 = PutProductsId200Enum | null

/**
 * @description Usuário não autenticado.
 */
export type PutProductsId401 = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Produto, marca ou fornecedor não encontrado.
 */
export type PutProductsId404 = {
  /**
   * @type string
   */
  message: string
}

export type PutProductsIdMutationRequest = {
  /**
   * @type string | undefined
   */
  supplier_id?: string
  /**
   * @type string | undefined
   */
  product_measurement_unit_id?: string
  /**
   * @type string | undefined
   */
  product_brand_id?: string
  /**
   * @type array | undefined
   */
  product_category_ids?: {
    /**
     * @type string
     */
    id: string
  }[]
  /**
   * @minLength 1
   * @type string
   */
  reference_code: string
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @type string | undefined
   */
  model?: string
  /**
   * @type string | undefined
   */
  description?: string
  /**
   * @type integer | undefined
   */
  ncm?: number
  /**
   * @type integer | undefined
   */
  cfop?: number
  /**
   * @type string | undefined
   */
  cest?: string
  /**
   * @type string | undefined
   */
  merchandise_origin?: string
}

export type PutProductsIdMutationResponse = PutProductsId200

export type PutProductsIdMutation = {
  Response: PutProductsId200
  Request: PutProductsIdMutationRequest
  PathParams: PutProductsIdPathParams
  Errors: PutProductsId401 | PutProductsId404
}