/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ToZod } from '@kubb/plugin-zod/utils'
import type { PostUsers201Type, PostUsers409Type, PostUsersMutationRequestType, PostUsersMutationResponseType } from '../../types/users/PostUsersType'
import { z } from 'zod'

/**
 * @description Usuário cadastrado com sucesso.
 */
export const postUsers201Schema = z.enum(['null']).describe('Usuário cadastrado com sucesso.').nullable() as unknown as ToZod<PostUsers201Type>

/**
 * @description Este email já está cadastrado em nossa base de dados.
 */
export const postUsers409Schema = z
  .object({
    message: z.string(),
  })
  .describe('Este email já está cadastrado em nossa base de dados.') as unknown as ToZod<PostUsers409Type>

export const postUsersMutationRequestSchema = z.object({
  name: z.string().min(1),
  email: z.string().email().min(1),
  password: z.string().min(6),
}) as unknown as ToZod<PostUsersMutationRequestType>

export const postUsersMutationResponseSchema = z.lazy(() => postUsers201Schema) as unknown as ToZod<PostUsersMutationResponseType>