/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const postEmployees201Enum = {
  null: 'null',
} as const

export type PostEmployees201EnumType = (typeof postEmployees201Enum)[keyof typeof postEmployees201Enum]

/**
 * @description Colaborador cadastrado com sucesso.
 */
export type PostEmployees201Type = PostEmployees201EnumType | null

/**
 * @description Usuário não autenticado.
 */
export type PostEmployees401Type = {
  /**
   * @type string
   */
  message: string
}

/**
 * @description Colaborador já cadastrado.
 */
export type PostEmployees409Type = {
  /**
   * @type string
   */
  message: string
}

export const postEmployeesMutationRequestDocumentTypeEnum = {
  PERSON: 'PERSON',
  COMPANY: 'COMPANY',
} as const

export type PostEmployeesMutationRequestDocumentTypeEnumType =
  (typeof postEmployeesMutationRequestDocumentTypeEnum)[keyof typeof postEmployeesMutationRequestDocumentTypeEnum]

export const postEmployeesMutationRequestGenderEnum = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const

export type PostEmployeesMutationRequestGenderEnumType = (typeof postEmployeesMutationRequestGenderEnum)[keyof typeof postEmployeesMutationRequestGenderEnum]

export type PostEmployeesMutationRequestType = {
  /**
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @minLength 1
   * @type string
   */
  phone: string
  /**
   * @type string | undefined
   */
  phone_2?: string
  /**
   * @type string
   */
  document_type: PostEmployeesMutationRequestDocumentTypeEnumType
  /**
   * @minLength 1
   * @type string
   */
  document: string
  /**
   * @type string | undefined
   */
  document_2?: string
  /**
   * @minLength 1
   * @type string, email
   */
  email: string
  /**
   * @type string | undefined
   */
  state_registration?: string
  /**
   * @type boolean | undefined
   */
  tax_free?: boolean
  /**
   * @type string | undefined
   */
  gender?: PostEmployeesMutationRequestGenderEnumType
  /**
   * @type string | undefined, date-time
   */
  birth_date?: string
  /**
   * @minLength 1
   * @type string
   */
  recipient_name: string
  /**
   * @minLength 1
   * @type string
   */
  recipient_phone: string
  /**
   * @minLength 1
   * @type string
   */
  cep: string
  /**
   * @minLength 1
   * @type string
   */
  street: string
  /**
   * @minLength 1
   * @type string
   */
  number: string
  /**
   * @type string | undefined
   */
  complement?: string
  /**
   * @minLength 1
   * @type string
   */
  neighborhood: string
  /**
   * @minLength 1
   * @type string
   */
  city: string
  /**
   * @minLength 1
   * @type string
   */
  state: string
}

export type PostEmployeesMutationResponseType = PostEmployees201Type

export type PostEmployeesTypeMutation = {
  Response: PostEmployees201Type
  Request: PostEmployeesMutationRequestType
  Errors: PostEmployees401Type | PostEmployees409Type
}